### ISSUE TITLE
[bug] Title bar not showing when using translucid/white GTK Theme

### ISSUE THREAD

**Issue by GabrielCasarin** [johnfactotum/foliate#389] opened 2020-05-27 01:29 UTC
When my desktop is using the GTK theme Materia Light and the foreground of Foliate is in the white theme, the title bar does not show the icons and the title of the book.
But, when I click at the positions where the buttons where suposed to be, their window boxes appear.

![foliate](https://user-images.githubusercontent.com/7823137/82965811-98c6c000-9f9f-11ea-919c-99e50a5821bf.png)

**Comment by johnfactotum** [comment] 2020-05-27 02:30
Duplicate of https://github.com/johnfactotum/foliate/issues/316. This has been fixed with 0edfa0269c4b3be4744c2aeb930630f59cd3390c and 0ba940be568265f33ddf322b931cad7de005044e.

**Closed by johnfactotum** 2020-05-27 02:30 UTC
Labels: duplicate
