### ISSUE TITLE
foliate is not able to turn to next page if reading an epub that is set up with right-to-left page turn direction (like manga)

### ISSUE THREAD

**Issue by madsl** [johnfactotum/foliate#921] opened 2022-07-25 18:52 UTC
If you try to read an epub that is set up for right-to-left page turning direction (so you should press the left button for next page), it does not work at all. The only way to turn to a page, is selecting the page through the slider.

This is the output when pressing the left page key (The left key correctly says Next page):
decodeURI("..."),
...
Gjs-Message: 20:51:13.382: JS LOG: cover
Gjs-Message: 20:51:13.390: JS LOG: book-ready
Gjs-Message: 20:51:13.390: JS LOG: run_javascript: JSON.stringify(book.package.metadata)
Gjs-Message: 20:51:13.390: JS LOG: run_javascript: JSON.stringify(book.navigation.toc)
Gjs-Message: 20:51:13.391: JS LOG: failed to get file info
Gjs-Message: 20:51:13.392: JS LOG: saving file uri
Gjs-Message: 20:51:13.393: JS LOG: run_javascript: loadLocations(null)
Gjs-Message: 20:51:13.393: JS LOG: run_javascript: render()
Gjs-Message: 20:51:13.456: JS LOG: rendition-ready
Gjs-Message: 20:51:13.457: JS LOG: run_javascript: setStyle({"fontFamily":"Serif","fontSize":16,"fontWeight":400,"fontStyle":"normal","fontStretch":"normal","spacing":1.5,"margin":40,"maxWidth":1400,"usePublisherFont":false,"justify":true,"hyphenate":...
Gjs-Message: 20:51:13.457: JS LOG: run_javascript: setupRendition()
Gjs-Message: 20:51:13.457: JS LOG: run_javascript: display('epubcfi(/6/8!/4/1:0)')
Gjs-Message: 20:51:13.491: JS LOG: layout
Gjs-Message: 20:51:13.502: JS LOG: relocated
Gjs-Message: 20:51:13.502: JS LOG: epubcfi(/6/2!/4/1:0)
Gjs-Message: 20:51:13.552: JS LOG: book-displayed
Gjs-Message: 20:51:13.593: JS LOG: relocated
Gjs-Message: 20:51:13.593: JS LOG: epubcfi(/6/8!/4/1:0)
Gjs-Message: 20:51:14.394: JS LOG: writing to /home/mads/.local/share/com.github.johnfactotum.Foliate/library/uri-store.json
Gjs-Message: 20:51:14.594: JS LOG: writing to /home/mads/.local/share/com.github.johnfactotum.Foliate/urn%3Auuid%3A7a2b9c01-e15f-4807-8137-54fd8080e88c.json
Gjs-Message: 20:51:14.596: JS LOG: book list: updating urn:uuid:7a2b9c01-e15f-4807-8137-54fd8080e88c
Gjs-Message: 20:51:14.596: JS LOG: book list: updating urn:uuid:7a2b9c01-e15f-4807-8137-54fd8080e88c
Gjs-Message: 20:51:16.174: JS LOG: run_javascript: rendition.next()
Gjs-Message: 20:51:16.187: JS LOG: relocated
Gjs-Message: 20:51:16.187: JS LOG: epubcfi(/6/8!/4/1:0)
Gjs-Message: 20:51:17.190: JS LOG: writing to /home/mads/.local/share/com.github.johnfactotum.Foliate/urn%3Auuid%3A7a2b9c01-e15f-4807-8137-54fd8080e88c.json
Gjs-Message: 20:51:17.191: JS LOG: book list: updating urn:uuid:7a2b9c01-e15f-4807-8137-54fd8080e88c
Gjs-Message: 20:51:17.192: JS LOG: book list: updating urn:uuid:7a2b9c01-e15f-4807-8137-54fd8080e88c

**Comment by johnfactotum** [comment] 2022-07-31 02:26
I think this is https://github.com/futurepress/epub.js/issues/1069.

**Comment by johnfactotum** [comment] 2022-10-19 17:31
Duplicate of #415

**Closed by johnfactotum** 2022-10-19 17:31 UTC
Labels: bug, epub.js
