### ISSUE TITLE
Missing spaces in rendering after <span>

### ISSUE THREAD

**Issue by nebulon42** [johnfactotum/foliate#498] opened 2020-06-25 20:34 UTC
In version 2.1.1 consider the following source
```
<p><span id="p2.67" epub:type="paragraph-number">67</span>
[...]
Dienstag gab es<span epub:type="pagebreak" id="page397" title="397"/> Specknudel mit Kraut, am 
Mittwoch wurde ein
[...]
</p>
```
which leads to the rendering
![rendering](https://user-images.githubusercontent.com/3531092/85792206-6ee5f200-b733-11ea-9454-81dfca3c171d.png)

The rendering misses a space between "es" and "Specknudel". This is the position where the `<span>` is located. After the span a space is present in the source.

**Comment by johnfactotum** [comment] 2020-06-26 02:21
A few different ideas:
- We do not provide a default style for `epub:type="pagebreak`
- If the book styles the `<span>` with CSS with selectors like `span[epub|type~="pagebreak"]`, it won't have any effect when the page is rendered as HTML, since HTML does not support XML namespaces. Before b447f6f82c78fbfc43ec141d73ff79c9515ff327, everything was being rendered as HTML even though it's parsed as XHTML. This is really an Epub.js bug.
- In some situations, the page is incorrectly parsed as HTML, which would make the `<span>` not close immediatly. See #275 and #288.

However, I think none of these issues would have caused the space to disappear. Maybe you can go to the menu > _Advanced_ > _Enable Developer Tools_, then right click on the paragraph and choose _Inspect Element_ and see how it's actually being rendered.

**Comment by nebulon42** [comment] 2020-06-26 18:29
Thanks for the information and also for the info that you are using Epub.js. Could have found out myself.
The styling for the element looks like:
```
*[epub|type='pagebreak']{
	display: none;
}
```
In the inspector it shows that the space is somehow removed while the closing tag is correct:
![inspector](https://user-images.githubusercontent.com/3531092/85886480-7ca87f80-b7e6-11ea-9267-2ca1daf402c7.png)

I checked in my own VueJS based reader using Epub.js 0.3.85 I'm developing and also there the problem occurs.
![inspector2](https://user-images.githubusercontent.com/3531092/85889344-939da080-b7eb-11ea-9aec-c2c5d25b7df6.png)

So this is a upstream bug. Do you want to track that here or should I close?

**Comment by johnfactotum** [comment] 2020-06-27 01:54
OK. Closing this as _not our bug_, then.

Still I'm confused. I tried to reproduce this by editing a book to contain a span tag like that, and everything works as expected.

**Closed** 2020-06-27 01:54 UTC
Labels: not our bug

**Comment by nebulon42** [comment] 2020-06-27 10:49
I just inspected the built e-book (not the source from which it is built) and there the space is also missing. Seems like my build tool (standard ebooks) trims that away. Sorry for the noise.
