### ISSUE TITLE
Some font colors are not configurable

### ISSUE THREAD

**Issue by winterwolf** [johnfactotum/foliate#634] opened 2020-11-29 06:20 UTC
Red text is not readable in dark theme:

![screenshot-001](https://user-images.githubusercontent.com/42620439/100534779-3931c180-321b-11eb-9b75-1c29003fd871.png)

In white theme it looks fine:

![screenshot-002](https://user-images.githubusercontent.com/42620439/100534801-6f6f4100-321b-11eb-8c88-e75953a20409.png)

**Comment by johnfactotum** [comment] 2021-02-17 08:00
Duplicate of #265

**Closed by johnfactotum** 2021-02-17 08:00 UTC
Labels: bug
