### ISSUE TITLE
Broken gui fonts on Ubuntu 21.10

### ISSUE THREAD

**Issue by monsieurdanna** [johnfactotum/foliate#865] opened 2022-02-07 08:44 UTC
Just installed via Snap, fonts from interface are not being shown correctly.

**Screenshots**
![Screenshot from 2022-02-07 03-40-13](https://user-images.githubusercontent.com/19712386/152753702-c348db8e-6dfe-4657-b150-1b7d8059235a.png)
![Screenshot from 2022-02-07 03-42-52](https://user-images.githubusercontent.com/19712386/152753783-24ee3618-809d-460b-8a47-a4151e02dc61.png)

**Version:**
 - Foliate version: 2.6.3
 - OS/Distribution and version: Ubuntu 21.10
 - Desktop environment: Gnome 40.4.0
 - Installation method: Snap

**Comment by ngirard** [comment] 2022-02-16 11:02
I'm in the same boat. Ubuntu 21.10.
I've tried all available deb packages (Foliate versions 2.6.1 to 2.6.4), to no avail.

What makes this problem critical, is that the text is too small to be readable.

**Comment by ngirard** [comment] 2022-02-16 11:20
I managed to restore the correct font size at the price of overzooming the UI by
1. installing a deb package
2. executing
    ```sh
    env GDK_DPI_SCALE=2.0 /usr/bin/com.github.johnfactotum.Foliate <file.epub>
   ```

@monsieurdanna, could you pelase try and report back ?

**Comment by ngirard** [comment] 2022-02-16 12:30
Turns out that on my machine, this was caused by `Xft.dpi` erroneously set to 0:
```sh
xrdb -query | grep dpi
Xft.dpi:        0
```
A direct forkaround consists in
1. Adding `Xft.dpi: 96` to `~/.Xresources`
2. Executing `xrdb -merge ~/.Xresources`

However, this is not a satisfactory solution: I couldn't pinpoint what caused `Xft.dpi` to be set to 0 in the first place.

Furthermore, this is not an acceptable solution to this issue. Indeed, since
> The X _server DPI_ is, on the other hand, barely used. Common GUI toolkits like Qt and GTK don't care about that setting, not even a little. Icons and things like that won't change.
> — [src](https://linuxreviews.org/HOWTO_set_DPI_in_Xorg)

the expected behaviour of Foliate and its underlying libs here should be to fall back to the value of 96, which is today's tookits choice.

**Comment by monsieurdanna** [comment] 2022-02-17 03:41
Well, here Xft.dpi is correctly set to 96, will try installing from deb and using the GDK_DPI_SCALE=2.0 option. Thanks!

**Comment by johnfactotum** [comment] 2022-02-24 10:02
Duplicate of #820, I think

**Closed by johnfactotum** 2022-02-24 10:02 UTC
Labels: bug
