### ISSUE TITLE
add pdf

### ISSUE THREAD

**Issue by elibr1212** [johnfactotum/foliate#1070] opened 2023-08-18 19:52 UTC
I accidentally downloaded an EPUB file
and I used your software (it was installed on my computer / it seems to me that I downloaded it to my computer once and installed it..)
I activated
Wow, I really liked it!!

Then I said ok. Let's see if it's possible to open PDF files and it didn't work and it's sucks
that it doesn't work and there is no such option 
.
Your software is really good! Is it possible for you to add a PDF? I happened to see in a Google search that they asked you to add a PDF
What happened in the end?

**Comment by johnfactotum** [comment] 2023-08-31 10:52
>  What happened in the end?

Literally nothing happened, which is why there's still no PDF support :)

Closing this as a duplicate of #139.

**Closed by johnfactotum** 2023-08-31 10:52 UTC
Labels: enhancement
