### ISSUE TITLE
Add keyboard shortcut for translate feature

### ISSUE THREAD

**Issue by Ja7ad** [johnfactotum/foliate#806] opened 2021-11-08 06:11 UTC
Please add keyboard shortcut for fast translation

**Comment by apandada1** [comment] 2021-11-09 14:02
Do you want the whole book to be translated at once?

**Comment by Ja7ad** [comment] 2021-11-09 15:51
> Do you want the whole book to be translated at once?

No just selected words.

To use the translate feature, right-click on a word is required, but it's better to add a keyboard shortcut.

for example `Ctrl + X` or `Ctrl + Z`

**Comment by johnfactotum** [comment] 2021-11-23 03:38
Duplicate of #540

**Closed by johnfactotum** 2021-11-23 03:38 UTC
Labels: enhancement
