### ISSUE TITLE
I open the same book every time

### ISSUE THREAD

**Issue by aystmi** [johnfactotum/foliate#1258] opened 2024-02-23 17:54 UTC
I open the same book every time, even if I open a new book now, close and reopen the old book before, and there is only one book in all books

**Version:**
 - Foliate version: 3.1.0
 - OS/Distribution and version: 6.7.5-arch1-1
 - Desktop environment: GNOME 45
 - Installation method: pacman

**Comment by chenkeao** [comment] 2024-03-03 11:54
I use the same OS and DE as you and the problems for me are even worse and weirder. Sometimes, I clicked a book existing in my library, but another one that was not in the library was opened. Some books failed to be added continuously. The maintainer told me that the problems lie with the tracker3, you can check it.

**Comment by johnfactotum** [comment] 2024-03-16 09:56
Duplicate of #1231.

**Closed as not planned by johnfactotum** 2024-03-16 09:56 UTC
Labels: duplicate, question
