### ISSUE TITLE
Don't have a library button

### ISSUE THREAD

**Issue by tonypachino** [johnfactotum/foliate#784] opened 2021-09-15 17:17 UTC
**Describe the bug**
i would like to have in upper menu some button that will bring me back to my library instead i have to close the app and again, open the app so that i can see all of my books again.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Version:**
 - Foliate version:
 - OS/Distribution and version: [e.g. Ubuntu 18.04]
 - Desktop environment: [e.g. GNOME 3.36]
 - Installation method: [e.g. Flatpak]

**Additional context**

**Comment by johnfactotum** [comment] 2021-09-17 07:50
I think this counts as a duplicate of #509 as fixing #509 will imply fixing this issue.

**Closed by johnfactotum** 2021-09-17 07:50 UTC
Labels: bug
