### ISSUE TITLE
Page Flipping Animation

### ISSUE THREAD

**Issue by kdwk** [johnfactotum/foliate#659] opened 2021-01-25 06:31 UTC
**Is your feature request related to a problem? Please describe.**
Currently, flipping pages is a static, hard, abrupt process. You are on one page, you press, and suddenly another page appears. This makes the experience not as smooth as could be.

**Describe the solution you'd like**
Having a smooth page flipping transition animation like the one found in Apple Books. See attached video to see what I mean.

https://user-images.githubusercontent.com/39268094/105669281-e96d2f00-5f19-11eb-9223-b95c1e95ab3a.mp4

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by johnfactotum** [comment] 2021-01-25 13:20
Duplicate of #188

**Closed by johnfactotum** 2021-01-25 13:20 UTC
Labels: enhancement
