### ISSUE TITLE
Make text-to-speech feature more discoverable

### ISSUE THREAD

**Issue by dspacejs** [johnfactotum/foliate#672] opened 2021-02-13 08:19 UTC
**Is your feature request related to a problem? Please describe.**
It'd be great if you can listen to your books with a text-to-speech feature, which can transform any eBook into an audiobook.

**Describe the solution you'd like**
A button somewhere for text-to-speech. Highlight the active word currently being spoken, and automatically scroll the page to keep in sync with the current spoken word. Perhaps also skip redundant text, like the table of contents.

**Describe alternatives you've considered**
Not all books have audiobooks. It'd also be handy to do this, so you don't have to get a copy of an audiobook for whatever book you're reading.

**Comment by itprojects** [comment] 2021-02-13 12:50
This is not a bug/issue.

The described feature already exists in Foliate.

1. Start Foliate, open a book.
2. Press "Text-to-speech" button (in bottom bar, right side).
3. Alternatively, select one word, a context menu opens, then press "Start-from-here" .

Note: For this all to work you need to have a TTS reader - i. e. `espeak`, `festival`, `spd-say`.

**Comment by dspacejs** [comment] 2021-02-14 00:32
@itprojects additionally I had to set the TTS command in the settings, but now it works.

Perhaps this should be clearer in the UI? It only showed after I configured it in the settings. Maybe it should just show by default, except the TTS button/dropdown item for "Start from here" are disabled (with a hint saying to configure it)

**Comment by itprojects** [comment] 2021-02-15 08:34
@dspacejs From the README.md:

> Basic text-to-speech support with eSpeak NG and Festival

> For text-to-speech support, install espeak-ng, or festival, and packages for the individual voices.

Adding a suggestion to the UI implies that there only a very specific set of apps to check for Text-to-speech (TTS). This is a problem, because there are many apps that can provide TTS. Some are online, some are offline, some are FOSS, some are blobs. A detection mechanism will give false positives, thus causing more confusion.

**Comment by dspacejs** [comment] 2021-02-15 11:06
@itprojects people shouldn't have to read the full README to know that. I downloaded this app a long time ago, so even if I saw that bit in the README, I must have forgot. The UI should make it obvious rudimentary functionality like this exists and be seamless.

You don't have to auto-detect the TTS. I see two feasible solutions:

1. Add a dependency to the app for whatever the best TTS software is. If it's already installed on the user's machine, then it won't be downloaded twice.
2. What I mentioned earlier, about revealing the UI for this, but disabling it (so the user can't click the TTS button or anything) until it's configured in the settings.

The first is far more preferable and is seamless. It works without any configuration. It also means the user doesn't have to bother going through the different TTS options, and manually select the best one. I've never used TTS on Linux before, so it's a hassle to have to do that.

**Comment by itprojects** [comment] 2021-02-15 12:15
@dspacejs Option 1 creates a permanent dependency barrier to Foliate adoption. It can also cause compilation problems for those (and there are some) that want to compile from source.

The better would be Option 2 "Grayed out button", since the button is already there, just need to disable, instead of hide. Then the user will look at the `Readme.md`, maybe even without being asked, and install a TTS package.

You are right that maybe the design of this part of Foliate should be looked at, but design is no panacea.

**Comment by johnfactotum** [comment] 2021-02-17 07:56
The button doesn't have to be grayed out. If the TTS command is not set, it can just show the TTS configuration dialog when you click on it. One downside of this is that it can be a little distracting for people who don't use TTS at all.

**Comment by itprojects** [comment] 2021-02-17 11:03
@johnfactotum Perhaps an updated Readme.md with a section on the typical settings? 

List of known configurations:

**espeak-ng**:

espeak-ng -a 100 -g 1 -p 50 -s 160

espeak-ng -v mb-en1 -a 100 -g 1 -p 50 -s 160

**mimic**:

mimic -f /dev/stdin

mimic -f /dev/stdin -voice slt

**Comment by johnfactotum** [comment] 2022-09-23 18:15
Closing this in favor of #829

**Closed by johnfactotum** 2022-09-23 18:15 UTC
Labels: enhancement
