### ISSUE TITLE
Can't open the epubs in foliate

### ISSUE THREAD

**Issue by Yugeniki** [johnfactotum/foliate#698] opened 2021-03-26 13:30 UTC
**Describe the bug**
The software is unable to do what it has promised to do. It can't open epubs I have manually added. It can't open books I downloaded through catalogs. It also refuses to save the later, but has no problem with keeping the former.

**To Reproduce**
I have done a clean install of arcolinux and it hasn't changed much. The problem most be on software side. Running it through terminal tells me I must use imports.gi.settings to choose a gtk. I have no idea how to do that. 

**Version:**
 - Foliate version: Newest 
 - OS/Distribution and version: Arcolinux
 - Desktop environment: Gnome
 - Installation method: Pacman

Update: I have disabled tracker. Still can't open epubs. 
Another update: It now crashes the app if I try to open from~/.local directory.
Yet another update, after trying with sudo foliate and trying to click on the link I receive new errors. No idea seems to be dbus related now?
New update: Opening books in regular run foliate now results in foliate crashing. D-foot, a dbus fixer, has revealed that the dbus of foliate is not activable. 
Newest update: Foliate-git doesn't work either way.

**Comment by nmlt** [comment] 2021-03-26 19:44
I had the same problem, but after manually building and making sure the old version wasn't launched foliate worked again. Like the OP [here](https://bbs.archlinux.org/viewtopic.php?id=264901) said, it seems like this is a problem with the updated dependencies in archlinux.

**Comment by johnfactotum** [comment] 2021-03-27 02:36
The version in `community` is `folaite 2.5.0`, which cannot open books if you have `gjs 1.68`. See #689. This should be fixed with 2.6.x. If it still can't open books with the latest version, 2.6.2, please run with `--verbose` and post the output.

**Comment by anonimasusan** [comment] 2021-03-27 07:38
Appologies for hijacking thread, but I have similar issue under uptodate Arch Linux. It worked fine last week.
foliate foo.epub --verbose doesn't open  and yields:

(com.github.johnfactotum.Foliate:15016): Gjs-CRITICAL **: 08:37:59.611: JS ERROR: TypeError: "file" is read-only
open@resource:///com/github/johnfactotum/Foliate/js/window.js:1004:9
_init@resource:///com/github/johnfactotum/Foliate/js/window.js:965:29
main/</<@resource:///com/github/johnfactotum/Foliate/js/main.js:310:29
main/<@resource:///com/github/johnfactotum/Foliate/js/main.js:304:22
main@resource:///com/github/johnfactotum/Foliate/js/main.js:474:24
run@resource:///org/gnome/gjs/modules/script/package.js:206:19
@/usr/bin/foliate:9:17

**Comment by Yugeniki** [comment] 2021-03-27 07:50
For whoever it may concern, the suggested solution of manually building proved ineffective. 
I, however, found a way. By accident. 

In the process of checking if it is DE specific, I installed Mate and Xfce. The barest minimum. After that Foliate started working in all DE. 

It seems there is a dependency that isn't explicitly listed, but is required nevertheless. Perhaps John could look into to it, but I won't. My care ends here.  

I suggest keeping this open as my solution may not work for all, and the issue may be more tricky than we first thought.

**Comment by johnfactotum** [comment] 2021-03-27 08:23
@anonimasusan That error looks like #689. It's been fixed with Foliate 2.6.

@Yugeniki In that case I'm going to close this now, as I cannot reproduce the issue. If anyone is still having problems, I suggest opening a new issue and posting the steps to reproduce and logs, if possible.

**Closed by johnfactotum** 2021-03-27 08:23 UTC
Labels: bug, need info
