### ISSUE TITLE
Save changes in preferences only upon confirmation

### ISSUE THREAD

**Issue by digitalethics** [johnfactotum/foliate#625] opened 2020-11-08 15:43 UTC
When using a mouse with a scroll wheel, I frequently find myself accidentally making changes through the mouse wheel that I didn't intend to make. For me, the most intuitive solution to this problem would be to simply add a _Save_ or _Confirm changes_ button in the preferences dialogue.

**Comment by johnfactotum** [comment] 2020-11-14 11:51
From the [HIG](https://developer.gnome.org/hig/stable/dialogs.html.en):
> Presentation dialogs are either instant or explicit apply. In instant apply dialogs, changes to settings or values are immediately updated. In contrast, explicit apply dialogs include a button for applying changes.
>
> Instant apply should be used wherever possible. [...]
>
> Explicit apply is only necessary if changes in the dialog have to be applied simultaneously in order to have the desired behaviour.

I think a better solution would be to use a different widget that does not change with mouse wheel. Some apps have already switched to a popover, which is more touch-friendly as well. Another way to alleviate this would be to reduce scrolling by putting preferences into different pages.

It's also arguably a bug—combo boxes should not grab scrolling when you're scrolling. I do remember this happening before. But now, testing on my machine, scrolling simply stops upon reaching the combo box, and further scrolling has no effect at all.

**Comment by johnfactotum** [comment] 2021-01-10 11:56
Closing as wontfix as there isn't a good reason to not follow the HIG.

**Closed by johnfactotum** 2021-01-10 11:56 UTC
Labels: enhancement

**Comment by gitkeerthi** [comment] 2022-05-27 06:56
Ateast provide "Reset to defaults"

**Comment by johnfactotum** [comment] 2022-05-27 10:00
As I said above, the problem is really a GTK bug. See https://gitlab.gnome.org/GNOME/gtk/-/issues/593
