### ISSUE TITLE
Can't open any ebook

### ISSUE THREAD

**Issue by padraa** [johnfactotum/foliate#880] opened 2022-03-27 13:10 UTC
I can't manage to open any ebook, I've tried local epub and mobi files. Downloaded some ebooks from Catalogs. It would either show the error "Empty Response" or be stuck on loading forever. This is the output of `foliate --verbose` which tries to open one of my local epub files:
```
foliate --verbose

(WebKitWebProcess:2): Gdk-WARNING **: 17:17:29.473: Failed to read portal settings: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.portal.Desktop was not provided by any .service files
Gjs-Message: 17:17:33.048: JS LOG: ready
Gjs-Message: 17:17:33.049: JS LOG: run_javascript: doubleClickTime =
                    400
Gjs-Message: 17:17:33.049: JS LOG: run_javascript: imgEventType = "click"
Gjs-Message: 17:17:33.049: JS LOG: run_javascript: windowSize = 640
Gjs-Message: 17:17:33.049: JS LOG: run_javascript: windowHeight = 633
Gjs-Message: 17:17:33.049: JS LOG: run_javascript: zoomLevel = 1
Gjs-Message: 17:17:33.049: JS LOG: run_javascript: enableFootnote = true
Gjs-Message: 17:17:33.049: JS LOG: run_javascript: autohideCursor = false
Gjs-Message: 17:17:33.049: JS LOG: run_javascript: open(
                    decodeURI("file:///home/padra/Documents/A%2520Brief%2520History%2520of%2520Time/Hawking,%2520Stephen%2520William%2520-%2520A%2520brief%2520history%2520of%2520time_%2520from%2...
Gjs-Message: 17:17:33.051: JS LOG: book-error

(com.github.johnfactotum.Foliate:4247): Gjs-WARNING **: 17:17:33.051: JS ERROR: Error: Empty Response
_init/<@resource:///com/github/johnfactotum/Foliate/js/epubView.js:623:57
_handleAction@resource:///com/github/johnfactotum/Foliate/js/epubView.js:886:22
_init/<@resource:///com/github/johnfactotum/Foliate/js/epubView.js:617:18
main@resource:///com/github/johnfactotum/Foliate/js/main.js:478:24
run@resource:///org/gnome/gjs/modules/script/package.js:206:19
@/sbin/foliate:9:17
```
I'm using version 2.6.4-1 on Arch.
I've even built foliate from the github repository manually but there was no difference.
If you need any info about my system or whatnot I'd be happy to provide them.

**Comment by jonathonf** [comment] 2022-03-27 13:38
Duplicate of https://github.com/johnfactotum/foliate/issues/878

**Closed** 2022-03-27 13:40 UTC
