### ISSUE TITLE
Arch LInux (Manjaro) not working

### ISSUE THREAD

**Issue by Pinche-Dev** [johnfactotum/foliate#788] opened 2021-09-25 12:31 UTC
** (com.github.johnfactotum.Foliate:25900): CRITICAL **: 18:15:20.574: g_irepository_find_by_name: assertion 'typelib != NULL' failed

** (com.github.johnfactotum.Foliate:25900): CRITICAL **: 18:15:20.574: g_irepository_find_by_name: assertion 'typelib != NULL' failed

** (com.github.johnfactotum.Foliate:25900): CRITICAL **: 18:15:20.574: g_irepository_find_by_name: assertion 'typelib != NULL' failed

** (com.github.johnfactotum.Foliate:25900): CRITICAL **: 18:15:20.574: g_irepository_find_by_name: assertion 'typelib != NULL' failed

** (com.github.johnfactotum.Foliate:25900): CRITICAL **: 18:15:20.574: g_irepository_find_by_name: assertion 'typelib != NULL' failed

** (com.github.johnfactotum.Foliate:25900): CRITICAL **: 18:15:20.574: g_irepository_find_by_name: assertion 'typelib != NULL' failed

** (com.github.johnfactotum.Foliate:25900): CRITICAL **: 18:15:20.575: g_irepository_find_by_name: assertion 'typelib != NULL' failed

** (com.github.johnfactotum.Foliate:25900): CRITICAL **: 18:15:20.575: g_irepository_find_by_name: assertion 'typelib != NULL' failed

** (com.github.johnfactotum.Foliate:25900): CRITICAL **: 18:15:20.575: g_irepository_find_by_name: assertion 'typelib != NULL' failed

** (com.github.johnfactotum.Foliate:25900): CRITICAL **: 18:15:20.575: g_irepository_find_by_name: assertion 'typelib != NULL' failed

** (com.github.johnfactotum.Foliate:25900): CRITICAL **: 18:15:20.575: g_irepository_find_by_name: assertion 'typelib != NULL' failed

** (com.github.johnfactotum.Foliate:25900): CRITICAL **: 18:15:20.575: g_irepository_find_by_name: assertion 'typelib != NULL' failed

(com.github.johnfactotum.Foliate:25900): GLib-GObject-WARNING **: 18:15:20.575: cannot register existing type 'TrackerSparqlConnection'

(com.github.johnfactotum.Foliate:25900): GLib-CRITICAL **: 18:15:20.575: g_once_init_leave: assertion 'result != 0' failed

(com.github.johnfactotum.Foliate:25900): GLib-GObject-CRITICAL **: 18:15:20.575: g_type_register_static: assertion 'parent_type > 0' failed

(com.github.johnfactotum.Foliate:25900): GLib-GObject-WARNING **: 18:15:20.575: cannot add private field to invalid (non-instantiatable) type '<invalid>'

(com.github.johnfactotum.Foliate:25900): GLib-CRITICAL **: 18:15:20.575: g_once_init_leave: assertion 'result != 0' failed

(com.github.johnfactotum.Foliate:25900): GLib-GObject-CRITICAL **: 18:15:20.575: g_object_new_with_properties: assertion 'G_TYPE_IS_OBJECT (object_type)' failed

(com.github.johnfactotum.Foliate:25900): Tracker-CRITICAL **: 18:15:20.575: tracker_sparql_backend_load_plugins: assertion 'self != NULL' failed
zsh: segmentation fault (core dumped)  com.github.johnfactotum.Foliate

**Comment by Pinche-Dev** [comment] 2021-09-25 12:32
used to work fine but doesnot work now,
Things that I tried:::
1. reinstall the OS
2. install using aur/foliate-git
3. install from source 
4. install from snapd.
5. install from flatapk

**Comment by kaiwizz** [comment] 2021-09-26 14:00
I am having the exact same issue in manjaro. My error message is exactly like yours I guess.

```
** (com.github.johnfactotum.Foliate:16770): CRITICAL **: 08:56:02.377: g_irepository_find_by_name: assertion 'typelib != NULL' failed

** (com.github.johnfactotum.Foliate:16770): CRITICAL **: 08:56:02.377: g_irepository_find_by_name: assertion 'typelib != NULL' failed

** (com.github.johnfactotum.Foliate:16770): CRITICAL **: 08:56:02.377: g_irepository_find_by_name: assertion 'typelib != NULL' failed

** (com.github.johnfactotum.Foliate:16770): CRITICAL **: 08:56:02.377: g_irepository_find_by_name: assertion 'typelib != NULL' failed

** (com.github.johnfactotum.Foliate:16770): CRITICAL **: 08:56:02.378: g_irepository_find_by_name: assertion 'typelib != NULL' failed

** (com.github.johnfactotum.Foliate:16770): CRITICAL **: 08:56:02.378: g_irepository_find_by_name: assertion 'typelib != NULL' failed

** (com.github.johnfactotum.Foliate:16770): CRITICAL **: 08:56:02.378: g_irepository_find_by_name: assertion 'typelib != NULL' failed

** (com.github.johnfactotum.Foliate:16770): CRITICAL **: 08:56:02.378: g_irepository_find_by_name: assertion 'typelib != NULL' failed

** (com.github.johnfactotum.Foliate:16770): CRITICAL **: 08:56:02.378: g_irepository_find_by_name: assertion 'typelib != NULL' failed

** (com.github.johnfactotum.Foliate:16770): CRITICAL **: 08:56:02.378: g_irepository_find_by_name: assertion 'typelib != NULL' failed

** (com.github.johnfactotum.Foliate:16770): CRITICAL **: 08:56:02.378: g_irepository_find_by_name: assertion 'typelib != NULL' failed

** (com.github.johnfactotum.Foliate:16770): CRITICAL **: 08:56:02.378: g_irepository_find_by_name: assertion 'typelib != NULL' failed

(com.github.johnfactotum.Foliate:16770): GLib-GObject-WARNING **: 08:56:02.378: cannot register existing type 'TrackerSparqlConnection'

(com.github.johnfactotum.Foliate:16770): GLib-CRITICAL **: 08:56:02.378: g_once_init_leave: assertion 'result != 0' failed

(com.github.johnfactotum.Foliate:16770): GLib-GObject-CRITICAL **: 08:56:02.378: g_type_register_static: assertion 'parent_type > 0' failed

(com.github.johnfactotum.Foliate:16770): GLib-GObject-WARNING **: 08:56:02.378: cannot add private field to invalid (non-instantiatable) type '<invalid>'

(com.github.johnfactotum.Foliate:16770): GLib-CRITICAL **: 08:56:02.378: g_once_init_leave: assertion 'result != 0' failed

(com.github.johnfactotum.Foliate:16770): GLib-GObject-CRITICAL **: 08:56:02.378: g_object_new_with_properties: assertion 'G_TYPE_IS_OBJECT (object_type)' failed

(com.github.johnfactotum.Foliate:16770): Tracker-CRITICAL **: 08:56:02.378: tracker_sparql_backend_load_plugins: assertion 'self != NULL' failed
```

I do not know if this is a manjaro issue or foliate.

**Comment by icepie** [comment] 2021-09-27 19:55
archlinux get the same error

**Comment by lompabo** [comment] 2021-09-28 06:20
Same issue here, I'm also on Manjaro

**Comment by kleinHeiti** [comment] 2021-09-28 09:19
Same here: Manjaro (Stable)

**Comment by johnfactotum** [comment] 2021-09-28 10:17
Duplicate of #785

**Closed by johnfactotum** 2021-09-28 10:17 UTC
Labels: bug
