### ISSUE TITLE
Double page view loads only partial text

### ISSUE THREAD

**Issue by r-0-0-t** [johnfactotum/foliate#23] opened 2019-06-01 12:22 UTC
So I increased the font size to 16 and started to read a book in double view.
But it only loads only showable amount of texts and remaining texts doesn't show up, nor in the next page.
But I can read the full page in scroll mode!

**To Reproduce:**
download epub from archive.com website [The Quran Epub](https://archive.org/details/qxpvi-english/page/n0)

**Some Screenshots of the bug:**

![Only partial loaded in double page](https://user-images.githubusercontent.com/41895860/58748359-691ece00-8499-11e9-8357-2a16006c894e.png)

![The Settings](https://user-images.githubusercontent.com/41895860/58748403-011cb780-849a-11e9-9914-e201637002ae.png)

**And in the single page:**

![The page gets loaded and scrollable with mouse only](https://user-images.githubusercontent.com/41895860/58748374-979ca900-8499-11e9-8df5-db6eb8f993c3.png)

**Comment by johnfactotum** [comment] 2019-06-01 14:01
I can somewhat reproduce some weirdness for this book. However, this seems to be an Epub.js bug.

**Comment by johnfactotum** [comment] 2019-07-04 01:10
Closing as there's nothing to be done in Foliate. I suggest that you open the issue with [Epub.js](https://github.com/futurepress/epub.js). See https://github.com/johnfactotum/foliate/issues/32#issuecomment-498084804 for how to reproduce this in Epub.js itself.

**Closed by johnfactotum** 2019-07-04 01:10 UTC
Labels: epub.js, not our bug
