### ISSUE TITLE
Disable/hide popups

### ISSUE THREAD

**Issue by CipherCloak** [johnfactotum/foliate#1286] opened 2024-03-30 16:11 UTC
**Question:**
A would like to know how to **disable/hide** the `popup` described in the following images.

**Version:**
 - Foliate version: 3.1.0
 - OS/Distribution and version: Linux Mint 21.3
 - Desktop environment: Cinnamon 5.2
 - Installation method: Flatpak

![image](https://github.com/johnfactotum/foliate/assets/3332674/e846ff02-81b5-418d-bb8f-d2f9d805d0cd)
![image](https://github.com/johnfactotum/foliate/assets/3332674/3141c433-b296-4342-b68a-4fae53485afa)

Thanks in advance!!!

**Comment by johnfactotum** [comment] 2024-03-31 03:56
Duplicate of #196.

**Closed as not planned by johnfactotum** 2024-03-31 03:56 UTC
Labels: duplicate, question

**Comment by CipherCloak** [comment] 2024-04-01 01:17
>Duplicate of #196.

Hey @johnfactotum , thank you for taking the time to read my OP.

Could you please guide me in the right direction as to which method/function/code is responsible for displaying the mentioned tooltip?

Thanks in advance!

**Comment by johnfactotum** [comment] 2024-04-02 03:48
It's part of the book. See https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/title.
