### ISSUE TITLE
Multi-Page empty space in Standard Ebook titles.

### ISSUE THREAD

**Issue by rhynec** [johnfactotum/foliate#941] opened 2022-09-14 17:59 UTC
**Describe the bug**
For some reason, Foliate displays multiple empty pages in between the Titlepage and Imprint of Standard Ebook titles, in all available ebook formats.

**To Reproduce**
1. Open any SE epub with Foliate (for example, [this](https://standardebooks.org/ebooks/susanna-haswell-rowson/charlotte-temple) one).
2. Starting at the Titlepage, naviagate through the ebook's pages using the arrow keys.
3. Change pages (press forward on your arrow keys) about 10-24 times (depending on your Foliate window size).
4. Arrive at the Imprint after all those key presses.

Note: Also works when changing pages with mouse clicks, but is much more tedious since clicks need to be spaced out.

**Expected behavior**
Arrive at the Imprint from the Titlepage in a single click/key-press. This works properly in all other ebook app/readers I've tested (though, not exhaustively).

**Version:**
 - Foliate version: 2.6.4
 - OS/Distribution and version: Fedora 36
 - Desktop environment: Gnome 42
 - Installation method: Native rpm from Fedora repos.

**Comment by johnfactotum** [comment] 2022-09-15 10:37
So apparently they changed the titlepage and added invisible elements with font size set to zero, and it does work. The problem is that Foliate tries to force the user's preferred font size on all `p` elements. So the font size of the `p` in the titlepage is no longer zero.

The best solution would probably be to stop forcing font size on `p`, which already breaks too many books, anyway. At least we should probably try to lower the specificity.

And maybe this could be fixed in Epub.js as well, because I think it's using the width returned by `.getBoundingClientRect()`. Perhaps the bug could be fixed if one could account for negative overflows when calculating the width.

**Comment by johnfactotum** [comment] 2023-03-07 13:39
This is fixed in the gtk4 branch, as it doesn't force font size anymore.

**Closed by johnfactotum** 2023-03-07 13:39 UTC
Labels: bug
