### ISSUE TITLE
Page number issues with specific book, sometimes crashes

### ISSUE THREAD

**Issue by fire-eggs** [johnfactotum/foliate#586] opened 2020-09-04 16:08 UTC
**Describe the bug**
Paging forward through the attached book. There are several places where there are significant pauses when changing pages. At those locations, going back shows a very different page number. Going back again corrects the page number.

**To Reproduce**
1. Open the attached book in Foliate.
2. Insure that Foliate is in double-page mode.
3. Page forward to page 177.
4. Page forward again. There is a visible pause, then page 178 is displayed.
5. Page backward. Again a pause. Foliate displays page 147.
6 Page backward again. Foliate displays page 175.

Going forward / backward around one of these "pauses" may cause Foliate to crash. See terminal messages below.

Additional problem points at pages 375, 564, and 695.

**Expected behavior**
Page numbers remain consistent. Foliate does not crash.

**Screenshots**
N/A

**Version:**
 - Foliate version: 2.4.2
 - OS/Distribution and version: Linux Mint 20
 - Desktop environment: Cinnamon 4.6.6
 - Installation method: Flatpak

**Additional context**

The following messages/crashes have been observed in terminal, inconsistently.
```
(com.github.johnfactotum.Foliate:2): Gjs-WARNING **: 11:54:15.813: Unhandled promise rejection. To suppress this warning, add an error handler to your promise chain with .catch() or a try-catch block around your await expression. Stack trace of the failed promise:
  main@resource:///com/github/johnfactotum/Foliate/js/main.js:474:24
  run@resource:///org/gnome/gjs/modules/script/package.js:222:19
  @/app/bin/com.github.johnfactotum.Foliate:9:17
```

```
(com.github.johnfactotum.Foliate:2): Gjs-ERROR **: 11:39:48.442: toggling down object GInotifyFileMonitor that's already queued to toggle up
```
Problem file (zipped 'cause Github insists)
[Masters of Fantasy - Bill Fawcett.zip](https://github.com/johnfactotum/foliate/files/5175845/Masters.of.Fantasy.-.Bill.Fawcett.zip)

**Comment by fire-eggs** [comment] 2020-09-04 16:23
Examining the contents of the ebook, the "pause"s I mention occur at the transition between the physical HTML files in the epub file.

**Comment by johnfactotum** [comment] 2020-09-05 10:51
The pause is just it loading and rendering the pages, which can take a long time if the HTML page is long because Epub.js uses CSS columns to paginate the text, and this method is slow, particularly on WebKit.

The crash is a GJS bug (see #357). It's more susceptible to crashing when turning the page because that's when it writes to a monitored JSON file to update the reading progress.

**Comment by johnfactotum** [comment] 2021-06-30 04:37
Duplicate of #357

**Closed by johnfactotum** 2021-06-30 04:37 UTC
Labels: bug
