### ISSUE TITLE
Remember to translate language. Not only in English

### ISSUE THREAD

**Issue by marcimix** [johnfactotum/foliate#1224] opened 2024-01-15 10:54 UTC
**Is your feature request related to a problem? Please describe.**
App won't save for used language. It's always English on my system during the remember choose.

**Describe the solution you'd like**
To save used language before

**Describe alternatives you've considered**
It can be pasted to google translate by web browser directly or make definition word in English.

**Comment by johnfactotum** [comment] 2024-01-15 16:33
Duplicate of #1159

**Closed as not planned by johnfactotum** 2024-01-15 16:33 UTC
Labels: duplicate, enhancement
