### ISSUE TITLE
Using libsoup2 and libsoup3 in the same process is not supported

### ISSUE THREAD

**Issue by hubutui** [johnfactotum/foliate#844] opened 2022-01-04 06:01 UTC
**Describe the bug**
Fail to start foliate due to libsoup2 and libsoup3 are both installed in the system. `/usr/bin/com.github.johnfactotum.Foliate` outputs:
```text
Gjs-Message: 13:57:18.284: JS WARNING: [resource:///com/github/johnfactotum/Foliate/js/main.js 23]: Requiring WebKit2 but it has 2 versions available; use imports.gi.versions to pick one

(com.github.johnfactotum.Foliate:435826): libsoup-ERROR **: 13:57:18.391: libsoup3 symbols detected. Using libsoup2 and libsoup3 in the same process is not supported.
[1]    435826 trace trap (core dumped)  /usr/bin/com.github.johnfactotum.Foliate

```

**Version:**
 - Foliate version: 2.6.3
 - OS/Distribution and version: ArchLinux
 - Desktop environment: GNOME 41.2
 - Installation method: `pacman -S foliate`

**Additional context**
see also ArchLinux bug report [here](https://bugs.archlinux.org/task/72947?project=5&string=foliate).

**Comment by fabiscafe** [comment] 2022-01-04 08:21
Duplicate of #812, #816
Fixed in #808 - https://github.com/johnfactotum/foliate/commit/8c00d67d57241bce965043fb98ba76782989eee5

**Closed** 2022-01-05 07:29 UTC
Labels: bug, duplicate
