### ISSUE TITLE
Interface becomes unusable if 'Power Saver' power profile is active.

### ISSUE THREAD

**Issue by tomicakorac** [johnfactotum/foliate#969] opened 2022-10-27 02:20 UTC
**Describe the bug**
GNOME version 41 has introduced the Power Profiles feature. One of its presets, 'Power Saver' specifically, causes a number of operation critical issues with Foliate's graphical interface. More information is available in #879.

**Workaround**
Before running Foliate, select any Power Profile other than 'Power Saver', for example 'Balanced' or 'Performance'.

**Steps to reproduce**
1. Activate 'Power Saver' Power Profile (can be done in multiple ways, for example Ubuntu Settings > Power > Power Profile > Power Saver)
2. Run Foliate and load any .epub file (only .epub is tested, possibly the bug exists for other formats too)

**Expected behavior**
Foliate should load the file, display its content, and accept navigation through the loaded file by clicking on respective gui elements and using mouse & keyboard shortcuts/commands.

**What happens instead**
- The file is stuck in endless loading until focus is switched away from Foliate and back to it again
- GUI navigation elements (mostly) do not accept clicks, with few exceptions; This is most noticeable when quickly clicking many times on one of the buttons.
- Keyboard & mouse shortcuts/commands do not work

**Version:**
 - Foliate version: 2.6.3, 2.6.4
 - OS/Distribution and version: Ubuntu 22.04 and later
 - Desktop environment: GNOME 41 and later
 - Installation method: PPA, Flatpak

**Additional context**
This bug was first reported in #879 but it took some time to track down the actual causes. The original thread is now closed because it contains a number of outdated and potentially harmful assumptions, and to allow for better prioritisation of debugging.

Since there is an easy workaround, there is no urgency to fix this bug. Also, because GNOME's Power Profile feature is not well documented (we don't know what exactly the "Power Saver" preset does), it is at this time difficult to debug it. For these two reasons, this bug should have a relatively low priority in fixing.

**Comment by tomicakorac** [comment] 2022-11-07 18:05
Potentially relevant information was added to another topic [here](https://gitlab.freedesktop.org/hadess/power-profiles-daemon/-/issues/113#note_1619455).

**Comment by tomicakorac** [comment] 2022-11-18 08:23
My computer has just received an upgrade of several libraries, among which an upgrade for Webkit2GTK from 2.38.0 to 2.38.2. After this upgraede, this issue seems to have been resolved. Can anyone else please test and confirm this?

**Comment by Tuba2** [comment] 2022-11-23 02:30
I'm having the same problem. Almost gave up on the app before finding this issue, since I had no idea of what was the problem. Glad I didn't, since the app is great. Thanks for finding and reporting!

And I believe it is indeed a low priority bug, but also something that will improve the user experience a lot, since Power Saving mode is great for this app's use case: reading books on your computer.

**Comment by emes81** [comment] 2023-01-12 14:10
Thanks for everyone's efforts identifying this. Would an in-app notification be feasible to alert users to this issue until it is resolved? Foliate is particularly likely to be used by non-technical users who are less likely to be able to find the workaround here.

**Comment by Tuba2** [comment] 2023-01-12 17:49
Sounds great. The Gtk-banner widget seems the most appropriate way to give this alert, appearing only when Power Saving mode is on. A button to disable Power Saving mode can be made available and be pressed directly from the banner.

**Comment by wimdows** [comment] 2023-04-23 20:43
I have the exact same problem on a Librem5 running PureOS. The L5 does not have a Power Saver mode.

**Comment by iiiian** [comment] 2023-05-22 02:56
After reading the source code of power profile daemon, I find that by default it use [platform profile](https://www.kernel.org/doc/html/latest/userspace-api/sysfs-platform_profile.html). I believe that means power saving is implemented by firmware.

**Comment by tomicakorac** [comment] 2023-05-22 04:56
@iiiian thanks for replying. To be honest, I fail to see the relevance of your comment to the topic. Can you please elaborate further? How does the knowledge you shared contribute to resolving this issue?

**Comment by johnfactotum** [comment] 2023-07-29 04:59
Tried the gtk4 branch. Unlike previous versions, it can open and render books normally for the most part.

The only thing that's broken now seems to be the new sliding animation (see #188 and #862). This occurs in Epiphany as well. Upon closer examination, it appears that `requestAnimationFrame()` is broken in WebKitGTK when power saver mode is active.

**Comment by tomicakorac** [comment] 2023-10-17 07:30
This issue seems to be gone now. Here's what I know:

- All morning I've been opening numerous .epub files in Foliate with Power 
Profile set to "Power Saver", everything seems to be working as expected;
- The issue was still present 2 weeks at latest when I last checked it; 
Some update may have happened that helped.

Can anyone else please try on their end to confirm, or deny me? I'm 
reminding of steps to reproduce:


 > - Activate 'Power Saver' Power Profile (can be done in multiple ways, 
for example Ubuntu Settings > Power > Power Profile > Power Saver)
 > - Run Foliate and load any .epub file (only .epub is tested, possibly 
the bug exists for other formats too)

**Comment by jistr** [comment] 2023-10-17 09:02
I can confirm this seems fixed now on Fedora Silverblue 38.20231015.0 and flatpaks (Foliate + runtime) updated to latest.

**Comment by emes81** [comment] 2023-10-17 10:24
Fixed on Arch updated to latest

**Closed** 2023-11-12 17:48 UTC
Labels: bug
