### ISSUE TITLE
GJS Error Preventing Foliate From Starting

### ISSUE THREAD

**Issue by moriel5** [johnfactotum/foliate#603] opened 2020-10-05 02:41 UTC
There are no issues compiling Foliate here on Solus (aside from LibHandy not being available, however I maintain an unofficial package for that).

Unfortunately, when attempting to open it, nothing happens.
When doing so via the terminal, I get the following error:

> Gjs-Message: 05:26:32.306: JS WARNING: [resource:///com/github/johnfactotum/Foliate/js/handy.js 68]: reference to undefined property "Column"
>
>(com.github.johnfactotum.Foliate:8741): Gjs-WARNING **: 05:26:32.306: JS ERROR: TypeError: class heritage Handy.Column is not an object or null
@resource:///com/github/johnfactotum/Foliate/js/handy.js:68:7
@resource:///com/github/johnfactotum/Foliate/js/opds.js:25:23
@resource:///com/github/johnfactotum/Foliate/js/library.js:28:63
@resource:///com/github/johnfactotum/Foliate/js/main.js:44:27
@/usr/bin/com.github.johnfactotum.Foliate:9:1
>
>
>(com.github.johnfactotum.Foliate:8741): Gjs-CRITICAL **: 05:26:32.306: Script /usr/bin/com.github.johnfactotum.Foliate threw an exception

This happens, both on version 2.4.2, and on the latest master.

This is not my first time compiling Foliate, so this is quite strange, since it runs fine on my desktop install (currently I'm running from my laptop's HDD, on my desktop, since I need to microsolder the battery cable holder back), which I had compiled back when LibHandy was at a version around 0.8 (I had recently updated my package to 1.0), although this should not have anything to do with the issue at hand.

**Version:**
 - Foliate version: 2.4.2 + Latest Master
 - OS/Distribution and version: Solus 4.1 Fortitude
 - Desktop environment: Budgie 10.5.1 (with GNOME Stack 3.36.5)
 - Installation method: Compiled via Meson/Ninja

**Comment by Kandelai** [comment] 2020-10-06 06:32
Same issue happening version 2.4.2-1
OS/Distribution: EndeavourOS/Arch
DE: KDE 5.19.5

> [rodney@rodney-mainpc ~]$ com.github.johnfactotum.Foliate %U
> 
> (com.github.johnfactotum.Foliate:122788): Gjs-CRITICAL **: 23:26:15.348: JS ERROR: TypeError: class heritage Handy.Column is not an object or null
> @resource:///com/github/johnfactotum/Foliate/js/handy.js:68:7
> @resource:///com/github/johnfactotum/Foliate/js/opds.js:25:23
> @resource:///com/github/johnfactotum/Foliate/js/library.js:28:63
> @resource:///com/github/johnfactotum/Foliate/js/main.js:44:27
> @/usr/bin/com.github.johnfactotum.Foliate:9:1
> 
> 
> (com.github.johnfactotum.Foliate:122788): Gjs-CRITICAL **: 23:26:15.348: Script /usr/bin/com.github.johnfactotum.Foliate threw an exception
> [rodney@rodney-mainpc ~]$ 
>

**Comment by johnfactotum** [comment] 2020-10-07 15:39
This is caused by #548 and should be fixed with ab9592b973d76d85cc228635045f4b3e875f5147. 

For anyone using versions prior to this fix, the workaround is to install a version of libhandy < 0.82.0 (on Arch Linux there's `libhandy0`).

**Closed by johnfactotum** 2020-10-07 15:39 UTC
Labels: bug
