### ISSUE TITLE
Screen Tearing

### ISSUE THREAD

**Issue by aadilayub** [johnfactotum/foliate#49] opened 2019-06-06 07:41 UTC
I often experience screen tearing when maximizing or flipping pages in Foliate. I haven't experienced this behavior on any other apps on my system (Fedora 30). 

Here is a screencast of the behavior (apologies for the low resolution):

![foliatebug](https://user-images.githubusercontent.com/31581044/59015395-50773500-8858-11e9-9961-4498d7f0812b.gif)

**Comment by johnfactotum** [comment] 2019-06-06 10:45
I can't really reproduce. In any case I think this is probably a GTK or WebKit or Flatpak bug, as Foliate is simply GTK plus a WebKit WebView, and doesn't do anything special to draw anything or anything like that.

**Comment by Vistaus** [comment] 2019-06-07 11:00
> I can't really reproduce. In any case I think this is probably a GTK or WebKit or Flatpak bug, as Foliate is simply GTK plus a WebKit WebView, and doesn't do anything special to draw anything or anything like that.

Or a Mutter on Wayland issue as Fedora 30 uses Wayland by default.

**Comment by johnfactotum** [comment] 2019-06-08 04:21
Yes, that too. On Wayland sometimes something like this happens:

![Screenshot from 2019-06-08 12-17-34](https://user-images.githubusercontent.com/50942278/59141897-790c4580-89a4-11e9-89f1-b90782acd9df.png)

Don't know if is this is related.

**Comment by johnfactotum** [comment] 2019-07-05 05:32
I will close this for now because 1) I can't reproduce and 2) most likely not our bug.

**Closed by johnfactotum** 2019-07-05 05:32 UTC
