### ISSUE TITLE
Crashes when open epub book Ubuntu 24.04

### ISSUE THREAD

**Issue by auspham** [johnfactotum/foliate#1397] opened 2024-09-12 13:57 UTC
**Describe the bug**
Crashes when trying to open an epub book 

**To Reproduce**
1. Click open on the main screen
2. Click on an epub file
3. Crash

**Expected behavior**
Should open the epub for reading

**Version:**
 - Foliate version:  3.1.1
 - OS/Distribution and version: [e.g. Ubuntu 18.04] Ubuntu 24.04.1 LTS"
 - Desktop environment: [e.g. GNOME 3.36]  GNOME 46.0 
 - Installation method: [e.g. Flatpak] Github release download link

**Additional context**
Crash logs:

```
❯ foliate
bwrap: setting up uid map: Permission denied

** (com.github.johnfactotum.Foliate:24820): ERROR **: 23:53:09.979: Failed to fully launch dbus-proxy: Child process exited with code 1
[1]    24820 trace trap (core dumped)  foliate
```

# Work around:

Related bugs can be found here: https://etbe.coker.com.au/2024/04/24/ubuntu-24-04-bubblewrap/

Work around is to create a file in `/etc/apparmor.d/bwrap` with following content:

```
abi <abi/4.0>,
include <tunables/global>

profile bwrap /usr/bin/bwrap flags=(unconfined) {
  userns,

  # Site-specific additions and overrides. See local/README for details.
  include if exists <local/bwrap>
}
```

And then do a `systemctl reload apparmor`

**Comment by johnfactotum** [comment] 2024-09-13 01:10
Duplicate of #1262

**Closed as not planned** 2024-09-14 15:23 UTC
Labels: bug, duplicate
