### ISSUE TITLE
The font menu is not fully translated

### ISSUE THREAD

**Issue by schw0reismus** [johnfactotum/foliate#40] opened 2019-06-04 13:01 UTC
![изображение](https://user-images.githubusercontent.com/51238434/58880946-c5742e80-86e1-11e9-9a00-d2a69829d9e6.png)

**Comment by johnfactotum** [comment] 2019-06-04 17:01
This is not the only place where gettext fails to extract the strings. I believe this is caused by https://savannah.gnu.org/bugs/?50920. It says the fix is contained in gettext-0.20, but I don't that version at the moment so I haven't tested yet.

**Comment by shibotto** [comment] 2019-06-07 12:28
Actually it seems even worse with gettext-0.20.1.
Used `ninja com.github.johnfactotum.Foliate-pot` and diffed with 1fe9263f, to keep the output "short":
![immagine](https://user-images.githubusercontent.com/3816409/59103717-ef229500-892f-11e9-94f6-495038841a5c.png)

**Comment by johnfactotum** [comment] 2019-06-08 07:07
Basically, xgettext seems to go wrong whenever there's a slash inside backticks. My guess is that while they've added support for template strings, the problem with slash in backticks wasn't fixed so it actually made things worse.

I've added a workaround in a37760f745992376ab3d10e80bf9e55de2829ad3, and it works in gettext 0.19.8.1.

**Comment by johnfactotum** [comment] 2019-07-03 07:15
Closing as the workaround works for now. Should probably report the issue upstream.

**Closed by johnfactotum** 2019-07-03 07:15 UTC
