### ISSUE TITLE
Can not add book to Foliate

### ISSUE THREAD

**Issue by buffalospirits** [johnfactotum/foliate#815] opened 2021-11-27 02:56 UTC
**Describe the bug**
When I click on the add book (+) button nothing happens. No file window opens. Nada. Nothing. Same with going to the menu icon and clicking on 'add books'.

**Expected behavior**
A file window should open so I can click to the folder where my ebook files are.

**Version:**
 - Foliate version: 2.6.3
 - OS/Distribution and version: Xubuntu 20.04.3 LTS
 - Desktop environment: Xfce
 - Installation method: snap (I think)

**Additional context**
ALL links that should open a window for adding books do not work. ALL the links concerning actions pertaining to the Catalogs DO work.

/home/(my home folder)/snap/foliate/1167/.local/share/com.github.johnfactotum.Foliate/books
In Preferences, this ^^ is the default directory shown to save to.

No 'error' message appears, the 'add book' functionality simply does not open a window to get to my ebook files. Everything else seems to work ok.

EDIT..........I can go the folder containing my ebook and click to open with Foliate. The book will open in Foliate and it will appear in the Foliate Library.

**Comment by johnfactotum** [comment] 2021-11-27 18:56
Probably a duplicate of #725. Try installing `xdg-desktop-portal-gtk`.

**Closed** 2023-02-03 05:51 UTC
Labels: bug, duplicate, snap
