### ISSUE TITLE
Shortcuts are limited. Need more customizable keyboard shortcuts

### ISSUE THREAD

**Issue by idea-log** [johnfactotum/foliate#755] opened 2021-07-03 11:00 UTC
Hello there. Thanks for this nice application for viewing e-books but I think that there are some keyboard shortcut customization missing. For example, I would like to be able to highlight a word quickly without any mouse clicks, say for example with CTRL + H
Thanks!

**Comment by johnfactotum** [comment] 2021-07-04 10:22
Duplicate of #305 ?

**Closed** 2021-07-07 14:43 UTC
Labels: duplicate, enhancement
