### ISSUE TITLE
Foliate Bug in Arch Linux ...

### ISSUE THREAD

**Issue by Tomoghno** [johnfactotum/foliate#828] opened 2021-12-14 15:49 UTC
Gjs-Message: 21:16:24.869: JS WARNING: [resource:///com/github/johnfactotum/Foliate/js/main.js 23]: Requiring WebKit2 but it has 2 versions available; use imports.gi.versions to pick one

(com.github.johnfactotum.Foliate:6403): libsoup-ERROR **: 21:16:25.018: libsoup3 symbols detected. Using libsoup2 and libsoup3 in the same process is not supported.
[1]    6403 trace trap (core dumped)  foliate

**Comment by johnfactotum** [comment] 2021-12-14 15:51
Duplicate of #808, #812

**Closed by johnfactotum** 2021-12-14 15:51 UTC
Labels: bug
