### ISSUE TITLE
PDF content rendered fuzzy 

### ISSUE THREAD

**Issue by hxzhao527** [johnfactotum/foliate#1282] opened 2024-03-26 12:24 UTC
**Describe the bug**
Is seems the text in a PDF file rendered with a mask, too fuzzy.

**To Reproduce**
Just open a pdf file

**Expected behavior**
![image](https://github.com/johnfactotum/foliate/assets/8402502/a507aefb-aace-495a-8d4d-fdd1c005b69a)

**Screenshots**
![image](https://github.com/johnfactotum/foliate/assets/8402502/81c8cc0d-ffd7-40ab-af68-be424a9d5d18)

**Version:**
 - Foliate version: `3.1.0`
 - OS/Distribution and version: Manjaro 23.1.3 Vulcan
 - Desktop environment: Xfce4
 - Installation method: pacman (the system package manager)

![image](https://github.com/johnfactotum/foliate/assets/8402502/66b44091-259d-45ad-a9a8-fbb78a783f92)

**Comment by beesflower** [comment] 2024-03-26 15:01
I had also got this problem on ubuntu 22.04.

**Comment by johnfactotum** [comment] 2024-03-26 21:55
Duplicate of #1129

**Closed as not planned** 2024-03-28 05:58 UTC
Labels: bug, duplicate
