### ISSUE TITLE
Inside a book, `Ctrl+F` search keyboard shortcut does not work if the book pages are focused instead of the sidebar

### ISSUE THREAD

**Issue by nekohayo** [johnfactotum/foliate#1299] opened 2024-04-12 03:35 UTC
**To Reproduce**
1. Enter a book
2. Click on the Search button
3. Press `Esc` to toggle off the search
4. Press `Ctrl+F`, notice the searchbar reappears
5. Press `Esc` to toggle off the search
6. Click the book's page contents on the right, so that the focus is no longer on the sidebar (even if the sidebar is pinned)
7. Press `Ctrl+F` to try to activate and focus (and select-all) the searchentry's contents

**Expected behavior**
Search entry gets reactivated, and existing query text (if any) should be all preselected (so that the user can replace/overwrite it, or choose to extend it instead)

**Version:**
 - Foliate version: 3.1.0
 - OS/Distribution and version: Fedora 39
 - Desktop environment: GNOME 45
 - Installation method: RPM

**Additional context**
Running in Wayland.

**Comment by johnfactotum** [comment] 2024-04-12 11:33
See https://github.com/johnfactotum/foliate/issues/1279#issuecomment-2017195341

> * OS/Distribution and version: Fedora 39
> 
> * Desktop environment: GNOME 45

Guess that means it was caused by a change in how WebKitGTK handles shortcuts.

At any rate, this should be fixed in v3.1.1.

**Closed as completed** 2024-04-15 03:58 UTC
Labels: bug
