### ISSUE TITLE
Freezes on tranation menu

### ISSUE THREAD

**Issue by ColorfulCode728** [johnfactotum/foliate#1367] opened 2024-07-28 16:36 UTC
**Describe the bug**
Foliate becomes and stuck when translating into language other than english.

**To Reproduce**
1. Select a word
2. Select "Translate" option from pop up.
3. Select "Bangla" from drop down menu.
4. Foliate then and stays on the translate menu even when i click on other place.

**Expected behavior**
It shouldn't be stuck on the menu. The translation menu should disappear when clicked outside of it just like dictionary and wikipedia menu. But it disappears when i click outside of the app area (e.g. Foliate app icon on dock, the gnome top bar).

**Version:**
 - Foliate version: 3.1.1
 - OS/Distribution and version: Ubuntu 24.04
 - Desktop environment: GNOME 46
 - Installation method: deb/apt

**Comment by johnfactotum** [comment] 2024-08-07 18:04
Duplicate of #1270

**Closed as not planned by johnfactotum** 2024-08-07 18:04 UTC
Labels: bug

**Comment by LiviusTrivius** [comment] 2024-11-22 10:11
**Describe the bug**
After double clicking on word in epub text and choosing 'translate', then choosing another language (no English) the translation appears correctly. But clicking outside the popup or outside Foliate window does not make the popup  disappear. Only calling the language popup WITHOUT selecting a language, and then click outside the popup makes the popup disappear. 

**To Reproduce**
Steps to reproduce the behavior (as described by Ovi329):

    Select a word. 
    Double click word.
    Select "Translate" option from pop up.
    Select "Dutch" from drop down menu.
    Click outside popup OR click outside Foliate window: popup does not disappear.
    Even after selecting English again from the popup the popup will not disappear.

**Steps to reproduce the behavior to make the popup window disappear:**

    Select a word. 
    Double click word.
    Select "Translate" option from pop up.
    Select "Dutch" from drop down menu.
    Translation shows up.
    Call pulldown menu (make NO selection)
    While pulldown is open, click outside popup
    popup disappears
   
**Expected behavior (confirms Ovi329)**

The translation menu should disappear when clicked outside of it just like dictionary and wikipedia menu, irrespective of the language chosen. 

I cannot confirm Ovi329's next remark: "But it disappears when i click outside of the app area (e.g. Foliate app icon on dock, the gnome top bar)." In my case the popup does NOT disappear when clicking on the Foliate icon in panel. Foliate hides, but the popup stays. 

**Version & Environment:**

    Foliate version: 3.1.1
    OS/Distribution and version: Linux Mint 22
    Desktop environment: Cinnamon 6.2.9
    Installation method: deb/apt
