### ISSUE TITLE
Font color does not change with themes

### ISSUE THREAD

**Issue by cmhobbs** [johnfactotum/foliate#928] opened 2022-08-09 21:09 UTC
**Describe the bug**
On Pop!_OS 22.04 with Foliate installed via Flatpak, when I open a book and change the theme, the font color stays the same.  This is especially apparent when attempting to use a dark theme.

**To Reproduce**
1. Open a book
2. Click on the hamburger menu
3. Select the 'Theme' submenu
4. Choose any theme
5. The background color changes but the font remains the same

**Expected behavior**
The font color should change with the theme's color.

**Screenshots**
Example of a dark theme change.

![image](https://user-images.githubusercontent.com/26329/183761414-8ccd9381-1d20-468d-af6e-9361f996f167.png)

**Version:**
 - Foliate version: 2.6.4
 - OS/Distribution and version:  Pop!_OS 22.04
 - Desktop environment: GNOME 42.2
 - Installation method: Flatpak

**Additional context**
Thanks for Foliate!

**Comment by johnfactotum** [comment] 2022-08-11 10:26
Duplicate of #265

**Closed by johnfactotum** 2022-08-11 10:26 UTC
Labels: bug
