### ISSUE TITLE
Can't open a book after a restart of the system.

### ISSUE THREAD

**Issue by ConEstArthur** [johnfactotum/foliate#1178] opened 2023-12-10 17:43 UTC
**Describe the bug**
Basically Foliate has no idea where the book is after I restart the system. It occurs when I open a book from **Files** app (file manager), which then foliate imports into library. 

**To Reproduce**
1. Open any book epub or mobi from file manager. 
2. Restart the system.
3. Launch Foliate and in library, click on the book which you opened from file manager.
4. It cannot be found.

**Expected behavior**
It should remember the location of the books ? I surmise.

**Screenshots**
![Screenshot from 2023-12-10 22-55-24](https://github.com/johnfactotum/foliate/assets/76774182/8adffdea-7554-4c10-8d9f-0f7c5c1edcd7)

**Version:**
 - Foliate version: 3.0.1
 - OS/Distribution and version: Fedora 39
 - Desktop environment: Gnome 45.2
 - Installation method: Flatpak

**Additional context**
Of course when I choose **Open** option in app itself. It opens just fine after the restart.

**Comment by johnfactotum** [comment] 2023-12-10 18:26
Duplicate of #942

**Closed as not planned by johnfactotum** 2023-12-10 18:26 UTC
Labels: bug, duplicate
