### ISSUE TITLE
Flatpak dont show the pages of the books

### ISSUE THREAD

**Issue by FAb7D** [johnfactotum/foliate#1170] opened 2023-12-03 22:22 UTC
**Describe the bug**
With the flatpak on Solus  the program opens, you see the books, you see the index of the books, you don't see the text and the pages in general

**To Reproduce**
flatpak install flathub com.github.johnfactotum.Foliate
flatpak install flathub com.github.johnfactotum.Foliate

**Expected behavior**

**Screenshots**
```
$ flatpak run com.github.johnfactotum.Foliate

(com.github.johnfactotum.Foliate:2): com.github.johnfactotum.Foliate-WARNING **: 22:57:34.955: Gio.DBusError: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name is not activatable
getURIFromTracker@resource:///com/github/johnfactotum/Foliate/library.js:16:60
get@resource:///com/github/johnfactotum/Foliate/library.js:56:42
getBookFromIdentifier@resource:///com/github/johnfactotum/Foliate/library.js:105:36
getBook@resource:///com/github/johnfactotum/Foliate/library.js:101:21
activate@resource:///com/github/johnfactotum/Foliate/library.js:394:63
activate@resource:///com/github/johnfactotum/Foliate/library.js:322:18
_init/GLib.MainLoop.prototype.runAsync/</<@resource:///org/gnome/gjs/modules/core/overrides/GLib.js:266:34
  
KMS: DRM_IOCTL_MODE_CREATE_DUMB failed: Permesso negato
Failed to create GBM buffer of size 1903x1148: Permesso negato
KMS: DRM_IOCTL_MODE_CREATE_DUMB failed: Permesso negato
Failed to create GBM buffer of size 1903x1148: Permesso negato
KMS: DRM_IOCTL_MODE_CREATE_DUMB failed: Permesso negato
Failed to create GBM buffer of size 1903x1148: Permesso negato
Failed to create EGL images for DMABufs with file descriptors -1, -1 and -1

(com.github.johnfactotum.Foliate:2): com.github.johnfactotum.Foliate-WARNING **: 22:58:14.191: Gio.DBusError: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name is not activatable
getURIFromTracker@resource:///com/github/johnfactotum/Foliate/library.js:16:60
get@resource:///com/github/johnfactotum/Foliate/library.js:56:42
getBookFromIdentifier@resource:///com/github/johnfactotum/Foliate/library.js:105:36
getBook@resource:///com/github/johnfactotum/Foliate/library.js:101:21
activate@resource:///com/github/johnfactotum/Foliate/library.js:394:63
activate@resource:///com/github/johnfactotum/Foliate/library.js:322:18
_init/GLib.MainLoop.prototype.runAsync/</<@resource:///org/gnome/gjs/modules/core/overrides/GLib.js:266:34
  
KMS: DRM_IOCTL_MODE_CREATE_DUMB failed: Permesso negato
Failed to create GBM buffer of size 1903x1148: Permesso negato
KMS: DRM_IOCTL_MODE_CREATE_DUMB failed: Permesso negato
Failed to create GBM buffer of size 1903x1148: Permesso negato
KMS: DRM_IOCTL_MODE_CREATE_DUMB failed: Permesso negato
Failed to create GBM buffer of size 1903x1148: Permesso negato
Failed to create EGL images for DMABufs with file descriptors -1, -1 and -1

(com.github.johnfactotum.Foliate:2): Gdk-CRITICAL **: 22:58:22.251: gdk_surface_get_device_position: assertion 'GDK_IS_SURFACE (surface)' failed

(com.github.johnfactotum.Foliate:2): Gtk-CRITICAL **: 22:58:22.251: _gtk_widget_find_at_coords: assertion 'GDK_IS_SURFACE (surface)' failed
KMS: DRM_IOCTL_MODE_CREATE_DUMB failed: Permesso negato
Failed to create GBM buffer of size 282x282: Permesso negato
KMS: DRM_IOCTL_MODE_CREATE_DUMB failed: Permesso negato
Failed to create GBM buffer of size 282x282: Permesso negato
KMS: DRM_IOCTL_MODE_CREATE_DUMB failed: Permesso negato
Failed to create GBM buffer of size 282x282: Permesso negato
Failed to create EGL images for DMABufs with file descriptors -1, -1 and -1
foliate:selection-tool:101:26: CONSOLE ERROR Error
![Screenshot_20231203_231859](https://github.com/johnfactotum/foliate/assets/104997294/c40b3e03-329c-4146-a789-1ab17b9851d3)
```
![Screenshot_20231203_231859](https://github.com/johnfactotum/foliate/assets/104997294/f7c36d4a-f67e-4540-8598-ab9b7342b31f)

**Version:**
 - Foliate version:3.01 flapak
 - OS/Distribution and version: [e.g.Solus]
 - Desktop environment: [e.g. KDE]
 - Installation method: [e.g. Flatpak]

**Additional context**

**Comment by johnfactotum** [comment] 2023-12-04 06:23
Duplicate of #1107

**Closed as not planned** 2023-12-04 06:24 UTC
Labels: bug, duplicate
