### ISSUE TITLE
Page navigation skips random pages

### ISSUE THREAD

**Issue by mxnemu** [johnfactotum/foliate#929] opened 2022-08-10 18:35 UTC
**Describe the bug**
When trying to move to the next / previous page. It moves a random amount of pages and always skips certain pages. 

Maybe https://github.com/johnfactotum/foliate/issues/900 is relevant, but for me it actually skips pages, it is not just the counter that is wrong.

**To Reproduce**
1. Download this epub https://archive.org/download/TaoismTaoOfYiJingJouTsungHwamin/%5BTaoism%5DTao_of_Yi_Jing%28JouTsungHwa%29min.epub
2. open it
3. try to tap on the left or right side of the screen / use the right or left arrow key.
4. It moves multiple pages forward / backwards.
5. 6. I can't navigate to the pages 9-24.
6. Page 25 randomly has different content from the previous pages.

**Expected behavior**
It only moves one page per tap.

**Screenshots**
Here is a screencast. The left half is Foliate, the right half is Calibre. Pages 9-24 can never be reached in Foliate. 

[bug.webm](https://user-images.githubusercontent.com/560561/183989441-3e0fadf1-71b4-4bae-83e6-9a2eccc6709e.webm)

**Version:**
I first encountered this on the Pinephone Manjaro ARM from gnome software and later confirmed it on the desktop with flatpak.

 - Foliate version: v2.6.4 
 - OS/Distribution and version: Manjaro ARM / Ubuntu 20.04
 - Desktop environment: Phosh / Xmonad
 - Installation method: Gnome Software / Flatpak

**Additional context**
Try to open this same epub in calibre, or the Archive.org [web viewer](https://archive.org/details/TaoismTaoOfYiJingJouTsungHwamin/). It displays as expected.

**Comment by johnfactotum** [comment] 2022-08-11 10:24
This is an Epub.js bug (see https://github.com/johnfactotum/foliate/wiki#my-book-is-not-displayed-properly for how to reproduce with Epub.js) and I'm not sure why it's happening. At first I thought it might be that the text width is not calculated properly, but that does not appear to be the case.

**Comment by johnfactotum** [comment] 2022-10-19 18:05
By the way I think this is actually a duplicate of #23, which is the same problem with another EPUB from archive.org.

**Comment by johnfactotum** [comment] 2022-10-25 07:29
Fixed in the new renderer (https://github.com/johnfactotum/foliate/issues/962).

**Closed by johnfactotum** 2022-10-25 07:29 UTC
Labels: bug, epub.js

**Comment by johnfactotum** [comment] 2023-06-12 06:54
For reference, I believe the issue is due to Epub.js not supporting `default` for `page-progression-direction`. See https://github.com/futurepress/epub.js/issues/1340#issuecomment-1586685310.
