### ISSUE TITLE
Request always two columns and scroll one column only

### ISSUE THREAD

**Issue by jack6th** [johnfactotum/foliate#670] opened 2021-02-11 23:11 UTC
Request two functions:   
1. always two columns   
If width > 1500 and no sidebar Foliate will be four columns.   
If I use sidebar and drag it wider it changes to two columns.   
Please add an option to stick two columns.   
2. scroll one column only   
Some books have a lot of charts in it.   
The text before and after the chart often relate to the chart.   
If the chart is at the bottom of the right column, user cannot see the chart when he scroll to the next page.   
Plese add an option to scroll on column only so that the chart page can be scroll to the left column.

**Comment by johnfactotum** [comment] 2021-02-17 07:51
> always two columns

This is a duplicate of #538 

> scroll one column only

Duplicate of #187?

**Closed** 2021-02-17 08:30 UTC
Labels: duplicate, enhancement
