### ISSUE TITLE
Tooltips on the sidebar flickers

### ISSUE THREAD

**Issue by gitkeerthi** [johnfactotum/foliate#903] opened 2022-05-26 15:46 UTC
**Describe the bug**
Tooltips on the sidebar (where toc shows up) flickers

**To Reproduce**
1. Open an ebook
2. Open sidebar by clicking on the icon at top left corner of the windoe
3. Slowly hover over the table of contents allowing tooltips to pop
4. Tooltip begin to flicker. Sometimes they do, sometimes they don't. Very inconsistent though.

**Expected behavior**
There should be no flickering

**Screenshots**
N/A

**Version:**
 - Foliate version: 2.6.3
 - OS/Distribution and version: Fedora 36
 - Desktop environment: GNOME 42.1
 - Installation method: Flatpak (rpm is build unusable though)

**Additional context**
None

**Comment by johnfactotum** [comment] 2022-05-27 05:42
Duplicate of #746

**Closed by johnfactotum** 2022-05-27 05:42 UTC
Labels: bug

**Comment by budgetClick** [comment] 2022-07-16 01:17
I was able to solve this by enabling "use sidebar" in preferences.

**Comment by gitkeerthi** [comment] 2022-07-16 04:49
How do I stop receiving
