### ISSUE TITLE
Could not open any file

### ISSUE THREAD

**Issue by eXConf** [johnfactotum/foliate#886] opened 2022-04-15 17:35 UTC
**Describe the bug**
Hello. After today's update on Manjaro I can't open any book (my library consists of FB2 and EPUB files), Foliate just says "Could not open file" and "Empty response". Here is what I get in terminal:

```
(com.github.johnfactotum.Foliate:3996): Tracker-CRITICAL **: 20:19:28.737: tracker_bus_fd_cursor_real_get_string: assertion 'cursor_finished == false' failed

(com.github.johnfactotum.Foliate:3996): Gjs-WARNING **: 20:19:29.276: JS ERROR: Error: Load failed
_init/<@resource:///com/github/johnfactotum/Foliate/js/epubView.js:623:57
_handleAction@resource:///com/github/johnfactotum/Foliate/js/epubView.js:886:22
_init/<@resource:///com/github/johnfactotum/Foliate/js/epubView.js:617:18
main@resource:///com/github/johnfactotum/Foliate/js/main.js:478:24
run@resource:///org/gnome/gjs/modules/script/package.js:206:19
@/usr/bin/foliate:9:17

```

**Version:**
 - Foliate version: 2.6.4.1
 - OS/Distribution and version: Linux exconf-PC 5.10.109-1-MANJARO # 1 SMP PREEMPT Mon Mar 28 09:16:20 UTC 2022 x86_64 GNU/Linux
 - Desktop environment: GNOME 41
 - Installation method: Manjaro's Official Repositories (community)

**Comment by johnfactotum** [comment] 2022-04-16 05:29
Duplicate of #878, I think.

**Closed by johnfactotum** 2022-04-16 05:29 UTC
Labels: bug
