### ISSUE TITLE
Foliate failing to remember position past a specific page.

### ISSUE THREAD

**Issue by polzon** [johnfactotum/foliate#807] opened 2021-11-08 10:21 UTC
**Describe the bug**
I've been reading an eBook of Dune. It's a 1.1MB epub file with about 1197 pages (DejaVu Serif 14).

Past page 96, when I exit out of Foliate, it will no longer remember my position in the book. Any point I exit Foliate after page 96, I will be warped back to 96. If I exit before that point, it will remember my position just fine (e.g if I exit at 64, it will remember page 64). 

I've tried uninstalling, reinstalling, and clearing cache. They did not work. 

I've also tried installing the rpm of Foliate from the official Fedora 35 repo, also tried installing Foliate from the Fedora Flatpak repo. Both had the same issue.

I have been unable to reproduce this with other books, it's hard to narrow down the behavior.

**To Reproduce**
1. Open a large epub like Dune in this example.
2. Go to a page past 96, like 116 for example.
3. Close out of Foliate, then reopen.
4. You will be put back to page 96.

**Version:**
 - Foliate version: 2.6.3
 - OS/Distribution and version: Fedora 35
 - Desktop environment: Gnome 41.1, Wayland
 - Installation method: Flatpak via Flathub (user)

**Additional context**
I will add additional details if I can find a way to consistently reproduce with public eBooks from a source like Project Gutenberg.

**Comment by johnfactotum** [comment] 2022-10-25 08:12
I think this might be a duplicate of https://github.com/johnfactotum/foliate/issues/653

**Closed** 2022-10-25 08:15 UTC
Labels: bug, duplicate, epub.js
