### ISSUE TITLE
Please release it for windows

### ISSUE THREAD

**Issue by yogeshbatra** [johnfactotum/foliate#1071] opened 2023-08-30 18:42 UTC
Please release it for windows. I cant use wsl because of win 7 user so it would be helpful if you release it for windows.

**Comment by johnfactotum** [comment] 2023-08-31 10:47
Duplicate of #115.

I should note that even if there's a Windows version, it's highly unlikely that Windows 7 would be supported, as most browser engines have already dropped support for it. AFAIKT the only browser that still supports Windows 7 is Firefox ESR.

If you just want to *view* e-books, though, you could consider using the very bare bones demo reader: https://johnfactotum.github.io/foliate-js/reader.html.

**Closed by johnfactotum** 2023-08-31 10:47 UTC
Labels: enhancement
