### ISSUE TITLE
Please release it for Windows too !

### ISSUE THREAD

**Issue by anuragoasis** [johnfactotum/foliate#805] opened 2021-11-07 17:20 UTC
We all windows users request you to please release for Windows also.
Because "all" the windows ebook reader is crap and has very pathetic UI.

We love your creative Interface style approach very much and admire your project.
Infront of your project every other project is sh*t. 

We would really appreciate that if you could help us with this. And admire your work. 
Waiting for your next release of Windows version!

**Comment by apandada1** [comment] 2021-11-09 13:50
Duplicate of https://github.com/johnfactotum/foliate/issues/115.

You can run it in Windows with [some effort](https://github.com/johnfactotum/foliate/issues/115#issuecomment-830005534).

_We all GNU/Linux users request you to switch to GNU/Linux, and you will see the difference._

**Comment by anuragoasis** [comment] 2021-11-10 03:12
We appreciate linux OS 
We even run kali on android

But we would like to have a Windows executable file, and not vm running on windows.

**Closed** 2021-11-11 03:35 UTC
Labels: duplicate, enhancement

**Comment by anuragoasis** [comment] 2021-11-11 04:13
Reopen
