### ISSUE TITLE
It closes by itself

### ISSUE THREAD

**Issue by ijann** [johnfactotum/foliate#454] opened 2020-06-13 14:06 UTC
It closes by itself, this is the error that the console shows.

I installed it using pamac gui, my system is Manjaro cinnamon x64,
What I can say is that after a few hours it closes.
It is annoying but at least the time lapse when the app breaks is not very often. I mean I can be using the app for about 2 to 4 hours and then it breaks. I have to open it again.

Does this have something to do with nodejs installed on my system ?, 
I have version 12.17.0-1 nodejs-lts-erbium installed

![imagen](https://user-images.githubusercontent.com/2209203/84570279-e0509880-ad62-11ea-8731-6944f64e6340.png)

**Comment by johnfactotum** [comment] 2020-06-13 16:24
Looks like a duplicate of #357.

**Closed** 2020-06-13 16:25 UTC
Labels: duplicate
