### ISSUE TITLE
Missing Shortcuts

### ISSUE THREAD

**Issue by itprojects** [johnfactotum/foliate#203] opened 2019-11-12 15:24 UTC
Some of the old, great shortcuts are missing. Space, Backspace, Page Up, Page Down.

@johnfactotum Is this design or bug?

**Comment by johnfactotum** [comment] 2019-11-12 15:51
None of the shortcuts are missing. If it doesn't, then it's a bug.

**Comment by itprojects** [comment] 2019-11-12 17:12
In version 1.x there was Space, backspace for next and previous page. Those were great shortcuts! Quick and easy - 100 pages used to go in 2 hours! Would you believe it?

**Comment by johnfactotum** [comment] 2019-11-12 17:22
All the shortcuts are still there and work the same way as they did in 1.x. If they don't work for you, it's probably because the webview doesn't have focus (which is true also for 1.x). Otherwise, it must be some bug in determining whether the view is zoomed. In which case scrolling through pages (with touchpad or mouse) will also be broken for you.

**Comment by itprojects** [comment] 2019-11-12 18:40
@johnfactotum There is a real bug here.

In Scrolled mode you can scroll, when the webview has focus. You can use Space, Page Up, Page Down, Arrow Left, Arrow Right, just not Backspace.

Disabling Skeuomorphism is a direct fix, but then the app doesn't look as great. One step forward, two bugs back!

**Comment by itprojects** [comment] 2019-11-12 18:41
You can close this bug, as it's already in a Project Card, that you are targeting for 2.x

**Comment by itprojects** [comment] 2019-11-29 14:34
In and after commit "Add sidebar option" 6a51ab2b763b04466344bf863d89417de8853d8
 this bug in essence is reproduced. Space, arrow left, arrow right, and scroll, are practically unavailable, again.

**Comment by johnfactotum** [comment] 2019-11-29 15:43
I can't reproduce.

**Comment by itprojects** [comment] 2019-11-29 18:17
When installing master (`23bbf8c4`) with meson/ninja in Ubuntu 19.10, those shortcut keys don't work, but N and P correctly change pages.

So you have those shortcut keys working?

**Comment by johnfactotum** [comment] 2019-11-30 05:43
Yes.

**Comment by itprojects** [comment] 2019-11-30 12:02
@johnfactotum This bug happens when the page is zoomed in/out other than exactly 100%. If the value is restored to 100% there is no bug.

**Comment by johnfactotum** [comment] 2019-12-01 03:59
Thanks. Fixed now.

**Closed by johnfactotum** 2019-12-01 03:59 UTC
Labels: works for me
