### ISSUE TITLE
Full screen mode

### ISSUE THREAD

**Issue by blueorignal** [johnfactotum/foliate#4] opened 2019-05-31 05:02 UTC
Hi,

Firstly, thank you for an amazing ebook reader. I've been looking like for something like foliate on Linux for years.

One item I was wondering if you could consider implementing, is a full screen reading mode. This would enable a more immersive reading experience.

Thank you for the great development work. :+1:

**Comment by johnfactotum** [comment] 2019-05-31 05:11
A basic fullscreen mode has already been added in da1e72b.

"Basic" because currently you can't access the headerbar once you've enter fullscreen. Other than that, it's quite functional.

**Comment by elcste** [comment] 2019-05-31 12:21
If you need a model to emulate, [Celluloid](https://celluloid-player.github.io/) (formerly GNOME MPV) does a good job with full screen with an auto-hiding header bar and bottom toolbar.

It also puts a full screen button on the header bar, near the menu button, which I think would be a great addition, too.

**Comment by blueorignal** [comment] 2019-06-02 07:59
Thank you. That looks great. Will this be available in the next release? Obviously it didn't make it into the current version (1.0.1). I can't thank you enough for your work on foliate. Finally a decent ebook reader for Linux!

**Comment by johnfactotum** [comment] 2019-06-02 11:42
I'm thinking about doing a 1.1.0 release very soon, including the basic fullscreen support. A more complete fullscreen mode with autohide bars is still planned but might not happen in the very short term.

**Comment by blueorignal** [comment] 2019-06-02 13:01
There's no rush. I am just so thankful that someone is focusing on bringing a worthwhile ebook reader to Linux. Keep up the great work!

**Comment by itprojects** [comment] 2019-06-03 03:32
Tested Foliate v1.1.0: has full-screen mode working with F11 key.

**Comment by blueorignal** [comment] 2019-06-03 05:03
Thank you. This is perfect. Foliate now allows for a totally immersive reading experience when you combine full screen and hide the reading progress bar. Brilliant! :grin:

**Comment by itprojects** [comment] 2019-07-05 09:54
@johnfactotum In Evince, when the app is in full-screen mode the top bar retracts (to become hidden), until the mouse is moved; then shown, if the mouse moves; then hidden again, if the mouse stops for a few seconds. In Foliate this could mean you can have a progress bar on mouse move, but it be hidden, if you want to read in distraction-free mode (using keyboard). What do you think?

**Comment by itprojects** [comment] 2019-07-05 10:37
Gnome-books has a floating progress bar.

![See image.](https://user-images.githubusercontent.com/2698054/60717238-caaae000-9f10-11e9-9e9f-b1f383152abc.png)

**Comment by itprojects** [comment] 2019-10-28 19:05
@johnfactotum Commit `9ef30148` has added an overlay bar. Close this bug?

**Comment by blueorignal** [comment] 2019-10-30 00:06
Close away 🙂

**Comment by johnfactotum** [comment] 2019-10-30 05:38
The headerbar is still not accessible when in fullscreen, so this issue still stands. We need to make a duplicate headerbar and overlay it in fullscreen. Actually I kind of wonder why there's no built-in support for fullscreen headerbars in GTK.

**Comment by itprojects** [comment] 2019-10-30 11:41
Cursor autohide is broken, after the first new progress bar commit. Layer issue?

Why isn't there built-in support for fullscreen headerbars in GTK? Could be they've been waiting for this bug report for a while.

Doesn't making a duplicate of the headerbar in fullscreen defeat the point of fullscreen?

**Comment by johnfactotum** [comment] 2019-10-30 17:35
Cursor autohide being broken is unrelated to the overlaid controls, and is fixed with ad1fec4d05ca90f7a480c1d023145b850a38cf5f.

A duplicate of the headerbar in fullscreen will be hidden by default, and only revealed when needed, when the pointer moves to the top edge of the screen or when the screen is tapped.

**Comment by itprojects** [comment] 2019-10-30 19:55
Confirmed: auto-hide cursor is normal again.

**Closed** 2019-10-31 00:12 UTC
Labels: enhancement
