### ISSUE TITLE
Better appdata summary?

### ISSUE THREAD

**Issue by bertob** [johnfactotum/foliate#1088] opened 2023-10-08 13:44 UTC
The current summary "A simple and modern eBook viewer" starts with an article, which is not recommended. It also includes "simple" and "modern", which feel a bit generic. Maybe something like "Read your eBook collection" or "Read and annotate eBooks" could work?

More general guidance here: https://gitlab.gnome.org/GNOME/Initiatives/-/wikis/App-Metadata

**Comment by johnfactotum** [comment] 2023-10-08 13:47
Duplicate of #596.

**Comment by bertob** [comment] 2023-10-08 13:50
Haha sorry, should have searched beforehand!

Side note: Very excited to see the work happening on the gtk4 branch :star_struck:

**Comment by johnfactotum** [comment] 2023-10-08 13:53
Thanks!

**Closed by johnfactotum** 2023-10-08 13:53 UTC
Labels: duplicate, enhancement
