### ISSUE TITLE
Middle separation line missing upon opening a book

### ISSUE THREAD

**Issue by shadowislord** [johnfactotum/foliate#94] opened 2019-06-29 15:18 UTC
(Version 1.3.1 on Ubuntu 19.04, X11, GNOME 3.32.1 on a 4K monitor)

Upon opening a book, the line separating the two pages will be missing. The line will reappear on these actions:

- Changing the margins
- Changing the layout
- Resizing the window
- Enabling full screen mode
- Enabling reading progress bar

Upon opening a book:
![Screenshot from 2019-06-29 11-09-46](https://user-images.githubusercontent.com/6314496/60386152-7fe81e80-9a5f-11e9-8025-4ca4f5d53eb5.png)

Resizing:
![Screenshot from 2019-06-29 11-09-54](https://user-images.githubusercontent.com/6314496/60386154-88d8f000-9a5f-11e9-9fa5-f6402a18df1d.png)

**Comment by itprojects** [comment] 2019-06-29 15:57
+1 Confirmed. This does NOT appear to be related to epub.js line 4636, from https://github.com/johnfactotum/foliate/issues/76 . Changing the theme does not redraw (because it's CSS?) the line.

**Comment by johnfactotum** [comment] 2019-06-30 02:01
The divider isn't the only thing that's broken when the navbar is hidden on startup. Whatever's causing this seems to have "jammed" some of the events and hooks in Epub.js.

Interestingly, a sidebar was added recently, and this doesn't happen when the sidebar is shown.

**Comment by itprojects** [comment] 2019-06-30 16:14
Dividers: who needs them anyway!?

**Comment by itprojects** [comment] 2019-07-04 15:46
Please pardon the newbie questions.

This behaviour is happening when the progress-bar and side-bar are both missing, or when the app is in full-screen.

Question:

does this mean that the event, even if emitted, is not received by the relevant UI element, because that UI element is hidden/out-of-reach, and the system refuses to draw/change or change it (to save cycles)?

Shouldn't Epub.js emit, and GJS receive? But then how can a GJS draw if it is currently on an **invisible** **layer**?

Is the divider inside Epub.js or ontop of that layer?

**Comment by johnfactotum** [comment] 2019-07-05 03:50
@itprojects The events are not being emitted by Epub.js at all -- that's the problem. The divider is drawn inside the WebView on the "layout" event; GJS need not receive anything.

I've pushed a fix. It's hacky but it works.

**Closed** 2019-07-05 03:51 UTC
Labels: bug
