### ISSUE TITLE
Add an option to switch off pop up text when hover on the main text

### ISSUE THREAD

**Issue by ShelpAm** [johnfactotum/foliate#1374] opened 2024-08-06 03:18 UTC
That pop up text is annoying, blocking my view, when I want to view the text below, like this:
![image](https://github.com/user-attachments/assets/3b70fbb4-917c-4049-a60f-e7b8e641f31f)

**Comment by johnfactotum** [comment] 2024-08-07 18:19
Duplicate of #196

**Closed as not planned by johnfactotum** 2024-08-07 18:19 UTC
Labels: duplicate, enhancement
