### ISSUE TITLE
Noticeable stutter in Scrolled and Continuous layouts

### ISSUE THREAD

**Issue by lewisbolaton** [johnfactotum/foliate#861] opened 2022-01-25 02:17 UTC
**Describe the bug**
Frequent stutters seem to occur while scrolling in Scrolled and Continuous layouts. This usually happens when scrolling on a large number of lines (say a page or more) but sometimes it just happens randomly. I use a touchpad so the issue is much more apparent. The stutter looks as if the next page is waiting to be rendered (causing the application to freeze abruptly) then the scrolling continues as normal making it look like there was a frame drop. Sometimes, this makes me lose track of the line I am reading. 

I do not think the culprit here is primarily the number of pages displayed since in the Scrolled layout, it still happens even if a chapter only has a modest amount of pages. The issue occurs in the Scrolled layout as often as it is in the Continuous layout. 

**Version:**
 - Foliate version: 2.6.3
 - OS/Distribution and version: Fedora Workstation 34 (Wayland)
 - Desktop environment: GNOME 40.5
 - Installation method: Flatpak but issue still persists when installed natively

**Comment by johnfactotum** [comment] 2022-01-26 03:51
In scrolled mode, at least, it appears to be entirely caused by Epub.js [calculating the current location on every single scroll event](https://github.com/futurepress/epub.js/blob/858c3a8f91ba2387e12fffbd3e9b98757e65c9ba/src/rendition.js#L255).

This can be tested by removing the event handler:

```diff
diff --git a/src/web/epub.js b/src/web/epub.js
index 7329296..8a271a4 100644
--- a/src/web/epub.js
+++ b/src/web/epub.js
@@ -8477,7 +8477,7 @@ class rendition_Rendition {
 
     this.manager.on(constants["c" /* EVENTS */].MANAGERS.ORIENTATION_CHANGE, this.onOrientationChange.bind(this)); // Listen for scroll changes
 
-    this.manager.on(constants["c" /* EVENTS */].MANAGERS.SCROLLED, this.reportLocation.bind(this));
+    //this.manager.on(constants["c" /* EVENTS */].MANAGERS.SCROLLED, this.reportLocation.bind(this));
     /**
      * Emit that rendering has started
      * @event started
```

After this scrolling is smooth in the scrolled layout. So to fix this, it probably just needs to be debounced.

This doesn't seem to work for the continuous layout, though. I presume that in continuous scrolling, it probably has other event handlers checking whether to load the next/previous section, which should perhaps also be debounced/throttled.

**Comment by johnfactotum** [comment] 2022-10-02 18:10
Didn't realize, but this seems to be a duplicate of #545

**Closed by johnfactotum** 2022-10-02 18:10 UTC
Labels: bug, epub.js
