### ISSUE TITLE
Foliate randomly crashes

### ISSUE THREAD

**Issue by dspacejs** [johnfactotum/foliate#576] opened 2020-08-30 05:55 UTC
**Describe the bug**
Occasionally the app crashes. No error message or error log is provided, so I don't know why this is happening. It's definitely not because of something like insufficient memory or CPU.

**To Reproduce**
Not sure how to reproduce this, since it happens randomly.

**Expected behavior**
It shouldn't crash. And if it does, it should display an error message/log so the problem can be resolved.

**Version:**
 - Foliate version: 2.4.2
 - OS/Distribution and version: Ubuntu 20.04 LTS
 - Desktop environment: 3.36.3
 - Installation method: apt

**Comment by apandada1** [comment] 2020-08-31 04:27
Can you open Foliate from the terminal (`com.github.johnfactotum.foliate`) and provide the error message when it crashes?

**Comment by dspacejs** [comment] 2020-08-31 09:47
@apandada1 sure, next time I use it I'll do this and report back if it crashes

**Comment by dspacejs** [comment] 2020-09-02 02:53
@apandada1 `flatpak run com.github.johnfactotum.Foliate` doesn't work. Says the app doesn't exist. I used the official Flathub page to install it, so I'm not sure why this doesn't work.

**Comment by apandada1** [comment] 2020-09-02 03:51
>     * Installation method: apt
In the original post you wrote installation method is `apt`. Did you once again install it with Flatpak? Is the issue present in apt (.deb file or ppa) or Flatpak?

**Comment by dspacejs** [comment] 2020-09-03 08:33
@apandada1 oh yeah oops, that's right, I used apt. There's no `foliate` command when installing via apt, so how do I launch it from the command line?

**Comment by apandada1** [comment] 2020-09-03 08:46
`com.github.johnfactotum.Foliate`

**Comment by fire-eggs** [comment] 2020-09-04 15:34
Thanks for the instructions. Here's one crash:
```
$ flatpak run com.github.johnfactotum.Foliate
Portal call failed: Failed to start command: Failed to execute child process “dict” (No such file or directory)
Portal call failed: Failed to start command: Failed to execute child process “sdcv” (No such file or directory)

(com.github.johnfactotum.Foliate:2): Gjs-ERROR **: 11:30:34.375: toggling down object GInotifyFileMonitor that's already queued to toggle up
```
In my case, I've got four books open in Foliate simultaneously. The crash is occurring while paging through book number one.

That book is showing problematic behavior around page numbers, I'll post a separate issue.

**Comment by johnfactotum** [comment] 2020-09-04 16:05
@fire-eggs See #357

**Comment by fire-eggs** [comment] 2020-09-04 17:20
Gotcha!

**Comment by dspacejs** [comment] 2020-09-08 01:54
@apandada1 just came across a crash:

```sh
➜  ~ com.github.johnfactotum.Foliate
CONSOLE ERROR The Content Security Policy directive 'sandbox' is ignored when delivered via an HTML meta element.
CONSOLE ERROR The Content Security Policy directive 'sandbox' is ignored when delivered via an HTML meta element.
CONSOLE ERROR The Content Security Policy directive 'sandbox' is ignored when delivered via an HTML meta element.

(com.github.johnfactotum.Foliate:10667): Gjs-ERROR **: 11:23:14.570: toggling down object GInotifyFileMonitor that's already queued to toggle up

[1]    10667 trace trap (core dumped)  com.github.johnfactotum.Foliate
```

**Comment by dspacejs** [comment] 2020-09-08 02:15
Just happened again, the exact same error:

```sh
➜  ~ com.github.johnfactotum.Foliate
CONSOLE ERROR The Content Security Policy directive 'sandbox' is ignored when delivered via an HTML meta element.
CONSOLE ERROR The Content Security Policy directive 'sandbox' is ignored when delivered via an HTML meta element.
CONSOLE ERROR The Content Security Policy directive 'sandbox' is ignored when delivered via an HTML meta element.
CONSOLE ERROR The Content Security Policy directive 'sandbox' is ignored when delivered via an HTML meta element.
file:///usr/share/com.github.johnfactotum.Foliate/assets/client.html:35:26: CONSOLE ERROR TypeError: undefined is not an object (evaluating 'results.forEach')

(com.github.johnfactotum.Foliate:11506): Gjs-ERROR **: 11:44:37.955: toggling down object GInotifyFileMonitor that's already queued to toggle up

[1]    11506 trace trap (core dumped)  com.github.johnfactotum.Foliate
```

**Comment by apandada1** [comment] 2020-09-08 03:22
Looks like this is a duplicate of #357.

**Closed** 2020-09-08 03:22 UTC
Labels: bug, duplicate
