### ISSUE TITLE
Page is blank in 3.0.0 version

### ISSUE THREAD

**Issue by enricosavegnago** [johnfactotum/foliate#1115] opened 2023-11-13 17:41 UTC
**Describe the bug**
It's unable to read any kind of .epub file in the 3.0.0 version and neither it shows the loading of the page. It's possible to open the book and view chapters and details but the text doesn't load.

**To Reproduce**
1. Go to 'Library'
2. Click on 'Open file'
3. See error

**Screenshots**
![Reading page](https://github.com/johnfactotum/foliate/assets/73057645/ae1f231e-6a56-4bbc-a0dc-8ab7301f9b12)

**Version:**
 - Foliate version: 3.0.0
System: Ubuntu Core 22
Desktop: X-Cinnamon
Session: cinnamon (x11)
Language: en_US.UTF-8

Versions:
- Foliate 3.0.0
- GJS 1.76.02
- GTK 4.12.2
- Adwaita 1.4.0
- GLib 2.78.0
- WebKitGTK 2.42.0

 - Installation method: Snap package

**Comment by archisman-panigrahi** [comment] 2023-11-13 17:49
Can you try the flatpak as well? We need to know if this is a snap-only bug.

**Comment by enricosavegnago** [comment] 2023-11-13 18:04
I've just tried the flatpak version. Same situation.

**Comment by archisman-panigrahi** [comment] 2023-11-13 18:48
Did you open the book from the library view or did you open Foliate directly by opening the book from your file manager? 

Can you reproduce the issue with other books? Try a free ebook like https://standardebooks.org/ebooks/jules-verne/an-antarctic-mystery/frances-cashel-hoey, and let us know.

**Comment by johnfactotum** [comment] 2023-11-13 23:57
Nvidia?

**Comment by brezanac** [comment] 2023-11-14 01:54
Same issue, Linux Mint 21.2 Cinnamon, Nvidia 535.129.03.

```
System: GNOME 45 (Flatpak runtime)
Desktop: X-Cinnamon
Session: cinnamon (x11)
Language: en_US.UTF-8

Versions:
- Foliate 3.0.0
- GJS 1.78.00
- GTK 4.12.3
- Adwaita 1.4.0
- GLib 2.78.1
- WebKitGTK 2.42.1

User directories:
- /home/brezanac/.var/app/com.github.johnfactotum.Foliate/data
- /home/brezanac/.var/app/com.github.johnfactotum.Foliate/cache
```
The application just hangs at loading the file after using the **Open** option.
![foliate-3 0 0-hang](https://github.com/johnfactotum/foliate/assets/389770/54b4f9b7-7d49-48a4-83b2-2ef96700e0b7)

It looks like something is crashing WebKitGTK.

![foliate-3 0 0](https://github.com/johnfactotum/foliate/assets/389770/12b0c88b-1b11-4739-952f-a6544637383f)

**Comment by johnfactotum** [comment] 2023-11-14 02:05
If it's showing a blank page, probably the same as #1085 and #1093.

The crash looks like something different. See https://github.com/flatpak/flatpak/issues/5564 and https://github.com/flatpak/flatpak/issues/3712

**Comment by brezanac** [comment] 2023-11-14 03:17
While running Foliate with explicit locale did solve the loading issues, no actual book content was displayed, aside from what was in the sidebar.

`flatpak run --env=LC_ALL=en_US.UTF-8 com.github.johnfactotum.Foliate`

![foliate-no-content](https://github.com/johnfactotum/foliate/assets/389770/017ea2ef-df13-4b60-81de-55817409c7d3)

The following errors were obviously the cause.

![flatpak-bus](https://github.com/johnfactotum/foliate/assets/389770/da69eb96-ddff-4d80-ab9f-ad7e99d77f7f)

So I decided to explicitly instruct WebKitGTK inside the flatpak package to revert back to WPE/X11 renderer.

`flatpak run --env=WEBKIT_DISABLE_DMABUF_RENDERER=1 --env=LC_ALL=en_US.UTF-8 com.github.johnfactotum.Foliate`

This fixed the issue and Foliate was now properly displaying all content.

![foliate-content](https://github.com/johnfactotum/foliate/assets/389770/969fda4d-ce07-48ba-b7d6-79d365f3b65c)

Now, `WEBKIT_DISABLE_DMABUF_RENDERER` is kind of an ugly solution, soon possibly to be deprecated or even removed from WebKitGTK, but it gets the job done for now.

To make a more permanent solution without the need to run Foliate through shell, you could use Flatseal to define the necessary
 environmental varaibles like this.

![foliate-flatseal](https://github.com/johnfactotum/foliate/assets/389770/c8f073e6-355f-4e10-9c57-034f0a487a94)

Hope this helps.

**Comment by archisman-panigrahi** [comment] 2023-11-14 03:59
@johnfactotum In the next minor version of Foliate, please consider adding a "Troubleshoot books not loading if you are running NVidia" link/button (which can point to the comment above) (https://github.com/johnfactotum/foliate/issues/1115#issuecomment-1809480892) in the library view page, which NVidia users can follow. Thay can also stop many duplicate of bug reports. Also, beginner users may not know about GitHub, and may install Foliate from a software center. They can troubleshoot the issue by following that link

**Comment by johnfactotum** [comment] 2023-11-14 04:20
Well, ideally it could be included in the "troubleshooting" section in the about dialog, but I don't think Libadwaita supports that.

Probably I'll pin an issue, add a section to the FAQ, and update the issue templates.

**Comment by timothyparez** [comment] 2023-11-15 04:13
Same issue here on Ubuntu 23.04 (snap)
Open Foliate and then open any epub. ToC is visible, but reading pane is empty

**Comment by MikhailTNY** [comment] 2023-11-15 15:29
Same issue on PopOS 22.04 LTS, had to add the env variables that @brezanac helpfully provided. Thanks.

**Closed** 2023-11-20 07:05 UTC
Labels: bug, not our bug

**Comment by zmazanv** [comment] 2023-12-18 08:21
[**Arch Wiki**: Window does not appear in Flatpak on Nvidia](https://wiki.archlinux.org/title/Gamescope#Window_does_not_appear_in_Flatpak_on_NVIDIA)

This is a known issue with Nvidia in Flatpak environments.

The linked Arch Wiki page includes a band-aid fix which does solve the issue, although inconvenient and not really a long-term solution. This could be made easier with a script if it this isn't resolved any time soon and it becomes too much of a headache to have to update the variable at each driver update.

The advantage over the other proposed "solution" of setting `WEBKIT_DISABLE_DMABUF_RENDERER=1` is that you don't lose hardware acceleration. `WEBKIT_DISABLE_DMABUF_RENDERER=1` makes the app noticeably sluggish due to this. The app runs perfectly fine with the linked "solution".

The environment variable to set for Nvidia driver version 545.29.06 would be:
`GBM_BACKENDS_PATH=/usr/lib/x86_64-linux-gnu/GL/nvidia-545-29-06/extra/gbm`

The driver version number would need to be updated to match the running Nvidia driver version.

You could then set this with an override with `flatpak override --env=GBM_BACKENDS_PATH=/usr/lib/x86_64-linux-gnu/GL/nvidia-XXX-YY-ZZ/extra/gbm com.github.johnfactotum.Foliate` or through setting the environment variable in Flatseal, which does the same thing.

![imagen](https://github.com/johnfactotum/foliate/assets/95514881/81969f0a-93e6-40b3-9c7c-5d37285ca928)
