### ISSUE TITLE
Foliate keeps shutting down when open an epub file

### ISSUE THREAD

**Issue by kshamse** [johnfactotum/foliate#409] opened 2020-05-30 12:26 UTC
When try to open an epub file the application window immediately closed, it was working fine until it's updated with the new UI.

Affected **version** : 2.2.0
Update: 29.5.20202
OS: Ubuntu 18.04

**When try to run application from terminal I got these:**
```
Gtk-Message: 14:12:11.840: Failed to load module "canberra-gtk-module"
Gtk-Message: 14:12:11.841: Failed to load module "canberra-gtk-module"

** (com.github.johnfactotum.Foliate:14466): ERROR **: 14:12:12.154: Unable to fork a new child process: Failed to execute child process “/usr/lib/x86_64-linux-gnu/webkit2gtk-4.0/WebKitWebProcess” (No such file or directory)
Trace/breakpoint trap (core dumped)
```

**When try to run application from terminal with Superuser I got these:**
```mkdir: cannot create directory '/run/user/0': Permission denied

(com.github.johnfactotum.Foliate:14205): dconf-CRITICAL **: 14:10:40.985: unable to create directory '/run/user/0/snap.foliate/dconf': Permission denied.  dconf will not work properly.```

**Comment by johnfactotum** [comment] 2020-05-30 13:53
@khubabshams It looks like you using the Snap package? I also have the Snap installed on Ubuntu 18.04, and it works fine.

Also why would you want to run it as superuser? I think that's generally a bad idea.

@galgalesh This seems like a issue with the Snap package?

**Comment by khubabshams** [comment] 2020-05-30 13:57
I just assumed it's a permission issue so I try run it with Superuser but it didn't work too

**Comment by galgalesh** [comment] 2020-07-11 22:54
I could reproduce this issue in June but I can't reproduce it anymore. I think it was an issue with the xdg desktop portals support in Ubuntu 18.04 at that time, but it has been updated since.

Given that nobody else commented on this issue and the reviews in Ubuntu software don't mention it, I think we can safely assume it's gone.

@johnfactotum I suggest to close this issue. If anyone else has the same issue, please reopen it and I'll investigate further.

**Comment by johnfactotum** [comment] 2020-07-12 09:52
All right. Closing for now.

**Closed by johnfactotum** 2020-07-12 09:52 UTC
Labels: bug, need info, snap

**Comment by Mousavi310** [comment] 2021-02-22 11:01
I have the same error:

    mkdir: cannot create directory '/run/user/0': Permission denied

    (com.github.johnfactotum.Foliate:64809): dconf-CRITICAL **: 14:27:42.644: unable to create directory '/run/user/0/snap.foliate/dconf': Permission denied.  dconf will not work properly.

    (com.github.johnfactotum.Foliate:64809): dconf-CRITICAL **: 14:27:42.644: unable to create directory '/run/user/0/snap.foliate/dconf': Permission denied.  dconf will not work properly.

    (com.github.johnfactotum.Foliate:64809): dconf-CRITICAL **: 14:27:42.646: unable to create directory '/run/user/0/snap.foliate/dconf': Permission denied.  dconf will not work properly.

    (com.github.johnfactotum.Foliate:64809): dconf-CRITICAL **: 14:27:42.648: unable to create directory '/run/user/0/snap.foliate/dconf': Permission denied.  dconf will not work properly.

    (com.github.johnfactotum.Foliate:64809): dconf-CRITICAL **: 14:27:42.648: unable to create directory '/run/user/0/snap.foliate/dconf': Permission denied.  dconf will not work properly.
    No protocol specified
    Unable to init server: Could not connect: Connection refused
    No protocol specified
    unable to open lockfile /run/user/0/snap.foliate/webkitgtk-wayland-compositor-7ddeb5af-659f-4c54-92d2-d182e62aeda3.lock check permissions
    Nested Wayland compositor could not create display socket

    (com.github.johnfactotum.Foliate:64809): dconf-CRITICAL **: 14:27:42.699: unable to create directory '/run/user/0/snap.foliate/dconf': Permission denied.  dconf will not work properly.

    (com.github.johnfactotum.Foliate:64809): dconf-CRITICAL **: 14:27:42.699: unable to create directory '/run/user/0/snap.foliate/dconf': Permission denied.  dconf will not work properly.

    (com.github.johnfactotum.Foliate:64809): dconf-CRITICAL **: 14:27:42.699: unable to create directory '/run/user/0/snap.foliate/dconf': Permission denied.  dconf will not work properly.

    (com.github.johnfactotum.Foliate:64809): dconf-CRITICAL **: 14:27:42.703: unable to create directory '/run/user/0/snap.foliate/dconf': Permission denied.  dconf will not work properly.

    (com.github.johnfactotum.Foliate:64809): dconf-CRITICAL **: 14:27:42.703: unable to create directory '/run/user/0/snap.foliate/dconf': Permission denied.  dconf will not work properly.

    (com.github.johnfactotum.Foliate:64809): dconf-CRITICAL **: 14:27:42.703: unable to create directory '/run/user/0/snap.foliate/dconf': Permission denied.  dconf will not work properly.

    (com.github.johnfactotum.Foliate:64809): dconf-CRITICAL **: 14:27:42.704: unable to create directory '/run/user/0/snap.foliate/dconf': Permission denied.  dconf will not work properly.

    (com.github.johnfactotum.Foliate:64809): dconf-CRITICAL **: 14:27:42.706: unable to create directory '/run/user/0/snap.foliate/dconf': Permission denied.  dconf will not work properly.

    (com.github.johnfactotum.Foliate:64809): dconf-CRITICAL **: 14:27:42.706: unable to create directory '/run/user/0/snap.foliate/dconf': Permission denied.  dconf will not work properly.

    (com.github.johnfactotum.Foliate:64809): dconf-CRITICAL **: 14:27:42.706: unable to create directory '/run/user/0/snap.foliate/dconf': Permission denied.  dconf will not work properly.

    (com.github.johnfactotum.Foliate:64809): dconf-CRITICAL **: 14:27:42.706: unable to create directory '/run/user/0/snap.foliate/dconf': Permission denied.  dconf will not work properly.

    (com.github.johnfactotum.Foliate:64809): dconf-CRITICAL **: 14:27:42.706: unable to create directory '/run/user/0/snap.foliate/dconf': Permission denied.  dconf will not work properly.

    (com.github.johnfactotum.Foliate:64809): dconf-CRITICAL **: 14:27:42.706: unable to create directory '/run/user/0/snap.foliate/dconf': Permission denied.  dconf will not work properly.

    (com.github.johnfactotum.Foliate:64809): dconf-CRITICAL **: 14:27:42.706: unable to create directory '/run/user/0/snap.foliate/dconf': Permission denied.  dconf will not work properly.

    (com.github.johnfactotum.Foliate:64809): dconf-CRITICAL **: 14:27:42.706: unable to create directory '/run/user/0/snap.foliate/dconf': Permission denied.  dconf will not work properly.

    (com.github.johnfactotum.Foliate:64809): dconf-CRITICAL **: 14:27:42.707: unable to create directory '/run/user/0/snap.foliate/dconf': Permission denied.  dconf will not work properly.

    (com.github.johnfactotum.Foliate:64809): dconf-CRITICAL **: 14:27:42.707: unable to create directory '/run/user/0/snap.foliate/dconf': Permission denied.  dconf will not work properly.

    (com.github.johnfactotum.Foliate:64809): dconf-CRITICAL **: 14:27:42.707: unable to create directory '/run/user/0/snap.foliate/dconf': Permission denied.  dconf will not work properly.

    (com.github.johnfactotum.Foliate:64809): dconf-CRITICAL **: 14:27:42.707: unable to create directory '/run/user/0/snap.foliate/dconf': Permission denied.  dconf will not work properly.

    (com.github.johnfactotum.Foliate:64809): dconf-CRITICAL **: 14:27:42.707: unable to create directory '/run/user/0/snap.foliate/dconf': Permission denied.  dconf will not work properly.

    (com.github.johnfactotum.Foliate:64809): dconf-CRITICAL **: 14:27:42.707: unable to create directory '/run/user/0/snap.foliate/dconf': Permission denied.  dconf will not work properly.

    (com.github.johnfactotum.Foliate:64809): dconf-CRITICAL **: 14:27:42.707: unable to create directory '/run/user/0/snap.foliate/dconf': Permission denied.  dconf will not work properly.

    (com.github.johnfactotum.Foliate:64809): dconf-CRITICAL **: 14:27:42.707: unable to create directory '/run/user/0/snap.foliate/dconf': Permission denied.  dconf will not work properly.

    (com.github.johnfactotum.Foliate:64809): dconf-CRITICAL **: 14:27:42.707: unable to create directory '/run/user/0/snap.foliate/dconf': Permission denied.  dconf will not work properly.

    (com.github.johnfactotum.Foliate:64809): dconf-CRITICAL **: 14:27:42.707: unable to create directory '/run/user/0/snap.foliate/dconf': Permission denied.  dconf will not work properly.

    (com.github.johnfactotum.Foliate:64809): dconf-CRITICAL **: 14:27:42.707: unable to create directory '/run/user/0/snap.foliate/dconf': Permission denied.  dconf will not work properly.

    (com.github.johnfactotum.Foliate:64809): dconf-CRITICAL **: 14:27:42.714: unable to create directory '/run/user/0/snap.foliate/dconf': Permission denied.  dconf will not work properly.

    (com.github.johnfactotum.Foliate:64809): dconf-CRITICAL **: 14:27:42.714: unable to create directory '/run/user/0/snap.foliate/dconf': Permission denied.  dconf will not work properly.

    (com.github.johnfactotum.Foliate:64809): dconf-CRITICAL **: 14:27:42.727: unable to create directory '/run/user/0/snap.foliate/dconf': Permission denied.  dconf will not work properly.

    (com.github.johnfactotum.Foliate:64809): dconf-CRITICAL **: 14:27:42.727: unable to create directory '/run/user/0/snap.foliate/dconf': Permission denied.  dconf will not work properly.

    (com.github.johnfactotum.Foliate:64809): dconf-CRITICAL **: 14:27:42.740: unable to create directory '/run/user/0/snap.foliate/dconf': Permission denied.  dconf will not work properly.

    (com.github.johnfactotum.Foliate:64809): dconf-CRITICAL **: 14:27:42.740: unable to create directory '/run/user/0/snap.foliate/dconf': Permission denied.  dconf will not work properly.

    (com.github.johnfactotum.Foliate:64809): dconf-CRITICAL **: 14:27:42.740: unable to create directory '/run/user/0/snap.foliate/dconf': Permission denied.  dconf will not work properly.

    (com.github.johnfactotum.Foliate:64809): dconf-CRITICAL **: 14:27:42.740: unable to create directory '/run/user/0/snap.foliate/dconf': Permission denied.  dconf will not work properly.

    (com.github.johnfactotum.Foliate:64809): dconf-CRITICAL **: 14:27:42.740: unable to create directory '/run/user/0/snap.foliate/dconf': Permission denied.  dconf will not work properly.

    (com.github.johnfactotum.Foliate:64809): dconf-CRITICAL **: 14:27:42.741: unable to create directory '/run/user/0/snap.foliate/dconf': Permission denied.  dconf will not work properly.

    (com.github.johnfactotum.Foliate:64809): dconf-CRITICAL **: 14:27:42.758: unable to create directory '/run/user/0/snap.foliate/dconf': Permission denied.  dconf will not work properly.

    (com.github.johnfactotum.Foliate:64809): dconf-CRITICAL **: 14:27:42.758: unable to create directory '/run/user/0/snap.foliate/dconf': Permission denied.  dconf will not work properly.

    (com.github.johnfactotum.Foliate:64809): dconf-CRITICAL **: 14:27:42.762: unable to create directory '/run/user/0/snap.foliate/dconf': Permission denied.  dconf will not work properly.

    (com.github.johnfactotum.Foliate:64809): dconf-CRITICAL **: 14:27:42.763: unable to create directory '/run/user/0/snap.foliate/dconf': Permission denied.  dconf will not work properly.

    (com.github.johnfactotum.Foliate:64809): dconf-CRITICAL **: 14:27:42.763: unable to create directory '/run/user/0/snap.foliate/dconf': Permission denied.  dconf will not work properly.

    (com.github.johnfactotum.Foliate:64809): dconf-CRITICAL **: 14:27:42.766: unable to create directory '/run/user/0/snap.foliate/dconf': Permission denied.  dconf will not work properly.

    (com.github.johnfactotum.Foliate:64809): dconf-CRITICAL **: 14:27:42.766: unable to create directory '/run/user/0/snap.foliate/dconf': Permission denied.  dconf will not work properly.

    (com.github.johnfactotum.Foliate:64809): dconf-CRITICAL **: 14:27:42.766: unable to create directory '/run/user/0/snap.foliate/dconf': Permission denied.  dconf will not work properly.

    (com.github.johnfactotum.Foliate:64809): dconf-CRITICAL **: 14:27:42.766: unable to create directory '/run/user/0/snap.foliate/dconf': Permission denied.  dconf will not work properly.

    (com.github.johnfactotum.Foliate:64809): dconf-CRITICAL **: 14:27:42.766: unable to create directory '/run/user/0/snap.foliate/dconf': Permission denied.  dconf will not work properly.

    (com.github.johnfactotum.Foliate:64809): dconf-CRITICAL **: 14:27:42.767: unable to create directory '/run/user/0/snap.foliate/dconf': Permission denied.  dconf will not work properly.

    (com.github.johnfactotum.Foliate:64809): dconf-CRITICAL **: 14:27:42.767: unable to create directory '/run/user/0/snap.foliate/dconf': Permission denied.  dconf will not work properly.

    (com.github.johnfactotum.Foliate:64809): dconf-CRITICAL **: 14:27:42.767: unable to create directory '/run/user/0/snap.foliate/dconf': Permission denied.  dconf will not work properly.
    No protocol specified
    Unable to init server: Could not connect: Connection refused

    (com.github.johnfactotum.Foliate:64809): Gtk-WARNING **: 14:27:42.770: cannot open display: :1


This happened to me when I created another sudo user account and used that account to open my epub books. I'm using Ubuntu and installed foliate using snap.

**Comment by lamping7** [comment] 2021-11-04 19:59
Same problem with version 2.6.3 on Ubuntu 16.04 with the snap @johnfactotum. I tied without success:
```
sudo apt install libcanberra-gtk-module:i386
sudo apt install libcanberra-gtk*
```
