### ISSUE TITLE
[Bug] Click icon can't open Foliate

### ISSUE THREAD

**Issue by signdo** [johnfactotum/foliate#1131] opened 2023-11-15 05:46 UTC
**Describe the bug**

Click icon can't open the Foliate.
But run command `flatpak run com.github.johnfactotum.Foliate` will open it.

**Expected behavior**
Click app icon, then it will be launched.

**Version:**
 - Foliate version: 3.0.0
 - OS/Distribution and version: Debian 12
 - Desktop environment: GNOME 43.6
 - Installation method: Flatpak

**Additional context**
```
$ flatpak run com.github.johnfactotum.Foliate 

(com.github.johnfactotum.Foliate:2): com.github.johnfactotum.Foliate-WARNING **: 13:33:30.444: Gio.IOErrorEnum: Access to service is disallowed 'SERVICE'
getURIFromTracker@resource:///com/github/johnfactotum/Foliate/library.js:30:30
get@resource:///com/github/johnfactotum/Foliate/library.js:56:42
getBookFromIdentifier@resource:///com/github/johnfactotum/Foliate/library.js:105:36
getBook@resource:///com/github/johnfactotum/Foliate/library.js:101:21
activate@resource:///com/github/johnfactotum/Foliate/library.js:394:63
activate@resource:///com/github/johnfactotum/Foliate/library.js:322:18
_init/GLib.MainLoop.prototype.runAsync/</<@resource:///org/gnome/gjs/modules/core/overrides/GLib.js:266:34
  
Failed to create /home/me/.var/app/com.github.johnfactotum.Foliate/cache for shader cache (No such file or directory)---disabling.
Failed to create /home/me/.var/app/com.github.johnfactotum.Foliate/cache for shader cache (No such file or directory)---disabling.
Failed to create /home/me/.var/app/com.github.johnfactotum.Foliate/cache for shader cache (No such file or directory)---disabling.
Failed to create /home/me/.var/app/com.github.johnfactotum.Foliate/cache for shader cache (No such file or directory)---disabling.
Failed to create /home/me/.var/app/com.github.johnfactotum.Foliate/cache for shader cache (No such file or directory)---disabling.
Failed to create /home/me/.var/app/com.github.johnfactotum.Foliate/cache for shader cache (No such file or directory)---disabling.
Failed to create /home/me/.var/app/com.github.johnfactotum.Foliate/cache for shader cache (No such file or directory)---disabling.
Failed to create /home/me/.var/app/com.github.johnfactotum.Foliate/cache for shader cache (No such file or directory)---disabling.

```

**Comment by signdo** [comment] 2023-11-16 05:24
Normally right-click the App icon to display the menu:
![Screenshot from 2023-11-16 13-16-56](https://github.com/johnfactotum/foliate/assets/72440932/0dcc0909-9f24-41be-b8e1-4e9ae7100332)

Foliate:
![Screenshot from 2023-11-16 13-15-45](https://github.com/johnfactotum/foliate/assets/72440932/35ed74b0-be9a-426a-86db-7bba40cacac9)

Click `Unnamed` but nothing happen. Maybe that's why I can't start it?

**Comment by johnfactotum** [comment] 2023-11-17 00:09
No, although that is a bug (which has been fixed in git), with this bug I can still open it fine.

I don't know if there's a better way to troubleshoot this, but you can try and find the .desktop file (see https://discourse.flathub.org/t/where-are-all-the-installed-desktop-files-located-for-each-application/2147) and inspect it to see if there's anything wrong with the way it's launching the app.

**Comment by signdo** [comment] 2023-11-17 11:42
Referring to the article link you sent, I compared the `.desktop` file of other Flatpak app. And then modify the  `/var/lib/flatpak/exports/share/applications/com.github.johnfactotum.Foliate.desktop`.

I re-logged in the desktop after attaching the following content to the file, it is now open normally, and also fixed the bug of right-click displaying `Unnamed` :
```
[Desktop Action new-window]
Name=New Window
Exec=/usr/bin/flatpak run --branch=stable --arch=x86_64 --command=foliate --file-forwarding com.github.johnfactotum.Foliate @@u %U @@
```

**Comment by johnfactotum** [comment] 2023-11-17 17:03
It works for me even with the missing action, though. Are you sure that's what's causing this? Does it fail to launch if you run the unmodified `.desktop` file with `gio launch`?

But I guess the missing desktop action is already removed, so there's nothing that needs to be done anymore, either way.

**Comment by signdo** [comment] 2023-11-18 04:22
I tried to remove the extra lines I had added and re-logged into the desktop. Then click icon to open the Foliate, which results in the same failure as before.
Then run `gio launch /var/lib/flatpak/exports/share/applications/com.github.johnfactotum.Foliate.desktop`. It can be opened.

I suspect that this happens due to the different versions of Flatpak or other related software used. My Flatpak version is 1.14.4 on Debian12.

**Comment by signdo** [comment] 2023-11-18 04:52
Oh, please forgive me for Posting the last comment, now I know the real reason.

[https://specifications.freedesktop.org/desktop-entry-spec/desktop-entry-spec-latest.html#extra-actions](https://specifications.freedesktop.org/desktop-entry-spec/desktop-entry-spec-latest.html#extra-actions)

I noticed the superfluous content `Actions=new-window;` in line 64, which is the presence of which prevents clicking on icon to open the Foliate if not implement it. I deleted it and now I can open the Foliate normally when I re-login.

**Comment by johnfactotum** [comment] 2023-11-18 12:18
OK. Thanks for testing. I guess we can close this as a duplicate of #1111.

**Closed by johnfactotum** 2023-11-18 12:18 UTC
Labels: bug, need info
