### ISSUE TITLE
Foliate doesn't display images for large epub files.

### ISSUE THREAD

**Issue by angelgruevski** [johnfactotum/foliate#219] opened 2019-12-09 15:23 UTC
I have an epub book > 150mb. Foliate doesn't display all images in the book, instead it shows "Image" text.

I haven't encountered this issue with epub books of smaller size.

My PC has more than enough memory (8GB) for displaying the epub book.

**Comment by johnfactotum** [comment] 2019-12-10 02:06
I've tested with a few EPUB files ranging from 120 to 200MB, and they all seem to work fine.

Are there any messages when you open it from the terminal? Can you follow the instructions here: https://github.com/johnfactotum/foliate/wiki#my-book-is-not-displayed-properly, and see if it's an upstream issue?

**Comment by angelgruevski** [comment] 2019-12-10 09:16
Hi John,

I tested the epub using the link above, and the pictures do not display on https://futurepress.github.io/epub.js/examples/input.html too.

**Comment by johnfactotum** [comment] 2019-12-12 03:07
In that case, it is likely an upstream issue. Before opening an issue upstream, can you check if the book works in other e-book readers? Can you view the source of the file and check the `src` of the broken images to see what the problem is?

**Comment by angelgruevski** [comment] 2019-12-12 05:28
The book works in other e-book readers.
Unfortunately, the file is binary and I don't know how to check the source of it.

Below is a screenshot of the issue
![Screenshot from 2019-12-12 06-26-45](https://user-images.githubusercontent.com/57411081/70685081-87675100-1ca8-11ea-9e6d-324ea64af647.png)

**Comment by johnfactotum** [comment] 2019-12-13 01:24
On https://futurepress.github.io/epub.js/examples/input.html, you can right click on the image and choose "inspect element". Also, an EPUB file is a ZIP file, so you can rename the file extension to ".zip" and unzip it.

**Comment by angelgruevski** [comment] 2019-12-13 11:20
Okay, this is what the src of images that are displayed looks like: src="blob:https://futurepress.github.io/938f105f-9b26-4de2-98ae-516cdbff3ac6"

This is the src element for image that doesn't render/display correctly: 
src="pre79-0blob:https://futurepress.github.io/70734d2e-4338-4042-ad08-111f12901543"

In the screenshot below, Img1 is the one that isn't displayed, img2 is the one that is displayed correctly

![Screenshot from 2019-12-13 12-16-31](https://user-images.githubusercontent.com/57411081/70796540-d2fe2580-1da2-11ea-8bc0-4baabcefc9e8.png)

Apologies for not being able to provide too much useful info, I am not familiar with how epub works.

**Comment by johnfactotum** [comment] 2019-12-17 13:42
Hmm. That's odd. The alt text should be displayed if the image cannot be loaded. Does it work if you open the html files in Epiphany or other WebKitGTK based browsers?

**Comment by angelgruevski** [comment] 2019-12-18 05:11
Epiphany works, displays all images.
I tested the issue on another computer (both running Ubuntu 19.10), the issue reproduces on both computers.

**Comment by johnfactotum** [comment] 2020-01-17 08:28
Closing for now. As this appears to be an Epub.js issue, I suggest that you [report this upstream](https://github.com/futurepress/epub.js/issues).

**Closed by johnfactotum** 2020-01-17 08:28 UTC
Labels: bug, need info
