### ISSUE TITLE
The application does not open at all

### ISSUE THREAD

**Issue by miaoerwu** [johnfactotum/foliate#837] opened 2021-12-30 03:13 UTC
**Describe the bug**
Normal click on the application chart to start, no reflection.

**To Reproduce**
1. Go to 'applications'
2. Click on 'app icon'
3. no reflection

**Expected behavior**
Need it to open and run properly.

**Screenshots**
![image](https://user-images.githubusercontent.com/14366467/147718721-a887c3ac-aa31-4fa0-91bd-a051e48ac214.png)
![image](https://user-images.githubusercontent.com/14366467/147718743-4fc481ae-ef8f-4c69-9827-34ee8fb242c5.png)

**Version:**
 - Foliate version: 2.6.3
 - OS/Distribution and version: pop!_os 21.10
 - Desktop environment: GNOME 40
 - Installation method: snap

**Additional context**

**Comment by Philipp0205** [comment] 2021-12-30 07:32
Since today I get the same error.

**Comment by apandada1** [comment] 2022-01-13 14:54
> Just the version from the apt package manager not.

Did you mean, the snap version? Foliate is not available via apt (unless you add the PPA).

**Comment by johnfactotum** [comment] 2023-11-02 05:43
Duplicate of #800

**Closed by johnfactotum** 2023-11-02 05:43 UTC
Labels: bug, snap
