### ISSUE TITLE
Changing Theme Crash

### ISSUE THREAD

**Issue by soundprojects** [johnfactotum/foliate#987] opened 2023-01-27 16:33 UTC
**Describe the bug**
When trying to change the theme through the settings dropdown, Foliate crashes immediately

**To Reproduce**
2. Click on 'Theme'
3. Click Any other theme 
4. Crash

**Expected behavior**
Theme should change

**Version:**
 - Foliate version: 2.6.4
 - OS/Distribution and version: PopOs Latest
 - Installation method: Flatpak

**Additional context**
Tried both Flatpak and PopOs Store versions

**Comment by BabaJi-0** [comment] 2023-02-01 07:43
Duplicate of #719

**Closed** 2023-02-03 05:13 UTC
Labels: bug, duplicate
