### ISSUE TITLE
Content menu "tooltip" render issues. 

### ISSUE THREAD

**Issue by tupubozu** [johnfactotum/foliate#977] opened 2023-01-10 13:12 UTC
**Describe the bug**
Left menu "tooltips" misbehaving. "Tooltip" boxes render under the cursor causing the cursor to be interpreted to be away from the menu item it is hovering over. This in turn leads to the box flickering. 

**To Reproduce**
1. Open any book with a table of contents. 
2. Click on the top left content menu.
3. Move the cursor to any item in the table/list of content. 
4. Let the cursor hover for a bit, and observe the error.  

**Expected behavior**
"Tooltip" boxes not flickering. 

**Screenshots**
Screen capture does not capture the full extent of the error. The textbox flickers regularly on screen. 
[Screencast from 2023-01-10 14-06-17.webm](https://user-images.githubusercontent.com/63042612/211559664-5788a235-1b9e-4b0f-835d-af52b62c14cb.webm)

**Version:**
 - Foliate version: 2.6.4
 - OS/Distribution and version: Fedora 37 Workstation
 - Desktop environment: GNOME 43.2
 - Installation method: Flatpak

**Comment by tupubozu** [comment] 2023-01-10 13:14
The word "tooltip" is used due to a lack of a better word. I do not currently know what there objects are called in GTK

**Comment by johnfactotum** [comment] 2023-01-14 04:09
Duplicate of #746

**Closed by johnfactotum** 2023-01-14 04:09 UTC
Labels: bug
