### ISSUE TITLE
Select text and right click flips to next page

### ISSUE THREAD

**Issue by SeZuo** [johnfactotum/foliate#717] opened 2021-04-23 14:18 UTC
0. Deactivate contextual menu with the "Do nothing" option
1. Select some text
2. Right click anywhere or left-click on text
3. After a small delay, foliate turns to next page

If you wait 5 seconds between step 1 and 2, bug does not occur.

Version 2.6.3 from Archlinux with Gnome 40

**Comment by johnfactotum** [comment] 2021-05-02 15:55
I can't reproduce with right clicking. Right clicking shouldn't do anything. It doesn't handle any right click event, and it will actually show a context menu if you enable developer tools.

As for left clicking, if tap to turn page is enabled, it does go to the prev or next page if you click outside the selection. So I guess that's a bug.

**Comment by SeZuo** [comment] 2021-05-03 13:09
I disabled right click context menu with the "do nothing" option. Also, I don't have dev tools.

Left clicking is a bit random to trigger the bug. I do not have click to turn enabled. Also the bug always sends to next page, never to previous.

**Comment by johnfactotum** [comment] 2021-05-03 13:26
> Also the bug always sends to next page, never to previous.

In paginated mode, if you select text to the end of the current view, it will go to the next page after a delay. This makes it possible to select text across pages. This feature only goes to the next page, not the previous page. So from your description, I would guess that it's a bug of this feature.

It shouldn't happen, though. It will only go to the next page when you're selecting to the end of the page. It also only does so while you're holding down your mouse (i.e. after the delay, it checks if you're still holding down your mouse, and if not, it will do nothing).

The relevant code is here:
https://github.com/johnfactotum/foliate/blob/3f6f00899b90ee4391a4eae481c730930b691bd3/src/web/epub-viewer.js#L815-L825

Maybe you can try deleting this part and see if the problem goes away?

**Comment by SeZuo** [comment] 2021-05-04 19:15
It works !

**Comment by johnfactotum** [comment] 2024-12-05 03:16
Does this still happen in the latest version?

**Comment by SeZuo** [comment] 2024-12-18 17:10
Haven't used Foliate for a while, and it seems you can't turn pages by clicking anywhere anymore ?

How would you turn pages on a touch screen ?

Anyway, I suppose the issue is gone with the feature.

**Comment by johnfactotum** [comment] 2024-12-20 09:58
> How would you turn pages on a touch screen ?

You can do it by swiping.

Anyway, the issue was about right clicking, which wouldn't, or shouldn't, turn pages in the old version, either.

And the bug was apparently fixed after disabling turning pages on *selection*, which is a feature that is still present in the latest version.

> Anyway, I suppose the issue is gone with the feature.

Well, I guess I will close this for now then.

**Closed by johnfactotum** 2024-12-20 09:58 UTC
Labels: bug
