### ISSUE TITLE
Online Wiktionary definitions broken

### ISSUE THREAD

**Issue by AesaraB** [johnfactotum/foliate#1010] opened 2023-03-31 07:52 UTC
When using Foliate (both native Fedora and Flathub version 2.6.4), definition queries result in "no definitions found". sdcv definitions work as expected.

Per the terminal:

```
file:///usr/share/com.github.johnfactotum.Foliate/assets/client.html:35:26: CONSOLE ERROR TypeError: undefined is not an object (evaluating 'results.forEach')
```

No javascript errors are thrown in Foliate's dev console.

**Comment by johnfactotum** [comment] 2023-03-31 09:07
Duplicate of #418

**Closed** 2023-03-31 09:09 UTC
Labels: duplicate
