### ISSUE TITLE
libsoup3 symbols detected followed up by a crash

### ISSUE THREAD

**Issue by kulak** [johnfactotum/foliate#853] opened 2022-01-16 21:06 UTC
**Describe the bug**

I started application from command line and here is its output:

```
JS WARNING: [resource:///com/github/johnfactotum/Foliate/js/main.js 23]: Requiring WebKit2 but it has 2 versions available; use imports.gi.versions to pick one

(com.github.johnfactotum.Foliate:75061): libsoup-ERROR **: 13:00:58.591: libsoup3 symbols detected. Using libsoup2 and libsoup3 in the same process is not supported.
fish: Job 1, 'foliate' terminated by signal SIGTRAP (Trace or breakpoint trap)
```

The application terminated, but I expect it to run.

**Version:**

I am on current ArchLinux. I can't seem to obtain version information from application, but here is package version:

```
community/foliate 2.6.3-1 [installed]
    usr/bin/foliate
```

**Comment by johnfactotum** [comment] 2022-01-17 03:20
Duplicate of #812

**Closed by johnfactotum** 2022-01-17 03:20 UTC
Labels: bug
