### ISSUE TITLE
Dark themes - black letters not legible

### ISSUE THREAD

**Issue by lightonflux** [johnfactotum/foliate#673] opened 2021-02-15 00:28 UTC
**Describe the bug**
If an ebook formats some elements like titles in black, they aren't easy to read. 

**To Reproduce**

1. This ebook: https://zulu-ebooks.com/belletristik/jugend-ohne-gott/pdf/epub
1. Choose theme dark, gruvbox dark or grey
3. Go to a page with title
4.  Confirm that its black

**Expected behavior**

The colour of black letters should be changed to something legible in dark themes. 

**Screenshots**
![Bildschirmfoto von 2021-02-15 01-27-09](https://user-images.githubusercontent.com/1377943/107893701-f5eb1300-6f2c-11eb-94d0-7b2324280a78.png)

**Version:**
 - Foliate version: 2.5.0
 - OS/Distribution and version: Fedora 33
 - Installation method: Flatpak

**Comment by johnfactotum** [comment] 2021-02-17 07:59
Duplicate of #265

**Closed by johnfactotum** 2021-02-17 07:59 UTC
Labels: bug
