### ISSUE TITLE
Page swipe does nothing in RTL manga

### ISSUE THREAD

**Issue by linyaa-kiwi** [johnfactotum/foliate#1291] opened 2024-04-05 20:01 UTC
Page swipe, by either touchscreen or touchpad, does nothing in RTL manga.

**Expected behavior**

In RTL manga, the following works correctly:
- Changing pages with keyboard arrow keys.
- Changing pages with UI slider.
- Changing pages with the arrow buttons at each end of UI slider.

The following does not work. It does absolutely nothing.
- Changing pages with touchscreen swipe.
- Changing pages with touchpad swipe.

**Version:**
 - Foliate version: 3.1.1
 - OS/Distribution and version: Fedora 40
 - Desktop environment: Gnome 46.0
 - Installation method: Installed from source, and installed from Flatpak, both have bug. 

**Additional context**

I love Foliate. Thanks for making a greap app!

I've never debugged a GTK app before, but I can help if you provide a little guidance. For example, how do I insert debug log messages into the javascript and view them?

I began examing the scroll code in epub.js, and how dx/dy and vx/vy are processed, but I became lost without the ability to insert debug messages.

**Comment by johnfactotum** [comment] 2024-04-06 03:04
It's not really possible to do that with the current fixed-layout renderer, which doesn't support offsetting and snapping the page (the `scrollBy()` and `snap()` methods of the paginator). Apart from implementing those, one workaround would be to partially undo d3619e7acdb01e6f3841336b737ec90051905ca0, to get back non-1-to-1 gestures for fixed-layout books.

Technically this is a duplicate of #1225, as all fixed layout books, including PDF, use the same renderer and have the same problem.

**Comment by johnfactotum** [comment] 2024-09-28 06:49
Closing as duplicate of #1225

**Closed as not planned by johnfactotum** 2024-09-28 06:49 UTC
Labels: bug, duplicate
