### ISSUE TITLE
Introduce reading modes

### ISSUE THREAD

**Issue by digitalethics** [johnfactotum/foliate#486] opened 2020-06-23 08:51 UTC
Different reading modes should enable a set of specific defaults optimized for particular use cases regardless of whether these are related to interface, layout ~or even theme~ settings. All these settings can already be enabled but not easily enough. In order to improve usability for different use cases of Foliate, I think it would be great to be able to centrally access and quickly switch between them. Perhaps something like this could be implemented:

- [ ] ~Fullscreen~ Presentation Mode
<sub>Maximizes reading space while keeping interface and layout preferences</sub>

- [ ] Skeuomorphic Mode 
<sub>Imitates realistic shadows and text blocks</sub>

- [ ] Minimalist Mode¹
<sub>Enables a distraction-free reading experience</sub>

- [ ] Research Mode
<sub>Enables sidebar for quick access to annotations, bookmarks and more</sub>

A user should be able to reach them by clicking once on the menu button and then toggle between them via tick boxes (Fullscreen, Skeuomorphic, Minimalist and Research mode). I would also suggest to remove the fullscreen button as it looks out of place in the right corner and the function would be fully replaced by introducing reading mode tick boxes. 

¹The minimalist mode should essentially enable auto-hide header bar and disable sidebar and realistic shadows.

**Comment by johnfactotum** [comment] 2020-06-23 13:13
While this would simply the settings somewhat, one would lose the ability to, for example, have both a sidebar and realistic shadows, or to not use sidebar but sill disable auto-hide headerbar, etc.

In fact, I don't think there's anything that's really inherently exclusive about any of these "modes". The fact that you can't have skeuomorphism/sidebar and auto-hide headerbar together is due to _technical_ restrictions (which can probably be solved with some work); it's not a deliberate design choice.

Furthermore, I would kind of question the need to quickly switch between these modes. I'd expect most users to only settle on one preferred set of settings.

If the user _really_ needs these kind of "mode" switches, I would say that the best approach would be extending "themes" to all settings. That is, when switching a "theme", not only do you switch colors, you also switch all kinds of other things like font, UI, etc.

Alternatively, in some cases the need for frequently changing settings arises from the need to use different "themes"/"modes" for different books. In that case having _per-book_ settings would be the better approach (this is what Evince does).

**Comment by digitalethics** [comment] 2020-06-23 14:23
> While this would simply the settings somewhat, one would lose the ability to, for example, have both a sidebar and realistic shadows, or to not use sidebar but sill disable auto-hide headerbar, etc.

> I don't think there's anything that's really inherently exclusive about any of these "modes".

Introducing _reading modes_ should in fact not remove any of the currently used terminology and options (e.g. introducing a **Research Mode** should not remove the actual switch boxes in the preferences or menu popover to independently enable or disable various other options such as page shadows. These modes are really meant as additional features for frequent use cases or reading experiences. Maybe it would be possible to add customization to these _reading modes_ by allowing to override the defaults in the preferences (with the ability to restore the default settings).

> Furthermore, I would kind of question the need to quickly switch between these modes. I'd expect most users to only settle on one preferred set of settings.

I frequently find myself wanting to change between them, e.g. when sharing my screen (distant education) or giving an actual presentation (university) I'd prefer to have a dedicated **Presentation Mode**. When just doing casual reading I'd opt for a **Minimalist Mode**, and when reading/studying with frequent annotation use, I'd definitely be in **Research Mode**. Reading modes are not only meant to quickly alternate between different "customized reading experiences" but also as a more friendly feature for first-time users to quickly find their individual use cases visually represented without having to first explore the settings.

> Alternatively, in some cases the need for frequently changing settings arises from the need to use different "themes"/"modes" for different books. In that case having per-book settings would be the better approach (this is what Evince does).

This is a good idea too. I imagine this is more related to _themes and fonts_ rather than _interface and layouts_? Maybe this could be part of a **Custom Mode** fetching specific previously-stored per-book theme and font settings when enabled as a dedicated reading mode.

**Comment by johnfactotum** [comment] 2020-06-23 17:15
> Introducing _reading modes_ should in fact not remove any of the currently used terminology and options (e.g. introducing a **Research Mode** should not remove the actual switch boxes in the preferences or menu popover to independently enable or disable various other options such as page shadows.

I don't quite follow. If so then why add the so called " research mode"? Why not just call it "use sidebar"?

> I frequently find myself wanting to change between them, e.g. when sharing my screen (distant education) or giving an actual presentation (university) I'd prefer to have a dedicated **Presentation Mode**. When just doing casual reading I'd opt for a **Minimalist Mode**, and when reading/studying with frequent annotation use, I'd definitely be in **Research Mode**.

Presentation mode is basically just fullscreen? What's the difference?

It kind of feels like it boils down to "a way to quickly enable/disable sidebar".

> Reading modes are not only meant to quickly alternate between different "customized reading experiences" but also as a more friendly feature for first-time users to quickly find their individual use cases visually represented without having to first explore the settings.

If each "mode" is truly a preset for setting a number of different settings, then it might be useful. But each "mode" here is basically just a way to showcase _one_ setting. So having these "modes" basically just doubles the toggles. That will only make things more confusing.

> This is a good idea too. I imagine this is more related to _themes and fonts_ rather than _interface and layouts_?

Book specific sidebar setting can be very useful, for exactly the reason you said you'd need to swtich between research and minimal mode. Window size is another one. Can't really think of much else. I think this further shows that this issue largely boils down to "add a way to quickly enable/disable sidebar".

**Comment by digitalethics** [comment] 2020-06-23 17:42
> If each "mode" is truly a preset for setting a number of different settings, then it might be useful. 

Reading modes are really meant in exactly this sense. 

Regarding the presentation mode, I was looking for a solution to eliminate the fullscreen button which doesn't fit well into the menu popover. Reading modes allow users a new kind of interaction with central Foliate features and the fullscreen button problem would be solved _en passant_. A presentation mode can be qualitatively different from a mere fullscreen mode in that it could display visual anchors in a small window regarding where you are in a presentation (see Okular for example). 

The same applies to a potential research mode which could include displaying much more information (possibly through plugins) that can be made available and that would go way beyond just enabling the sidebar. In other words, I was thinking less in terms of the _current_ Foliate feature set but what _potential_ enhancements could be functionally grouped together and enabled by default under each specific reading mode. Nevertheless, I see lots of benefits to such an arrangement even without many of these features realized yet. In fact, many may only come to the foreground conceptually once the groundwork is laid in terms of what reading modes and experiences _can_ be realized.

**Comment by johnfactotum** [comment] 2020-06-24 03:55
> I was looking for a solution to eliminate the fullscreen button which doesn't fit well into the menu popover

How does it not fit? There's a fullscreen button at the top of the primary menu in Firefox, gedit, Evince, Epiphany. It's pretty much standard.

> Reading modes allow users a new kind of interaction with central Foliate features and the fullscreen button problem would be solved en passant.

But "Fullscreen" is commonly used as a way to remove distraction or to simply increase the size of the window to show more content, and you wouldn't want presentation tools in either of those cases. Any "mode" can be fullscreened or unfullscreened, really. Which means that even if there's a presentation mode, you'd still need to keep a separate fullscreen button no matter what.

> The same applies to a potential research mode which could include displaying much more information (possibly through plugins) that can be made available and that would go way beyond just enabling the sidebar.

I don't think making sweeping changes for hypothetical features is a good idea. What features are those, exactly? And how exactly would they work better with "reading modes" in place?

Most plugins, or any new built-in features, hypothetically speaking, will either be activated through a button in a menu, or they will probably want to display additional widgets either in the sidebar or in some other panel. So again it seems to me that the issue is largely just the need to quickly enable/disable sidebar mode (or to make sidebar mode work with auto-hide header bar).

Also, since you mentioned plugins, "reading modes" can probably itself be a plugin. In fact in many cases it doesn't even need to be a plugin. Since Foliate stores settings with GSettings, changing them is easy even for external tools. For example, supposed there's a plugin called "Presentation Mode" -- this plugin would add a button to the menu that lets you enter the presentation mode. Once activated, it will make the window fullscreen, automatically hide the sidebar, while adding whatever widgets one needs for presentations. When you exit the mode, the plugin undoes everything and you're back to the "normal" mode.

So the questions are:
- What exactly are the issues with the current behavior?
- Will adding "reading modes" actually fix these issues?
- Can these issues be fixed _without_ "reading modes"? If so, how do these alternative designs compare with "reading modes"?

**Comment by johnfactotum** [comment] 2023-11-02 05:53
I believe the core use case has been addressed in the GTK 4 version, as the sidebar can now be easily pinned/unpinned while the headerbar always autohides to maintain a minimal interface.

**Closed** 2023-11-02 05:53 UTC
Labels: enhancement
