### ISSUE TITLE
Please add a option to show all the books at a time, or at least to configure the maximum amount so you don't need to 'increase' the list too many times.

### ISSUE THREAD

**Issue by i30817** [johnfactotum/foliate#783] opened 2021-09-13 19:37 UTC
**Is your feature request related to a problem? Please describe.**
Not a problem but a annoyance of being a visual user and not having the possibility to see the book covers or names by default. When you have thousands of them this is not the most usable way. Changing this is kind of aggressively different because the interface currently doesn't allow selecting a element of the list without immediately loading it and doesn't allow navigation by focus select ( or to show other properties of the book like that ).

**Describe the solution you'd like**
While i understand that the limit is probably on purpose to limit the burden on the system of displaying all those covers, it should be able to be configured.

I'd also like other ways to both navigate to show the name than using the mouse and of actually showing the name by default (maybe with a label that expands on the selected book aft it's able to be selected without actually jumping to reading immediately.

**Describe alternatives you've considered**
Not any at all.

**Additional context**
I had similar features to display covers and names in my old project at https://github.com/i30817/bookjar. It was probably the least broken thing there, even if the actual reading technology was crap.

**Comment by johnfactotum** [comment] 2021-09-15 10:14
Duplicate of #583

**Closed by johnfactotum** 2021-09-15 10:14 UTC
Labels: enhancement
