### ISSUE TITLE
Foliate Flatpak crash closes when selecting a Theme 

### ISSUE THREAD

**Issue by CapeCrusader321** [johnfactotum/foliate#959] opened 2022-10-06 11:02 UTC
**Describe the bug**
I am using Foliate Flatpak, Whenever i open a document and select a theme from the theme option from the options menu foliate flatpak crashes and auto closes, i investigated by running the foliate flatpak through terminal and i have also provided the output

**To Reproduce**
"I Dont know if this a universal problem,but i am mentioning the way the error occurs"
1.Open Foliate.
2. Click on add books, add books etc.
3. Go to the "3" dots and select theme, change the theme to dark etc.
4. See error, the app crashes instantly and closes abruptly 

**Expected behaviour**
I expected Foliate to simply change the theme of document to dark etc.

**Screenshots**
![Screenshot at 2022-10-06 16-21-30](https://user-images.githubusercontent.com/100503303/194296317-2fa348fc-de62-4325-963c-c0ee184884f4.png)

**Version:**
 - Foliate version: 2.6.4(Latest from flatpak)
 - OS/Distribution and version: Parrot OS 5.1
 - Desktop environment: Mate DE 1.24
 - Installation method: Flatpak

**Additional context**
Possible reason for the error-

![Screenshot at 2022-10-06 16-21-30](https://user-images.githubusercontent.com/100503303/194296240-faa8b11b-d17e-4c18-b3cb-052345259bbe.png)

**Comment by johnfactotum** [comment] 2022-10-14 19:50
Duplicate of #719

**Closed by johnfactotum** 2022-10-14 19:50 UTC
Labels: bug
