### ISSUE TITLE
Could not open file.

### ISSUE THREAD

**Issue by NeuHix** [johnfactotum/foliate#992] opened 2023-02-10 01:19 UTC
**Describe the bug**
It happens on an interval of a day or two. I try to open the books that I haven't opened for 2 to 3 days and It says that it cannot open the file.  So I go to nautilus and open the book from there. Then it opens it, and then again for some days, It would open the book directly from Foliate Library . And after some days, It doesn't open that book if I do not open it for some days.
Even if the file is still there in the same directory and I don't rename or change the file's properties in any way.

**To Reproduce**
1. Go to Foliate Library
2. Click on a book that you haven't opened for 2 to 3 days.
3. and this appears:
![image](https://user-images.githubusercontent.com/94163435/217971653-a565eeab-7744-4db3-b375-4cb5f7c27581.png)

**Expected behavior**
Succesfully open the book anytime I try to open it.
(Given that the file hasn't been tampered)

**Screenshots**
Here's what happens:
https://drive.google.com/file/d/1gHOw3ywDkMFgpNLwGSIPyzRyXb_ox_nT/view

**Version:**
 - Foliate version: 2.6.4
 - OS/Distribution and version: Fedora 37 Workstation
 - Desktop environment: GNOME 43.2
 - Installation method: Flatpak

**Additional context**
It's not a serious problem which makes the software 'unusable'. 
To fix it myself, I gave it access to the entire home directory. but even then, it occurs.

**Comment by johnfactotum** [comment] 2023-02-13 03:29
Duplicate of #942

**Closed by johnfactotum** 2023-02-13 03:29 UTC
Labels: bug

**Comment by NeuHix** [comment] 2023-02-14 01:53
Can we give flatpak permission to read&write a particular directory ?

**Comment by NeuHix** [comment] 2023-02-14 01:58
@johnfactotum  Would this work ?
 ```flatpak override --user --filesystem=/home/arctrus/Documents/EBooks com.github.johnfactotum.Foliate```
