### ISSUE TITLE
Themes don't change text color

### ISSUE THREAD

**Issue by retesta** [johnfactotum/foliate#457] opened 2020-06-14 17:38 UTC
Text on **some** .epub and .mobi books will have fixed Black color and won't change with theme (both custom and default themes). On such occasions, text will only change color with Invert theme.

![Screenshot from 2020-06-11 19-05-43](https://user-images.githubusercontent.com/64700989/84599788-2e00fa00-ae64-11ea-977c-3507a570b389.png)
![Screenshot from 2020-06-14 14-29-30](https://user-images.githubusercontent.com/64700989/84599892-e0d15800-ae64-11ea-84d6-eed8ff20242c.png)

**Comment by johnfactotum** [comment] 2020-06-15 04:24
Duplicate of https://github.com/johnfactotum/foliate/issues/265.

Currently the colors aren't set with `!important`, so I guess it would be a good idea to do that. We could try overriding the color even more, but that's not really the best solution. Aggressive overriding makes things more tolerable with badly styled books, but it also breaks other books (and I think in some cases, restrictions of various e-book readers is often what led publishers to ugly hacks in the first place).

In the end, no amount of overrides will ever solve all styling issues. I think the best way is to provide an option to disable _all_ author styles (see https://github.com/johnfactotum/foliate/issues/267).

**Closed** 2020-06-15 10:07 UTC
Labels: duplicate
