### ISSUE TITLE
Vertical text + "scrolled" renders clipped

### ISSUE THREAD

**Issue by cronokirby** [johnfactotum/foliate#168] opened 2019-09-13 23:04 UTC
This stems from trying to render this book: 

https://www.mobileread.com/forums/attachment.php?attachmentid=106819&d=1370779912

This is a Japanese book, in vertical right-to-left format.

In scrolled mode, the output looks like this:

![](https://user-images.githubusercontent.com/22821947/64899235-792d7880-d658-11e9-9e9c-678f967a1673.png)

In single or auto mode, the output looks like this:

![](https://user-images.githubusercontent.com/22821947/64899272-a0844580-d658-11e9-9fd2-af6dd8ed79aa.png)

This might be related to this [upstream issue](https://github.com/futurepress/epub.js/issues/957).

The expected behavior would be the ability to scroll left for this book. At the very least, the text shouldn't be clipped.

**Comment by johnfactotum** [comment] 2019-09-14 05:49
Yes, this is a known issue, and the upstream issue was opened by me. Duplicate of #63 and #166.

**Closed by johnfactotum** 2019-09-14 05:49 UTC
