### ISSUE TITLE
The text at end of chapter is not shown, except for in scroll mode

### ISSUE THREAD

**Issue by mativiters** [johnfactotum/foliate#1284] opened 2024-03-28 21:29 UTC
**Describe the bug**
The text at end of chapters is not shown in side-by-side page mode, though it is shown in single page mode. This is not specific to one instance. It happens, at least, to books I have as epubs downloaded from Project Gutenberg.
I have added a screencast video for further clarification.
[a.webm](https://github.com/johnfactotum/foliate/assets/104627648/45627fa7-4e5f-4f00-8ffa-37b21eb8f9c4)

**Version:**
 - Foliate version: 3.1.0
 - OS/Distribution and version: Arch Linux
 - Desktop environment: GNOME 46
 - Installation method: arch repo binary through pacman

**Comment by johnfactotum** [comment] 2024-03-29 06:37
Duplicate of #1179

**Closed as not planned by johnfactotum** 2024-03-29 06:37 UTC
Labels: bug, duplicate
