### ISSUE TITLE
[Bug] The Library shows only two books

### ISSUE THREAD

**Issue by signdo** [johnfactotum/foliate#1132] opened 2023-11-15 08:11 UTC
**Describe the bug**

When I open the first and second books, they appear correctly in the library. But when I open a third book or more, they are not displayed in the library. This doesn't mean that it not save data about those books that have been read, it just doesn't show up in the library. When I reopen a book that wasn't in the library but was read, it shows me the last page I read.

In addition, when I remove a book from the library and then open a book that I have previously read but did not appear in the library, it still does not appear. This means that only one book in the library is now displayed correctly.

**Expected behavior**

All books that have been read should be displayed in the library.

**Version:**
 - Foliate version: 3.0.0
 - OS/Distribution and version: Debian 12
 - Desktop environment: GNOME 43.6
 - Installation method: Flatpak

**Additional context**

```
$ flatpak run com.github.johnfactotum.Foliate 
Failed to create /home/me/.var/app/com.github.johnfactotum.Foliate/cache for shader cache (No such file or directory)---disabling.
Failed to create /home/me/.var/app/com.github.johnfactotum.Foliate/cache for shader cache (No such file or directory)---disabling.
Failed to create /home/me/.var/app/com.github.johnfactotum.Foliate/cache for shader cache (No such file or directory)---disabling.
Failed to create /home/me/.var/app/com.github.johnfactotum.Foliate/cache for shader cache (No such file or directory)---disabling.
Failed to create /home/me/.var/app/com.github.johnfactotum.Foliate/cache for shader cache (No such file or directory)---disabling.
Failed to create /home/me/.var/app/com.github.johnfactotum.Foliate/cache for shader cache (No such file or directory)---disabling.
Failed to create /home/me/.var/app/com.github.johnfactotum.Foliate/cache for shader cache (No such file or directory)---disabling.
Failed to create /home/me/.var/app/com.github.johnfactotum.Foliate/cache for shader cache (No such file or directory)---disabling.

(com.github.johnfactotum.Foliate:2): com.github.johnfactotum.Foliate-CRITICAL **: 15:49:52.238: The index is not in the allowed range.
setEnd@[native code]
toRange@foliate:///foliate-js/epubcfi.js:308:22
@foliate:///foliate-js/paginator.js:860:21
reader.view.init
Failed to create /home/me/.var/app/com.github.johnfactotum.Foliate/cache for shader cache (No such file or directory)---disabling.
Failed to create /home/me/.var/app/com.github.johnfactotum.Foliate/cache for shader cache (No such file or directory)---disabling.
Failed to create /home/me/.var/app/com.github.johnfactotum.Foliate/cache for shader cache (No such file or directory)---disabling.
Failed to create /home/me/.var/app/com.github.johnfactotum.Foliate/cache for shader cache (No such file or directory)---disabling.
Failed to create /home/me/.var/app/com.github.johnfactotum.Foliate/cache for shader cache (No such file or directory)---disabling.
Failed to create /home/me/.var/app/com.github.johnfactotum.Foliate/cache for shader cache (No such file or directory)---disabling.
Failed to create /home/me/.var/app/com.github.johnfactotum.Foliate/cache for shader cache (No such file or directory)---disabling.
Failed to create /home/me/.var/app/com.github.johnfactotum.Foliate/cache for shader cache (No such file or directory)---disabling.
Failed to create /home/me/.var/app/com.github.johnfactotum.Foliate/cache for shader cache (No such file or directory)---disabling.
Failed to create /home/me/.var/app/com.github.johnfactotum.Foliate/cache for shader cache (No such file or directory)---disabling.
Failed to create /home/me/.var/app/com.github.johnfactotum.Foliate/cache for shader cache (No such file or directory)---disabling.
Failed to create /home/me/.var/app/com.github.johnfactotum.Foliate/cache for shader cache (No such file or directory)---disabling.
Failed to create /home/me/.var/app/com.github.johnfactotum.Foliate/cache for shader cache (No such file or directory)---disabling.
Failed to create /home/me/.var/app/com.github.johnfactotum.Foliate/cache for shader cache (No such file or directory)---disabling.
Failed to create /home/me/.var/app/com.github.johnfactotum.Foliate/cache for shader cache (No such file or directory)---disabling.
Failed to create /home/me/.var/app/com.github.johnfactotum.Foliate/cache for shader cache (No such file or directory)---disabling.

(com.github.johnfactotum.Foliate:2): com.github.johnfactotum.Foliate-CRITICAL **: 15:52:38.382: Argument 1 ('node') to Range.setEnd must be an instance of Node
setEnd@[native code]
toRange@foliate:///foliate-js/epubcfi.js:308:22
@foliate:///foliate-js/paginator.js:860:21
reader.view.init
```

**Comment by johnfactotum** [comment] 2023-11-15 08:15
Probably a duplicate of #435, if I have to guess.

**Comment by signdo** [comment] 2023-11-15 08:29
> Probably a duplicate of #435, if I have to guess.

Emmm, there's a difference.
My library only shows two books at most, and books don't replace showing in the library. But each book that is opened has the same uuid.

**Comment by johnfactotum** [comment] 2023-11-15 08:32
If your books have the same unique ID, then yes, it's the same issue.

> books don't replace showing in the library

Unlike v2.x, in v3.0, covers are not updated when you re-open a book, which I'm guessing is what you're seeing.

**Comment by signdo** [comment] 2023-11-15 08:37
> If your books have the same unique ID, then yes, it's the same issue.
> 
> > books don't replace showing in the library
> 
> Unlike v2.x, in v3.0, covers are not updated when you re-open a book, which I'm guessing is what you're seeing.

Oh yes, you're right! When I opened the book that was the only one in the library, it showed the contents of another book. This is so funny! 😂

**Comment by johnfactotum** [comment] 2023-11-15 08:40
I will close this as <i>duplicate</i>, then.

**Closed by johnfactotum** 2023-11-15 08:40 UTC
Labels: bug, need info
