### ISSUE TITLE
[bug] Math Equations are disproportionately large

### ISSUE THREAD

**Issue by jkotra** [johnfactotum/foliate#255] opened 2020-03-30 11:45 UTC
![Screenshot from 2020-03-30 17-13-05](https://user-images.githubusercontent.com/29590316/77908810-d235c480-72a9-11ea-9863-6f5a82e57b04.png)

Version 1.5.3
Arch Linux Latest - Gnome 3.36

**Comment by johnfactotum** [comment] 2020-03-30 12:27
Duplicate of https://github.com/johnfactotum/foliate/issues/223.

**Closed by johnfactotum** 2020-03-30 12:27 UTC
