### ISSUE TITLE
Wrong size for CSS vw unit

### ISSUE THREAD

**Issue by AliAbdelaal** [johnfactotum/foliate#223] opened 2019-12-29 12:27 UTC
![image](https://user-images.githubusercontent.com/22421898/71556923-2c26b400-2a47-11ea-9cf1-aaa7440a65ff.png)

All equations got rendered in such way, can't view equations at all.

**Comment by johnfactotum** [comment] 2020-01-01 02:23
I think the problem is that the book sets the size of the equations like this:

```css
div[data-type="equation"] math { font-size: calc(0.35em + 1vw); }
```

This works fine in a normal webpage, or in scrolled or continuous mode in Epub.js. However, when in paginated mode, since CSS columns are used to render the pages -- that is, the "pages" are actually columns in one very wide page -- the viewport size, as used by CSS, is many times wider than the window size, causing the equations to be huge.

I don't think there's an easy fix for this. Possible solutions are:
- I guess we can try replacing every use of `vw` with the correct window size. This however doesn't seem very practical, particularly when this needs to be done every time the window is resized.
- Develop an alternative paginated rendition method for Epub.js that preserve the correct viewport size. No idea if that would possible.

As a workaround:
- You can use scrolled layout or continuous layout (the latter is not available in stable releases yet)
- The publisher can remove the use of `vw` sizing; as a user you can edit the book and remove that line. I don't think using `vw` with equations makes much sense, anyway -- even when it works correctly, the equations will be too small on small screens, and too big on large screens.

**Comment by johnfactotum** [comment] 2022-10-16 09:30
Another problem is that in scrolled mode, while `vw` works, `vh` is broken (for horizontal writing). This is because the iframe is actually expanded to fit the whole page in scrolled mode as well (which is useful for overlaying annotations, and also required if you want to do continuous scrolling).

When `vh` is used in scrolled mode, it will often cause the page to grow (or shrink) indefinitely, because you have a loop: the iframe's height depends on the content's height, which depends on the iframe's height, which depends on the content's height...

Probably the best workaround is replacing every instance of `vw` and `vh` in CSS with some reasonably small value, so it will at least look much less broken. Or to initialize the values only once from the window size, but don't update them on resize, so you'll have to reload to update them.

**Closed** 2022-10-25 07:30 UTC
Labels: bug, epub.js
