### ISSUE TITLE
Typo: "Prefernces"

### ISSUE THREAD

**Issue by im4potato** [johnfactotum/foliate#353] opened 2020-05-13 16:26 UTC
If you enable `Use traditional titlebar`, and then go to `Edit` in the menu, `Preferences` is spelled incorrectly.

**Comment by johnfactotum** [comment] 2020-05-13 16:32
Duplicate of https://github.com/johnfactotum/foliate/issues/312.

**Closed** 2020-05-13 16:32 UTC
Labels: duplicate
