### ISSUE TITLE
Search across annotations of different books

### ISSUE THREAD

**Issue by Yaco** [johnfactotum/foliate#588] opened 2020-09-07 00:38 UTC
Hi! thanks for your great app.

Would be possible to search across annotations of different books and not only inside one book annotation?

Adding tags to annotations (like in hyphotesis) and be able to get all of them across all books in the library, would be a great addition.

Thanks!

**Comment by johnfactotum** [comment] 2020-09-07 09:15
Duplicate of #370

**Closed by johnfactotum** 2020-09-07 09:15 UTC
Labels: enhancement
