### ISSUE TITLE
Can't Import Books and Can't open books

### ISSUE THREAD

**Issue by RichCat6** [johnfactotum/foliate#934] opened 2022-09-04 16:15 UTC
**Describe the bug**
I can't import any new eBooks into the software. And I can't open books either.

**To Reproduce**
1. Try to import a new ebook

**Expected behavior**
For the eBook to successfully import.

**Screenshots**

**Version:**
 - Foliate version: 2.6.4
 - OS/Distribution and version: Linux Mint 20.3
 - Desktop environment: MATE 1.26.0
 - Installation method: Deb file

**Additional context**

**Comment by qururoland** [comment] 2022-09-06 10:26
Same problem with the latest .deb either downloaded or installed via PPA. Installing the flatpak version works. Syslog revealed (while still using the deb version):

```
Sep  6 11:15:23 me xdg-desktop-por[4294]: Realtime error: Could not map pid: Could not determine pid namespace: Could not find instance-id in process's /.flatpak-info
Sep  6 11:15:23 me com.github.john[42144]: JS ERROR: Error: Empty Response#012_init/<@resource:///com/github/johnfactotum/Foliate/js/epubView.js:623:57#012_handleAction@resource:///com/github/johnfactotum/Foliate/js/epubView.js:886:22#012_init/<@resource:///com/github/johnfactotum/Foliate/js/epubView.js:617:18#012main@resource:///com/github/johnfactotum/Foliate/js/main.js:478:24#012run@resource:///org/gnome/gjs/modules/script/package.js:206:19#012@/usr/bin/com.github.johnfactotum.Foliate:9:17
Sep  6 11:15:25 me dbus-daemon[1609]: [system] Activating via systemd: service name='org.freedesktop.hostname1' unit='dbus-org.freedesktop.hostname1.service' requested by ':1.215' (uid=1000 pid=42144 comm="/usr/bin/gjs /usr/bin/com.github.johnfactotum.Foli" label="unconfined")
```
So maybe there is a flatpak issue in the deb build! It's been like this since I upgraded to Ubuntu 22.04 and I've finally missed Foliate enough to try to find out why it wasn't working correctly.

**Comment by RichCat6** [comment] 2022-09-07 23:48
> Same problem with the latest .deb either downloaded or installed via PPA. Installing the flatpak version works. Syslog revealed (while still using the deb version):
> 
> ```
> Sep  6 11:15:23 me xdg-desktop-por[4294]: Realtime error: Could not map pid: Could not determine pid namespace: Could not find instance-id in process's /.flatpak-info
> Sep  6 11:15:23 me com.github.john[42144]: JS ERROR: Error: Empty Response#012_init/<@resource:///com/github/johnfactotum/Foliate/js/epubView.js:623:57#012_handleAction@resource:///com/github/johnfactotum/Foliate/js/epubView.js:886:22#012_init/<@resource:///com/github/johnfactotum/Foliate/js/epubView.js:617:18#012main@resource:///com/github/johnfactotum/Foliate/js/main.js:478:24#012run@resource:///org/gnome/gjs/modules/script/package.js:206:19#012@/usr/bin/com.github.johnfactotum.Foliate:9:17
> Sep  6 11:15:25 me dbus-daemon[1609]: [system] Activating via systemd: service name='org.freedesktop.hostname1' unit='dbus-org.freedesktop.hostname1.service' requested by ':1.215' (uid=1000 pid=42144 comm="/usr/bin/gjs /usr/bin/com.github.johnfactotum.Foli" label="unconfined")
> ```
> So maybe there is a flatpak issue in the deb build! It's been like this since I upgraded to Ubuntu 22.04 and I've finally missed Foliate enough to try to find out why it wasn't working correctly.

Thanks. You have a good one.

**Comment by crystallikelaw** [comment] 2022-10-27 02:24
Same issue here. Tried the latest deb file from both the daily build and stable ppa's. Flatpak does work.

Pop_OS 22.04
GNOME 41.4
Versions 2.6.4-1 and 2.6.4-4

**Comment by SylChamber** [comment] 2022-11-12 19:22
Same config as crytstallikelaw: Pop!_OS 22.04 and the `.deb` version. I installed the `deb` because the `flatpak` version didn't work so well, and I prefer `deb`.

* I *can* import most epubs: at least those that I "clean" with Calibre (which I usually do, because I also use Calibre to add metadata downloaded from Amazon, Google or Kobo, and to convert epubs in Kobo's epub version, `kepub`, without which images don't allow zooming on a Kobo reader)
* there is one epub that I *couldn't* import so far: [Terraform Up & Running, 3rd Edition](https://www.terraformupandrunning.com/) from O'Reilly and which I bought directly on Kobo
* I *can* **open** that same book from the file explorer (GNOME's Files). I just can't *import* it, and when I relaunch Foliate, it will fail to open that book. I have to open it again from the file explorer
* with the original epub, the table of contents is *empty*
* but if I convert that book with calibre (I converted it to `kepub` to add metadata), **then I can import it and keep it in my Foliate library**. No error importing, no error opening, and it still works after closing then launching Foliate. And the table of contents works.

That book has messed-up HTML. There are very large tables that go beyond a page's width, and they are truncated on my Kobo ereader. The Kobo app on my phone and Foliate or Thorium are the only way I can read those tables because they allow horizontal scrolling. I have to say that Manning does a really **lot** better job at crafting technical epubs than O'Reilly: no silliness with large tables, they really work mobile-first.

BTW I really miss Foliate on Windows. It's better than Thorium. Kudos.

**Comment by johnfactotum** [comment] 2022-11-13 06:52
This issue should probably be closed. It lacks information and is not actionable. And from the fact that .deb doesn't work but the Flatpak does, and the "Empty response" message, it's probably a duplicate of #878.

@SylChamber Can you open a separate issue? The strangest part is "I just can't _import_ it, and when I relaunch Foliate, it will fail to open that book. I have to open it again from the file explorer". That seems very unlikely to be a problem with the book itself. Especially if you're importing by drag and drop. That would suggest that it's probably a problem with URI handling. One can investigate this by running Foliate with `--verbose`. When opening a book, it will print a line containing `run_javascript: open(`, and the next line will contain the file URI.

**Closed by johnfactotum** 2022-11-13 06:52 UTC
Labels: bug
