### ISSUE TITLE
Please support custom styling for FB2 tags

### ISSUE THREAD

**Issue by natewind** [johnfactotum/foliate#1023] opened 2023-04-29 20:25 UTC
For example, I’d like to center `<title>` and italicize `<cite>`, not to metion picking a custom font for `<code>`. And more generally, FB2 markup is purely semantic, so the styling is supposed to be user-specific.

**Comment by johnfactotum** [comment] 2023-04-30 05:03
Duplicate of #930.

> picking a custom font for `<code>`

This is #222.

**Closed by johnfactotum** 2023-04-30 05:03 UTC
Labels: enhancement

**Comment by natewind** [comment] 2023-04-30 05:11
Maybe at least center titles by default?

**Comment by johnfactotum** [comment] 2023-04-30 05:13
It does in the `gtk4` branch.
