### ISSUE TITLE
Display StarDict content as HTML?

### ISSUE THREAD

**Issue by Moonbase59** [johnfactotum/foliate#839] opened 2021-12-31 18:53 UTC
**Is your feature request related to a problem? Please describe.**
I love the StarDict possibility of Foliate, but usually StarDict content is HTML-encoded. As it is now, dictionary content is displayed as pure text (see screenshot).

**Describe the solution you'd like**
Display StarDict offline dictionary content as HTML, much like the English Wiktionary display.

**Describe alternatives you've considered**
—

**Additional context**

As shown in Foliate, using my Wiktionary StarDict:
![Auswahl_194](https://user-images.githubusercontent.com/3706922/147836018-358c14e7-7d58-447a-8850-c2b72e56834b.png)

Same StarDict, same entry, as shown in GoldenDict:
![Frühstückstisch - GoldenDict_001](https://user-images.githubusercontent.com/3706922/147836098-a894673f-bfb3-4fcf-a9cd-2cf065db3575.png)

**Comment by johnfactotum** [comment] 2022-09-23 19:37
It seems this is a duplicate of #585

**Closed by johnfactotum** 2022-09-23 19:37 UTC
Labels: enhancement
