### ISSUE TITLE
Foliate hangs while opening file

### ISSUE THREAD

**Issue by alazyworkaholic** [johnfactotum/foliate#149] opened 2019-07-24 06:02 UTC
Installed Foliate from source on Ubuntu 18.04. The application starts and doesn't crash or become unresponsive, but it doesn't ever finish loading book. The spinning circle just keeps spinning. I've tried with many different valid epubs. In case it helps, install / runtime terminal output follows below.

`alan at P100 in ~/gits/foliate (master)
$ meson build --prefix=/usr
The Meson build system
Version: 0.45.1
Source dir: /home/alan/gits/foliate
Build dir: /home/alan/gits/foliate/build
Build type: native build
Project name: com.github.johnfactotum.Foliate
Build machine cpu family: x86
Build machine cpu: i686
Program desktop-file-validate found: YES (/usr/bin/desktop-file-validate)
Program appstream-util found: YES (/usr/bin/appstream-util)
Program glib-compile-schemas found: YES (/usr/bin/glib-compile-schemas)
Found pkg-config: /usr/bin/pkg-config (0.29.1)
Native dependency glib-2.0 found: YES 2.56.1
Program gjs found: YES (/usr/bin/gjs)
Configuring com.github.johnfactotum.Foliate using configuration
Program build-aux/meson/postinstall.py found: YES (/home/alan/gits/foliate/build-aux/meson/postinstall.py)
Build targets in project: 7
Found ninja-1.8.2 at /usr/bin/ninja

alan at P100 in ~/gits/foliate (master)
$ ninja -C build
ninja: Entering directory `build'
[3/3] Generating com.github.johnf....xml_merge with a custom command.

alan at P100 in ~/gits/foliate (master)
$ sudo ninja -C build install
ninja: Entering directory `build'
[0/1] Installing files.
Installing subdir /home/alan/gits/foliate/src/assets to /usr/share/com.github.johnfactotum.Foliate/assets
Installing data/com.github.johnfactotum.Foliate.desktop to /usr/share/applications/com.github.johnfactotum.Foliate.desktop
Installing data/com.github.johnfactotum.Foliate.appdata.xml to /usr/share/metainfo/com.github.johnfactotum.Foliate.appdata.xml
Installing src/com.github.johnfactotum.Foliate.src.gresource to /usr/share/com.github.johnfactotum.Foliate/com.github.johnfactotum.Foliate.src.gresource
Installing /home/alan/gits/foliate/data/com.github.johnfactotum.Foliate.gschema.xml to /usr/share/glib-2.0/schemas
Installing /home/alan/gits/foliate/data/com.github.johnfactotum.Foliate.svg to /usr/share/icons/hicolor/scalable/apps
Installing /home/alan/gits/foliate/data/com.github.johnfactotum.Foliate-symbolic.svg to /usr/share/icons/hicolor/symbolic/apps
Installing /home/alan/gits/foliate/build/src/com.github.johnfactotum.Foliate to /usr/bin
Running custom install script '/usr/bin/python3 /usr/bin/meson --internal gettext install --subdir=po --localedir=share/locale --pkgname=com.github.johnfactotum.Foliate'
Installing /home/alan/gits/foliate/build/po/cs_CS.gmo to /usr/share/locale/cs_CS/LC_MESSAGES/com.github.johnfactotum.Foliate.mo
Installing /home/alan/gits/foliate/build/po/fr_FR.gmo to /usr/share/locale/fr_FR/LC_MESSAGES/com.github.johnfactotum.Foliate.mo
Installing /home/alan/gits/foliate/build/po/it.gmo to /usr/share/locale/it/LC_MESSAGES/com.github.johnfactotum.Foliate.mo
Installing /home/alan/gits/foliate/build/po/nl_NL.gmo to /usr/share/locale/nl_NL/LC_MESSAGES/com.github.johnfactotum.Foliate.mo
Installing /home/alan/gits/foliate/build/po/ru_RU.gmo to /usr/share/locale/ru_RU/LC_MESSAGES/com.github.johnfactotum.Foliate.mo
Installing /home/alan/gits/foliate/build/po/zh_TW.gmo to /usr/share/locale/zh_TW/LC_MESSAGES/com.github.johnfactotum.Foliate.mo
Installing /home/alan/gits/foliate/build/po/pt_BR.gmo to /usr/share/locale/pt_BR/LC_MESSAGES/com.github.johnfactotum.Foliate.mo
Installing /home/alan/gits/foliate/build/po/es.gmo to /usr/share/locale/es/LC_MESSAGES/com.github.johnfactotum.Foliate.mo
Installing /home/alan/gits/foliate/build/po/id_ID.gmo to /usr/share/locale/id_ID/LC_MESSAGES/com.github.johnfactotum.Foliate.mo
Running custom install script '/home/alan/gits/foliate/build-aux/meson/postinstall.py'
Updating icon cache...
Updating desktop database...
Compiling GSettings schemas...

alan at P100 in ~/gits/foliate (master)
$ ls -l /usr/bin/Foliate
lrwxrwxrwx 1 root root 40 Jul 23 22:28 /usr/bin/Foliate -> /usr/bin/com.github.johnfactotum.Foliate

alan at P100 in ~/gits/foliate (master)
$ Foliate
Gjs-Message: 22:58:16.688: JS WARNING: [resource:///com/github/johnfactotum/Foliate/js/main.js 72]: test for equality (==) mistyped as assignment (=)?

(com.github.johnfactotum.Foliate:15631): Gjs-WARNING **: 22:58:24.888: JS ERROR: TypeError: jsResult.get_js_value is not a function
scriptGet/<@resource:///com/github/johnfactotum/Foliate/js/main.js:1909:31
main@resource:///com/github/johnfactotum/Foliate/js/main.js:3451:12
run@resource:///org/gnome/gjs/modules/package.js:225:12
@/usr/bin/Foliate:9:1

(com.github.johnfactotum.Foliate:15631): Gjs-WARNING **: 22:59:15.517: Unhandled promise rejection. To suppress this warning, add an error handler to your promise chain with .catch() or a try-catch block around your await expression. Stack trace of the failed promise:
  @resource:///com/github/johnfactotum/Foliate/js/main.js:333:1
  @/usr/bin/Foliate:9:1

(com.github.johnfactotum.Foliate:15631): Gjs-WARNING **: 22:59:15.517: Unhandled promise rejection. To suppress this warning, add an error handler to your promise chain with .catch() or a try-catch block around your await expression. Stack trace of the failed promise:
  @resource:///com/github/johnfactotum/Foliate/js/main.js:327:1
  @/usr/bin/Foliate:9:1
`
The JS ERROR paragraph appears a few seconds after I try to load the book. The next one appears as I close the app.

**Comment by aasril** [comment] 2019-07-24 07:13
I've also just built Foliate on Ubuntu 18.04 but I can load the epub files with no error. Though I built it with meson-0.51.0 and ninja-1.9.0.

**Comment by johnfactotum** [comment] 2019-07-24 07:20
This is very strange:
```
(com.github.johnfactotum.Foliate:15631): Gjs-WARNING **: 22:58:24.888: JS ERROR: TypeError: jsResult.get_js_value is not a function
scriptGet/<@resource:///com/github/johnfactotum/Foliate/js/main.js:1909:31
main@resource:///com/github/johnfactotum/Foliate/js/main.js:3451:12
run@resource:///org/gnome/gjs/modules/package.js:225:12
@/usr/bin/Foliate:9:1
```

I don't think it should ever say `TypeError: jsResult.get_js_value is not a function`. At worst it should be `TypeError: jsResult is null`.

What are your `gjs` and `gir1.2-webkit2-4.0` versions?

**Comment by caioluiz** [comment] 2019-08-14 01:34
Unfortunately, I am also having the same problem. 
I installed the foliate package from the AUR, version 1.53-3 and gjs 1.56.2.
Tried both normal and git packages.

When opening foliate:
```
Gjs-Message: 22:28:52.597: JS WARNING: [resource:///com/github/johnfactotum/Foliate/js/main.js 72]: test for equality (==) mistyped as assignment (=)?

(com.github.johnfactotum.Foliate:24745): Gtk-WARNING **: 22:28:52.638: Theme parsing error: gtk.css:68:35: The style property GtkButton:child-displacement-x is deprecated and shouldn't be used anymore. It will be removed in a future version

(com.github.johnfactotum.Foliate:24745): Gtk-WARNING **: 22:28:52.638: Theme parsing error: gtk.css:69:35: The style property GtkButton:child-displacement-y is deprecated and shouldn't be used anymore. It will be removed in a future version

(com.github.johnfactotum.Foliate:24745): Gtk-WARNING **: 22:28:52.638: Theme parsing error: gtk.css:71:36: The style property GtkCheckMenuItem:indicator-size is deprecated and shouldn't be used anymore. It will be removed in a future version

(com.github.johnfactotum.Foliate:24745): Gtk-WARNING **: 22:28:52.638: Theme parsing error: gtk.css:76:30: The style property GtkExpander:expander-size is deprecated and shouldn't be used anymore. It will be removed in a future version
```

when opening a file:
```(WebKitWebProcess:24780): Gdk-ERROR **: 22:28:56.423: The program 'WebKitWebProcess' received an X Window System error.
This probably reflects a bug in the program.
The error was 'BadValue (integer parameter out of range for operation)'.
  (Details: serial 201 error_code 2 request_code 151 (GLX) minor_code 34)
  (Note to programmers: normally, X errors are reported asynchronously;
   that is, you will receive the error a while after causing it.
   To debug your program, run it with the GDK_SYNCHRONIZE environment
   variable to change this behavior. You can then get a meaningful
   backtrace from your debugger if you break on the gdk_x_error() function.)

(com.github.johnfactotum.Foliate:24745): Gjs-CRITICAL **: 22:28:56.879: JS ERROR: SyntaxError: JSON.parse: unexpected end of data at line 1 column 1 of the JSON data @ resource:///com/github/johnfactotum/Foliate/js/main.js:1839
```

when closing the program:
```(com.github.johnfactotum.Foliate:24745): Gjs-WARNING **: 22:29:49.546: Unhandled promise rejection. To suppress this warning, add an error handler to your promise chain with .catch() or a try-catch block around your await expression. Stack trace of the failed promise:
  @resource:///com/github/johnfactotum/Foliate/js/main.js:237:1
  @/usr/bin/foliate:9:1


(com.github.johnfactotum.Foliate:24745): Gjs-WARNING **: 22:29:49.546: Unhandled promise rejection. To suppress this warning, add an error handler to your promise chain with .catch() or a try-catch block around your await expression. Stack trace of the failed promise:
  @resource:///com/github/johnfactotum/Foliate/js/main.js:236:1
  @/usr/bin/foliate:9:1
```

**Comment by Skydancer9** [comment] 2019-11-06 16:02
Hi, I seem to have a very similar problem. When I open any kind of epub, Foliate just keeps on opening the file but never finishes. I use Manjaro Linux (Arch-based distro). The problem started after the system update (kernel & mesa were also updated). Foliate version: 1.5.3

```
$ inxi -Sxxxc0
System:
  Kernel: 5.3.8-3-MANJARO x86_64 bits: 64 compiler: gcc v: 9.2.0 
  Desktop: Xfce 4.14.1 tk: Gtk 3.24.12 info: xfce4-panel wm: xfwm4 dm: LightDM 1.30.0 
  Distro: Manjaro Linux
```

This is the output from the terminal:
```
$ foliate test.epub 
Gjs-Message: 16:48:05.009: JS WARNING: [resource:///com/github/johnfactotum/Foliate/js/main.js 72]: test for equality (==) mistyped as assignment (=)?

(WebKitWebProcess:4568): Gdk-ERROR **: 16:48:06.147: The program 'WebKitWebProcess' received an X Window System error.
This probably reflects a bug in the program.
The error was 'BadValue (integer parameter out of range for operation)'.
  (Details: serial 185 error_code 2 request_code 152 (GLX) minor_code 34)
  (Note to programmers: normally, X errors are reported asynchronously;
   that is, you will receive the error a while after causing it.
   To debug your program, run it with the GDK_SYNCHRONIZE environment
   variable to change this behavior. You can then get a meaningful
   backtrace from your debugger if you break on the gdk_x_error() function.)

(com.github.johnfactotum.Foliate:4552): Gjs-CRITICAL **: 16:48:06.590: JS ERROR: SyntaxError: JSON.parse: unexpected end of data at line 1 column 1 of the JSON data @ resource:///com/github/johnfactotum/Foliate/js/main.js:1839
```

**Comment by johnfactotum** [comment] 2019-11-06 17:53
@Skydancer9 I found (what is presumably) your thread on the Manjaro forum. Link for reference: https://forum.manjaro.org/t/gdk-errors-after-the-last-update/110278. I'm not sure what's causing this, but it seems that it's not something that I can fix.

It seems that in some cases, the WebKit process may crash, leaving the Gdk error message. If this is the case, I think it will affect all applications that uses WebKitGTK (e.g. GNOME Web or Devhelp).

If, on the other hand, Foliate is simply stuck at the loading screen without any particular messages, it could be that the book is actually successfully loaded, but for some reason the events are not correctly emitted or handled.

**Comment by Skydancer9** [comment] 2019-11-06 19:52
@johnfactotum  thank you for your reply.
Yes, you found my thread. :) I think the problem is not Foliate, because I'm having problems with Calibre as well. Like you said — maybe it's WebKit, but from error logs I suspect it's also related in some way to OpenGL. Anyway, I just wanted to share this issue in case anyone else will experience it. 
I'll probably just wait for the next Manjaro/Arch update to see what happens.

**Comment by niyumard** [comment] 2019-11-09 17:23
I have the same problem:
```                                                                                                                                                                                                    ➜  ~ foliate
(com.github.johnfactotum.Foliate:7664): IBUS-WARNING **: 20:51:05.993: Unable to connect to ibus: Could not connect: Connection refused
CONSOLE ERROR Unhandled Promise Rejection: TypeError: undefined is not an object (evaluating 'cfiOne.path.steps')
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast

(WebKitWebProcess:7749): Gdk-ERROR **: 20:51:06.513: The program 'WebKitWebProcess' received an X Window System error.
This probably reflects a bug in the program.
The error was 'BadValue'.
  (Details: serial 206 error_code 2 request_code 155 (GLX) minor_code 34)
  (Note to programmers: normally, X errors are reported asynchronously;
   that is, you will receive the error a while after causing it.
   To debug your program, run it with the GDK_SYNCHRONIZE environment
   variable to change this behavior. You can then get a meaningful
   backtrace from your debugger if you break on the gdk_x_error() function.)

```
`➜  ~ inxi -Sxxxc0         
System:    Host: X Kernel: 4.15.0-66-generic x86_64 bits: 64 gcc: 7.4.0
           Desktop: i3 4.14.1 info: gnome-shell dm: gdm3 Distro: Ubuntu 18.04.3 LTS
`

**Comment by niyumard** [comment] 2019-11-09 17:29
> I have the same problem:
I fixed the problem by switching to Intel Graphics Card.
Now I get:
`f%                                                                                                                                                                                                                 ➜  ~ foliate
CONSOLE ERROR Unhandled Promise Rejection: TypeError: undefined is not an object (evaluating 'cfiOne.path.steps')
libGL error: MESA-LOADER: failed to retrieve device information
libGL error: Version 4 or later of flush extension not found
libGL error: failed to load driver: i915
libGL error: MESA-LOADER: failed to retrieve device information
file:///snap/foliate/current/usr/share/com.github.johnfactotum.Foliate/assets/epub.js:17390:32: CONSOLE LOG element [object SVGGElement] [object DOMStringMap]
file:///snap/foliate/current/usr/share/com.github.johnfactotum.Foliate/assets/epub.js:17390:32: CONSOLE LOG element [object SVGGElement] [object DOMStringMap]
file:///snap/foliate/current/usr/share/com.github.johnfactotum.Foliate/assets/epub.js:17390:32: CONSOLE LOG element [object SVGGElement] [object DOMStringMap]
file:///snap/foliate/current/usr/share/com.github.johnfactotum.Foliate/assets/epub.js:17390:32: CONSOLE LOG element [object SVGGElement] [object DOMStringMap]
file:///snap/foliate/current/usr/share/com.github.johnfactotum.Foliate/assets/epub.js:17390:32: CONSOLE LOG element [object SVGGElement] [object DOMStringMap]
file:///snap/foliate/current/usr/share/com.github.johnfactotum.Foliate/assets/epub.js:17390:32: CONSOLE LOG element [object SVGGElement] [object DOMStringMap]
file:///snap/foliate/current/usr/share/com.github.johnfactotum.Foliate/assets/epub.js:17390:32: CONSOLE LOG element [object SVGGElement] [object DOMStringMap]
file:///snap/foliate/current/usr/share/com.github.johnfactotum.Foliate/assets/epub.js:17390:32: CONSOLE LOG element [object SVGGElement] [object DOMStringMap]
file:///snap/foliate/current/usr/share/com.github.johnfactotum.Foliate/assets/epub.js:17390:32: CONSOLE LOG element [object SVGGElement] [object DOMStringMap]
file:///snap/foliate/current/usr/share/com.github.johnfactotum.Foliate/assets/epub.js:17390:32: CONSOLE LOG element [object SVGGElement] [object DOMStringMap]
file:///snap/foliate/current/usr/share/com.github.johnfactotum.Foliate/assets/epub.js:17390:32: CONSOLE LOG element [object SVGGElement] [object DOMStringMap]
file:///snap/foliate/current/usr/share/com.github.johnfactotum.Foliate/assets/epub.js:17390:32: CONSOLE LOG element [object SVGGElement] [object DOMStringMap]
file:///snap/foliate/current/usr/share/com.github.johnfactotum.Foliate/assets/epub.js:17390:32: CONSOLE LOG element [object SVGGElement] [object DOMStringMap]
file:///snap/foliate/current/usr/share/com.github.johnfactotum.Foliate/assets/epub.js:17390:32: CONSOLE LOG element [object SVGGElement] [object DOMStringMap]
file:///snap/foliate/current/usr/share/com.github.johnfactotum.Foliate/assets/epub.js:17390:32: CONSOLE LOG element [object SVGGElement] [object DOMStringMap]
file:///snap/foliate/current/usr/share/com.github.johnfactotum.Foliate/assets/epub.js:17390:32: CONSOLE LOG element [object SVGGElement] [object DOMStringMap]
file:///snap/foliate/current/usr/share/com.github.johnfactotum.Foliate/assets/epub.js:17390:32: CONSOLE LOG element [object SVGGElement] [object DOMStringMap]
file:///snap/foliate/current/usr/share/com.github.johnfactotum.Foliate/assets/epub.js:17390:32: CONSOLE LOG element [object SVGGElement] [object DOMStringMap]
file:///snap/foliate/current/usr/share/com.github.johnfactotum.Foliate/assets/epub.js:17390:32: CONSOLE LOG element [object SVGGElement] [object DOMStringMap]
file:///snap/foliate/current/usr/share/com.github.johnfactotum.Foliate/assets/epub.js:17390:32: CONSOLE LOG element [object SVGGElement] [object DOMStringMap]
file:///snap/foliate/current/usr/share/com.github.johnfactotum.Foliate/assets/epub.js:17390:32: CONSOLE LOG element [object SVGGElement] [object DOMStringMap]
file:///snap/foliate/current/usr/share/com.github.johnfactotum.Foliate/assets/epub.js:17390:32: CONSOLE LOG element [object SVGGElement] [object DOMStringMap]
file:///snap/foliate/current/usr/share/com.github.johnfactotum.Foliate/assets/epub.js:17390:32: CONSOLE LOG element [object SVGGElement] [object DOMStringMap]
file:///snap/foliate/current/usr/share/com.github.johnfactotum.Foliate/assets/epub.js:17390:32: CONSOLE LOG element [object SVGGElement] [object DOMStringMap]
file:///snap/foliate/current/usr/share/com.github.johnfactotum.Foliate/assets/epub.js:17390:32: CONSOLE LOG element [object SVGGElement] [object DOMStringMap]
file:///snap/foliate/current/usr/share/com.github.johnfactotum.Foliate/assets/epub.js:17390:32: CONSOLE LOG element [object SVGGElement] [object DOMStringMap]
file:///snap/foliate/current/usr/share/com.github.johnfactotum.Foliate/assets/epub.js:17390:32: CONSOLE LOG element [object SVGGElement] [object DOMStringMap]
file:///snap/foliate/current/usr/share/com.github.johnfactotum.Foliate/assets/epub.js:17390:32: CONSOLE LOG element [object SVGGElement] [object DOMStringMap]
file:///snap/foliate/current/usr/share/com.github.johnfactotum.Foliate/assets/epub.js:17390:32: CONSOLE LOG element [object SVGGElement] [object DOMStringMap]
file:///snap/foliate/current/usr/share/com.github.johnfactotum.Foliate/assets/epub.js:17390:32: CONSOLE LOG element [object SVGGElement] [object DOMStringMap]
file:///snap/foliate/current/usr/share/com.github.johnfactotum.Foliate/assets/epub.js:17390:32: CONSOLE LOG element [object SVGGElement] [object DOMStringMap]
file:///snap/foliate/current/usr/share/com.github.johnfactotum.Foliate/assets/epub.js:17390:32: CONSOLE LOG element [object SVGGElement] [object DOMStringMap]
file:///snap/foliate/current/usr/share/com.github.johnfactotum.Foliate/assets/epub.js:17390:32: CONSOLE LOG element [object SVGGElement] [object DOMStringMap]
file:///snap/foliate/current/usr/share/com.github.johnfactotum.Foliate/assets/epub.js:17390:32: CONSOLE LOG element [object SVGGElement] [object DOMStringMap]
file:///snap/foliate/current/usr/share/com.github.johnfactotum.Foliate/assets/epub.js:17390:32: CONSOLE LOG element [object SVGGElement] [object DOMStringMap]
file:///snap/foliate/current/usr/share/com.github.johnfactotum.Foliate/assets/epub.js:17390:32: CONSOLE LOG element [object SVGGElement] [object DOMStringMap]
file:///snap/foliate/current/usr/share/com.github.johnfactotum.Foliate/assets/epub.js:17390:32: CONSOLE LOG element [object SVGGElement] [object DOMStringMap]
file:///snap/foliate/current/usr/share/com.github.johnfactotum.Foliate/assets/epub.js:17390:32: CONSOLE LOG element [object SVGGElement] [object DOMStringMap]
file:///snap/foliate/current/usr/share/com.github.johnfactotum.Foliate/assets/epub.js:17390:32: CONSOLE LOG element [object SVGGElement] [object DOMStringMap]
file:///snap/foliate/current/usr/share/com.github.johnfactotum.Foliate/assets/epub.js:17390:32: CONSOLE LOG element [object SVGGElement] [object DOMStringMap]
file:///snap/foliate/current/usr/share/com.github.johnfactotum.Foliate/assets/epub.js:17390:32: CONSOLE LOG element [object SVGGElement] [object DOMStringMap]
file:///snap/foliate/current/usr/share/com.github.johnfactotum.Foliate/assets/epub.js:17390:32: CONSOLE LOG element [object SVGGElement] [object DOMStringMap]
file:///snap/foliate/current/usr/share/com.github.johnfactotum.Foliate/assets/epub.js:17390:32: CONSOLE LOG element [object SVGGElement] [object DOMStringMap]
file:///snap/foliate/current/usr/share/com.github.johnfactotum.Foliate/assets/epub.js:17390:32: CONSOLE LOG element [object SVGGElement] [object DOMStringMap]
file:///snap/foliate/current/usr/share/com.github.johnfactotum.Foliate/assets/epub.js:17390:32: CONSOLE LOG element [object SVGGElement] [object DOMStringMap]
file:///snap/foliate/current/usr/share/com.github.johnfactotum.Foliate/assets/epub.js:17390:32: CONSOLE LOG element [object SVGGElement] [object DOMStringMap]
file:///snap/foliate/current/usr/share/com.github.johnfactotum.Foliate/assets/epub.js:17390:32: CONSOLE LOG element [object SVGGElement] [object DOMStringMap]
file:///snap/foliate/current/usr/share/com.github.johnfactotum.Foliate/assets/epub.js:17390:32: CONSOLE LOG element [object SVGGElement] [object DOMStringMap]
file:///snap/foliate/current/usr/share/com.github.johnfactotum.Foliate/assets/epub.js:17390:32: CONSOLE LOG element [object SVGGElement] [object DOMStringMap]
file:///snap/foliate/current/usr/share/com.github.johnfactotum.Foliate/assets/epub.js:17390:32: CONSOLE LOG element [object SVGGElement] [object DOMStringMap]
file:///snap/foliate/current/usr/share/com.github.johnfactotum.Foliate/assets/epub.js:17390:32: CONSOLE LOG element [object SVGGElement] [object DOMStringMap]
file:///snap/foliate/current/usr/share/com.github.johnfactotum.Foliate/assets/epub.js:17390:32: CONSOLE LOG element [object SVGGElement] [object DOMStringMap]
Gjs-Message: 20:57:15.942: JS WARNING: [resource:///com/github/johnfactotum/Foliate/js/main.js 2135]: reference to undefined property "atStart"
`

Nonetheless I can read the book and use Foliate.

**Comment by galgalesh** [comment] 2020-02-10 21:40
I have the same issue on my computer which has an Nvidia GPU. Both on the snap and the deb version of Foliate and both on the master and 1.x branch.

**Comment by galgalesh** [comment] 2020-02-10 22:46
@niyumard 

Your issue was caused by a bug in the snap package. It should be fixed now; if you refresh the snap `snap refresh foliate --channel stable` it should work both with nvidia and intel gpu.

**Comment by galgalesh** [comment] 2020-04-05 14:16
@johnfactotum  I'm guessing you can close this issue now. The issue with the snap package is fixed now. The other people seemed to be having issues with the build from source. This is not needed anymore on Ubuntu and Manjaro since they ship snap support by default.

**If anyone is still having this issue with the 2.0.0 version, please let us know.**

**Comment by johnfactotum** [comment] 2020-04-07 04:01
Closing this for now. If anyone has any further problems, feel free to comment or open a new issue.

**Closed by johnfactotum** 2020-04-07 04:01 UTC
Labels: bug, works for me

**Comment by sameersharma84** [comment] 2022-10-18 00:24
> I was having the same problem, but using the foliate package from the AUR, version 1.53-3 and gjs 1.56.2. This behavior started after a system upgrade, including kernel and nvidia drivers. After doing a full reboot, the problem was solved for me.

This worked for me too. I had installed it from AUR using `sudo pacman -Syu foliate`. Faced the same issue but restart fixed it. Thanks!
