### ISSUE TITLE
Foliate hangs when loading file on Kubunti 24.04

### ISSUE THREAD

**Issue by vhrabar** [johnfactotum/foliate#1309] opened 2024-04-27 21:58 UTC
**Describe the bug**
On K24.04 Foliate is currently incapable of loading any EPUB or PDF files as it hangs during the loading process, without crashing or becoming unresponsive with the following log:
```
(com.github.johnfactotum.Foliate:2): Gtk-WARNING **: 23:44:43.067: Locale not supported by C library.
        Using the fallback 'C' locale.
flatpak-spawn: Invalid byte sequence in conversion input
Try "flatpak-spawn --help" for more information.

(com.github.johnfactotum.Foliate:2): com.github.johnfactotum.Foliate-CRITICAL **: 23:44:44.042: My name is Oh-No-WebKit-Crashed, bug of bugs!

(com.github.johnfactotum.Foliate:2): com.github.johnfactotum.Foliate-CRITICAL **: 23:44:44.042: Look on this line, Developer -- despair!
```

**Screenshots**
![image](https://github.com/johnfactotum/foliate/assets/97047523/a72d9e3b-5e29-4c70-ad5c-3e38d144422a)

**Version:**
 - Foliate version: 3.1.1
 - OS/Distribution and version: Kubuntu 24.04
 - Desktop environment: KDE Plasma 5.27.11
 - Installation method: Flatpak

**Comment by johnfactotum** [comment] 2024-05-01 11:18
Duplicate of #1169

**Closed as not planned by johnfactotum** 2024-05-01 11:18 UTC
Labels: bug, duplicate
