### ISSUE TITLE
TTS causes document to scroll to end without speech

### ISSUE THREAD

**Issue by squeaksvolvo** [johnfactotum/foliate#765] opened 2021-07-29 01:29 UTC
After configuring preferences for TTS, Festival or Other, using TTS would cause the document to scroll to the bottom without speaking.

After successfully testing the configuration to speak "The North Wind and ...", and closing the preferences window, then using the f5 key or headphone icon, the document scrolls to the bottom. This happens for the festival or Other but espeak-ng works as expected.

**Version:**
 - Foliate version: 2.6.3
 - OS/Distribution and version: Manjaro 21.1.0
 - Desktop environment: xfce 4.16
 - Installation method: Pamac community repository

**Additional context**
After closing and restarting foliate, the issue went away.

**Comment by johnfactotum** [comment] 2021-08-17 04:19
>  After closing and restarting foliate, the issue went away.

Can you still reproduce the issue now?

**Comment by DavidBonelo** [comment] 2021-10-01 02:32
I had the same issue when I configured the tts to Festival
*closing and restarting foliate solved the issue for me too.*
> Can you still reproduce the issue now?

Yes, if I change the tss to eSpeakNG and then to Festival again.

**Comment by KristijanZic** [comment] 2021-12-04 17:59
I can reproduce the issue. I've installed it via flathub on Ubuntu 20.10. 
Just open any epub and click the play TTS button and it will jump from chapter to chapter from top to bottom.
For mobi files the play TTS button just doesn't work.

I can't reproduce any of those issues on a snap version of the app. It works fine there.

**Comment by johnfactotum** [comment] 2023-12-05 17:11
Closing as TTS uses speech-dispatcher now. Feel free to open new issues for problems with the new version.

**Closed by johnfactotum** 2023-12-05 17:11 UTC
Labels: bug, need info
