### ISSUE TITLE
Foliate fails to open valid fb2 book: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by van-de-bugger** [johnfactotum/foliate#1053] opened 2023-07-02 23:28 UTC
**Describe the bug**

Foliate fails to open a valid FB2 book.

**To Reproduce**

```
$ cat <<'EOF' > test.fb2
<?xml version="1.0" encoding="UTF-8"?>
<FictionBook xmlns="http://www.gribuser.ru/xml/fictionbook/2.0" xmlns:l="http://www.w3.org/1999/xlink">
    <description>
        <title-info>
            <genre>home_crafts</genre>
            <author>
                <first-name>First</first-name>
                <last-name>Last</last-name>
            </author>
            <book-title>Title</book-title>
            <lang>en</lang>
        </title-info>
        <document-info>
            <author>
                <first-name>Anonymous</first-name>
                <last-name/>
            </author>
            <date value="2000-01-01">2000-01-01</date>
            <id>55555555-5555-5555-5555-555555555555</id>
            <version>1.0</version>
        </document-info>
    </description>
    <body>
        <title><p>Title</p></title>
        <section>
            <title><p>Chapter I</p></title>
            <section id="Reef">
                <title><p>Reef</p></title>
                <p>Text</p>
            </section>
            <section>
                <title><p>Another</p></title>
                <p><a l:href="#Reef">reef</a> text.</p>
            </section>
        </section>
    </body>
</FictionBook>
EOF

$ com.github.johnfactotum.Foliate ./test.fb2 
(com.github.johnfactotum.Foliate:976658): Gjs-WARNING **: 02:10:17.852: JS ERROR: Error: Maximum call stack size exceeded.
_init/<@resource:///com/github/johnfactotum/Foliate/js/epubView.js:623:57
_handleAction@resource:///com/github/johnfactotum/Foliate/js/epubView.js:886:22
_init/<@resource:///com/github/johnfactotum/Foliate/js/epubView.js:617:18
main@resource:///com/github/johnfactotum/Foliate/js/main.js:478:24
run@resource:///org/gnome/gjs/modules/script/package.js:206:19
@/usr/bin/com.github.johnfactotum.Foliate:9:17
```

Foliate shows the main window, but it contains error message

>  Could not open file
    Maximum call stack size exceeded

and button "Open Another File...".

**Expected behavior**

Foliate opens the book.

**Version:**
 - Foliate version: foliate-2.6.4-6.fc38.noarch
 - OS/Distribution and version: Fedora 38.
 - Desktop environment: GNOME 44.1
 - Installation method: rpm

**Additional context**

I have checked the `test.fb2` with `xmllint` program:

```
$ xmllint --noout --schema FictionBook-2.0.xsd test.fb2
test.fb2 validates
```

`test.fb2` is valid.

**Comment by johnfactotum** [comment] 2023-07-03 11:34
Duplicate of #935

**Closed by johnfactotum** 2023-07-03 11:34 UTC
Labels: bug
