### ISSUE TITLE
Foliate doesn't open books on Fedora 36

### ISSUE THREAD

**Issue by lhirlimann** [johnfactotum/foliate#885] opened 2022-04-12 13:48 UTC
**Describe the bug**

can't read any .epub on fedora 36.

**To Reproduce**

/usr/bin/gjs /usr/bin/com.github.johnfactotum.Foliate '/home/ludovic/Documents/books/La stratégie de la pucelle.epub'

**Expected behavior**
I can read the books

**Screenshots**
![image](https://user-images.githubusercontent.com/415751/162976841-4ba1d204-0915-485d-8ac2-f249305adbdd.png)

**Version:**
 - Foliate version: 2.6.4
 - OS/Distribution and version: Fedora 36
 - Desktop environment: Gnome 42
 - Installation method: rpm

**Additional context**

```
(com.github.johnfactotum.Foliate:92133): Gjs-WARNING **: 13:56:15.353: JS ERROR: Error: Empty Response
_init/<@resource:///com/github/johnfactotum/Foliate/js/epubView.js:623:57
_handleAction@resource:///com/github/johnfactotum/Foliate/js/epubView.js:886:22
_init/<@resource:///com/github/johnfactotum/Foliate/js/epubView.js:617:18
main@resource:///com/github/johnfactotum/Foliate/js/main.js:478:24
run@resource:///org/gnome/gjs/modules/script/package.js:206:19
@/usr/bin/com.github.johnfactotum.Foliate:9:17
```

**Comment by johnfactotum** [comment] 2022-04-12 15:57
Probably a duplicate of #878

**Comment by lhirlimann** [comment] 2022-04-13 08:23
confirming : glib2-2.72.0-2.fc36.x86_64

**Closed** 2022-04-13 14:32 UTC
Labels: bug, duplicate
