### ISSUE TITLE
Selection-scrolling within CODE doesn't work

### ISSUE THREAD

**Issue by eksperimental** [johnfactotum/foliate#543] opened 2020-07-27 00:46 UTC
**Describe the bug**
There is code that extends further than the height of the screen, and it is imposible to selecting it by clicking and dragging/scrolling.

**To Reproduce**
1. find programming code that it extends for more than the height of the screen.
2. click, and drag the coursor.
3. you will see it only gets selected up to the top of the screen.  

**Expected behavior**
to select-scroll as when you do it out of the code 

**Version:**
 - Foliate version: 2.2.1
 - OS/Distribution and version: linux
 - Installation method: built from sources

**Comment by johnfactotum** [comment] 2020-08-28 06:07
I can't reproduce this. Can you provide a screen recording or an example file?

**Comment by johnfactotum** [comment] 2021-06-30 05:16
Closing due to lack of information and activity. Feel free to comment or open a new issue if anyone has any further information.

**Comment by eksperimental** [comment] 2021-06-30 13:17
Sorry I haven't had the time to do a screen recording. I will reopen the issue once I mange to do this.

**Comment by johnfactotum** [comment] 2021-06-30 15:01
It would also be helpful to see whether it's an upstream issue: https://github.com/johnfactotum/foliate/wiki#my-book-is-not-displayed-properly

**Closed** 2023-03-15 12:12 UTC
Labels: bug, need info
