### ISSUE TITLE
UX: "turn page on tap" vs linux phones horizontal displays

### ISSUE THREAD

**Issue by okias** [johnfactotum/foliate#731] opened 2021-05-17 16:00 UTC
While on computer, there is usually lot space around text, on mobile device (e.g. 720x1440; 2000x3000) is very tiny space around text.

When double tapping words closer to screen border (for translations/dictionary) it triggers the page turn.
Generally I believe, one of solutions could be that on these layout, "turn page on tap" could be adjusted to only small border of screen.

Alternative solution could be disabling "turn page on tap" (by default) and letting users just swipe.

HW: OnePlus 6T
- LCD: 6.41 inches, 100.9 cm2 (~85.6% screen-to-body ratio)
- Resolution: 1080 x 2340 pixels, 19.5:9 ratio (~402 ppi density)

SW: Mobian Linux, Phosh/GNOME environment

**Comment by johnfactotum** [comment] 2021-05-18 03:08
Yeah, I think turning it off by default would probably be better (see #379).

Even with "turn page on tap" enabled, double clicking should still work, though. Single clicks are only triggered after a delay to check for double clicks.

**Comment by johnfactotum** [comment] 2021-06-30 04:33
Closing as a duplicate of #379.

**Closed by johnfactotum** 2021-06-30 04:33 UTC
Labels: bug
