### ISSUE TITLE
Improve the usability of Preferences dialog

### ISSUE THREAD

**Issue by gitkeerthi** [johnfactotum/foliate#904] opened 2022-05-26 15:51 UTC
**Is your feature request related to a problem? Please describe.**
When the preference dialog is open and you roll your mouse wheel you may inadvertently change a drop down's selected option if the cursor is over the drop down. Worse yet ,the changes are saved instantly and there is no way for the user to know he made an inadvertent change.

**Describe the solution you'd like**
Provide a Save or Apply button so inadvertent changes can be avoided

**Describe alternatives you've considered**
No idea

**Additional context**
None

**Comment by johnfactotum** [comment] 2022-05-27 05:43
Duplicate of #625

**Closed by johnfactotum** 2022-05-27 05:43 UTC
Labels: enhancement
