### ISSUE TITLE
Unable to Open Ebook

### ISSUE THREAD

**Issue by anathonous** [johnfactotum/foliate#835] opened 2021-12-26 01:14 UTC
Library loads fine. When trying to open Ebook I get spinning wheel.

Running Gentoo Current.

**Comment by johnfactotum** [comment] 2021-12-26 05:24
Please provide more information. Also see https://github.com/johnfactotum/foliate/issues/707#issuecomment-817575114.

**Comment by anathonous** [comment] 2021-12-26 05:45
Seems like common issue. 
Linux Observable 5.10.86-gentoo-x86_64 #1 SMP PREEMPT Sat Dec 18 21:01:52 CST 2021 x86_64 Intel(R) Xeon(R) CPU X5560 @ 2.80GHz GenuineIntel GNU/Linux
Using ~amd64 gentoo current

**Comment by rwperrott** [comment] 2022-11-08 03:38
I'm also getting a forever spinner in Foliate 2.64 (deb) for some books (most seem fine), which were validated by Sigil 1.9.20 and open fine in Xreader 3.4.5.
Linux Mint 21 MATE 64-bit

**Comment by johnfactotum** [comment] 2023-03-11 11:06
I'm going to close this since there's not a lot to go on here. It's probably a duplicate of some other endless spinner issue and likely fixed in the GTK 4 version. But feel free to comment or open a new issue if anyone has anything further to add.

**Closed by johnfactotum** 2023-03-11 11:06 UTC
Labels: bug, need info
