### ISSUE TITLE
"Trasnslate" popup does not close upon selecting any language

### ISSUE THREAD

**Issue by allco** [johnfactotum/foliate#1306] opened 2024-04-25 08:28 UTC
**Describe the bug**
"Trasnslate" popup does not close upon selecting any language

**To Reproduce**
1. Go to any book of EPUB
2. Select any word
3. Right click -> "Translate"
4. Change language in the popup
5.  Try to close the popup

**Expected behavior**
"Translate" popup closes upon Esc button or removing focus from it or so

**Actual behavior**
No way to close the popup. Esc does not close it same as clicking somewhere outside of the popup.

**Screenshots**
![image](https://github.com/johnfactotum/foliate/assets/15078991/30cb571c-7528-4400-aaca-3b917ca1e871)

**Version:**
 - Foliate version: 3.1.1
 - OS/Distribution and version: Fedora 39
 - Desktop environment: Gnome 45.5 on Wayland
 - Installation method:  Fedora packages

**Comment by johnfactotum** [comment] 2024-04-26 02:18
Duplicate of #1270.

When using GNOME one can work around this by clicking on the top bar. Not sure about other DEs.

**Closed as not planned by johnfactotum** 2024-04-26 02:18 UTC
Labels: bug, duplicate
