### ISSUE TITLE
Stack trace error thrown. Gjs-WARNING **: 03:12:44.385: Unhandled promise rejection.

### ISSUE THREAD

**Issue by shirishag75** [johnfactotum/foliate#1026] opened 2023-05-04 21:56 UTC
**Gjs-WARNING **: 03:12:44.385: Unhandled promise rejection.**

Got the following - 

```
$ foliate 100\ Books\ that\ Changed\ the\ Worlds.epub 

(com.github.johnfactotum.Foliate:1282537): Gjs-WARNING **: 03:12:44.385: Unhandled promise rejection. To suppress this warning, add an error handler to your promise chain with .catch() or a try-catch block around your await expression. Stack trace of the failed promise:
  main@resource:///com/github/johnfactotum/Foliate/js/main.js:478:24
  run@resource:///org/gnome/gjs/modules/script/package.js:206:19
  @/usr/bin/foliate:9:17
```

**To Reproduce**

**Expected behavior**
Basically the above should not be seen. 

**Screenshots**

**Version:**
 - Foliate version: 2.6.4 It actually is 2.6.4-1+dfsg3 in Debian repo. 
 - Debian testing. 
 - Mate 1.26.0
 - Installation method: From Debian repository. 

**Additional context**

**Comment by nublado-language-exchange** [comment] 2023-05-05 01:49
I had the same problem in Xubuntu 22.04 after doing a system upgrade. When trying to open an epub, I got that message and the GUI would go blank.

I just went to menu > Book > Reload, and it started working again.

**Comment by zjuyk** [comment] 2023-06-04 12:33
Same error, here is my system info.

- Foliate version: 2.6.4-2
- Arch Linux
- Plasma 5.27.5
- Installation method: From Arch Linux extra repository

**Comment by johnfactotum** [comment] 2023-06-25 08:11
Duplicate of #691, I think.

**Closed by johnfactotum** 2023-06-25 08:11 UTC
Labels: bug
