### ISSUE TITLE
[Feature request] Make a library package for IOS and Android

### ISSUE THREAD

**Issue by mrifni** [johnfactotum/foliate#556] opened 2020-08-16 05:55 UTC
It would be a nice feature to make a library package for android and IOS, Ipad devices. So app developers can use this package for their mobile apps.
At the moment there is folioreader but its not maintained anymore.

**Comment by apandada1** [comment] 2020-08-23 19:22
Foliate uses the library [epub.js](https://github.com/futurepress/epub.js/) in the backend, and uses [gjs](https://wiki.gnome.org/Attic/Gjs) to run, which is not available in Android/iOS AFAIK.
Foliate itself is not a library, but another app which uses epub.js

@mrifni  Kindly close the issue because it is not very related to Foliate as a GNU/Linux software. Instead, open an issue with epub.js if you need face a problem while building a mobile app with that library. Also, this is a duplicate of https://github.com/johnfactotum/foliate/issues/522, which was also opened by you. Please don't create duplicate issues.

**Closed** 2020-08-24 07:23 UTC
Labels: enhancement
