### ISSUE TITLE
[Feature Request] Support for Epubs with Vertical Text

### ISSUE THREAD

**Issue by Nutjob** [johnfactotum/foliate#63] opened 2019-06-12 20:29 UTC
This app is my current favourite app for reading epubs, unfortunately it does not display correctly vertical text, which is used in japanese and chinese books.
The characters cover only the small upper part of the page, the chapter selection and the scrolling seems not working at all.
Since the ebook reader in Calibre does not support this, I would really be grateful for this feature.

[Here's a link to an ebook for doing some test](https://www.mobileread.com/forums/showthread.php?t=215310)

**Comment by johnfactotum** [comment] 2019-06-13 01:53
Thanks for opening this issue.

I did notice this. What's troubling is that it seems to work fine with Epub.js, or the version used in their example, anyway. I thought it might be a regression in later versions of Epub.js, but I don't really know. Will look into it.

**Comment by johnfactotum** [comment] 2019-06-13 02:15
Okay, it's not a version problem. The problem is that I've been testing Epub.js in Firefox, and vertical text works fine there (and also works in Chromium). But it doesn't work with WebKit, which is what's used in Foliate.

**Comment by johnfactotum** [comment] 2019-07-08 14:26
I've opened an issue upstream: https://github.com/futurepress/epub.js/issues/957

**Comment by Nutjob** [comment] 2019-07-08 22:30
Thank you. Let's hope this issue can be fixed.

**Comment by johnfactotum** [comment] 2019-07-14 11:47
I will close this now as this will have to be fixed upstream.

**Closed by johnfactotum** 2019-07-14 11:47 UTC
Labels: epub.js
