### ISSUE TITLE
Size influences position

### ISSUE THREAD

**Issue by schmolch** [johnfactotum/foliate#557] opened 2020-08-16 12:17 UTC
By changing the space available for the text through changes in window size, text size or enabling / disabling the sidebar the position in the book changes, which is mildly confusing.

It would be preferable to remain at the same page.

**Comment by johnfactotum** [comment] 2020-08-28 06:01
Duplicate of #152 

Should already be fixed in 2.2.0 and later.

**Closed by johnfactotum** 2020-08-28 06:01 UTC
