### ISSUE TITLE
Failed to spawn webkitgtk process

### ISSUE THREAD

**Issue by Divelix** [johnfactotum/foliate#1368] opened 2024-07-29 10:17 UTC
I just installed foliate via snap on Ubuntu 22.04 and tried to open EPUB file with it. It throws this error:
```
(com.github.johnfactotum.Foliate:73301): Gtk-WARNING **: 12:48:07.623: No IM module matching GTK_IM_MODULE=ibus found

(com.github.johnfactotum.Foliate:73301): GLib-GIO-WARNING **: 12:48:09.585: Error creating IO channel for /proc/self/mountinfo: Permission denied (g-file-error-quark, 2)

** (com.github.johnfactotum.Foliate:73301): WARNING **: 12:48:15.448: Could not open /sys/class/dmi/id/chassis_type: Failed to open file “/sys/class/dmi/id/chassis_type”: Permission denied

** (com.github.johnfactotum.Foliate:73301): WARNING **: 12:48:15.448: Could not open /sys/firmware/acpi/pm_profile: Failed to open file “/sys/firmware/acpi/pm_profile”: Permission denied

** (com.github.johnfactotum.Foliate:73301): ERROR **: 12:48:15.452: Unable to spawn a new child process: Failed to spawn child process “/usr/lib/x86_64-linux-gnu/webkitgtk-6.0/WebKitNetworkProcess” (No such file or directory)
[1]    73301 trace trap (core dumped)  foliate

```

**To Reproduce**
1. `sudo snap install foliate`
2. `foliate` (call in terminal to see stdout)
3. Click `Open...` and choose EPUB file

**Expected behavior**
Open file without error

**Version:**
 - Foliate version: 3.1.1
 - OS/Distribution and version: Ubuntu 22.04
 - Desktop environment: GNOME 42.9 (X11)
 - Installation method: snap

My guess: May be I should do some `snap connect` permissions for foliage? But which ones?

**Comment by drfickle** [comment] 2024-08-02 14:44
I'm getting the same error on Ubuntu 22.04. In case it's book specific, I'm trying to read https://12factor.net/12factor.epub

**Comment by johnfactotum** [comment] 2024-08-07 18:16
Duplicate of #1102

**Closed as not planned by johnfactotum** 2024-08-07 18:16 UTC
Labels: bug, duplicate
