### ISSUE TITLE
No longer starts with gnome 40

### ISSUE THREAD

**Issue by darix** [johnfactotum/foliate#694] opened 2021-03-21 14:41 UTC
**Describe the bug**

Fails to launch properly when running with Gnome 40 libraries

```
(com.github.johnfactotum.Foliate:13502): Gjs-CRITICAL **: 15:32:36.172: JS ERROR: TypeError: "file" is read-only
open@resource:///com/github/johnfactotum/Foliate/js/window.js:1004:9
_init@resource:///com/github/johnfactotum/Foliate/js/window.js:965:29
main/</<@resource:///com/github/johnfactotum/Foliate/js/main.js:310:29
main/<@resource:///com/github/johnfactotum/Foliate/js/main.js:304:22
main@resource:///com/github/johnfactotum/Foliate/js/main.js:474:24
run@resource:///org/gnome/gjs/modules/script/package.js:206:19
@/usr/bin/foliate:9:17
```

**To Reproduce**
1. launch foliate

**Expected behavior**
it should work

**Version:**
 - Foliate version: 2.5.0
 - OS/Distribution and version:openSUSE Tumbleweed
 - Desktop environment: Gnome 40 (released versions were possible otherwise 40.rc)
 - Installation method: rpm
 - gjs 1.68.0

**Comment by johnfactotum** [comment] 2021-03-21 14:58
Duplicate of #689

**Closed** 2021-03-22 10:37 UTC
Labels: bug, duplicate
