### ISSUE TITLE
the translator does not work

### ISSUE THREAD

**Issue by valentingarp** [johnfactotum/foliate#1251] opened 2024-02-13 03:35 UTC
![Captura desde 2024-02-12 22-34-39](https://github.com/johnfactotum/foliate/assets/4121647/df662142-b57a-465d-8266-52e0bdefd3ec)

**Comment by johnfactotum** [comment] 2024-02-15 17:50
Probably a duplicate of #920

**Closed as not planned** 2024-02-22 11:49 UTC
Labels: bug, duplicate
