### ISSUE TITLE
font - smoothing

### ISSUE THREAD

**Issue by Jopp-gh** [johnfactotum/foliate#1302] opened 2024-04-16 13:17 UTC
**Describe the bug**
I see fonts with a red-blue backdrop shadow, maybe an font-smoothing issue?

**To Reproduce**
I didn't change anything in Foliate, every book looks unsharp and with a red-blue backdrop shadow. This effect is even stronger in dark mode, please see the attachments

**Expected behavior**
If I open pdf books in other apps, like xReader (default pdf reader on Mint cin.), then fonts look perfectly normal, sharp and without any (colored) shadow effect

**Version:**
 - Foliate version: 3.1.1
 - OS/Distribution and version: Mint 21.3 
 - Desktop environment: Cinnamon 6.0.4
 - Installation method: Flatpak

**Screenshots**
![Foliate -1](https://github.com/johnfactotum/foliate/assets/48620536/6eeb988c-f32b-48e5-ae5c-85bcbad6c34d)
![Foliate-2](https://github.com/johnfactotum/foliate/assets/48620536/0225b80a-49b8-4f2a-94cc-3688f0b5b250)

**Comment by johnfactotum** [comment] 2024-04-17 01:15
Duplicate of #1129

**Closed as not planned by johnfactotum** 2024-04-17 01:15 UTC
Labels: bug, duplicate
