### ISSUE TITLE
Keeps crashing (built from source ubuntu 22.04)

### ISSUE THREAD

**Issue by iconoclasthero** [johnfactotum/foliate#1171] opened 2023-12-05 17:12 UTC
**Describe the bug**
Randomly crashes with a segmentation fault (within minutes of being launched).
**To Reproduce**
1. Launch program
2. Do nothing with it
3. It crashes
4. See error.

**Screenshots**
"***MEMORY-ERROR***: com.github.johnfactotum.Foliate[381833]: GSlice: assertion failed: sinfo->n_allocated > 0"
"Segmentation fault (core dumped)"

**Version:**
 - Foliate version: 2.6.4
 - OS/Distribution and version: Ubuntu 22.04
 - Desktop environment: Whatever gnome is normally in an updated 22.04 LTS; gnome files says: 42.6
 - Built from GH source.  Seems to work on another 22.04 machine 
 - symlinked com.github...Foliate to /usr/bin/foliate
 - $ apt show gjs: Version: 1.72.4-0ubuntu0.22.04.1

**Additional context**
it seems to have something to do with gjs because i've seen some ephemeral messages (i think in a gui window) about the gsj console having an issue.  didn't capture them because they weren't in the

**Comment by iconoclasthero** [comment] 2023-12-05 17:14
$ foliate Book\ \(2012\).epub 

(com.github.johnfactotum.Foliate:384455): **Gjs-WARNING** **: 12:11:48.794: Unhandled promise rejection. To suppress this warning, add an error handler to your promise chain with .catch() or a try-catch block around your await expression. Stack trace of the failed promise:
  main@resource:///com/github/johnfactotum/Foliate/js/main.js:478:24
  run@resource:///org/gnome/gjs/modules/script/package.js:206:19
  @/usr/bin/foliate:9:17

Segmentation fault (core dumped)

**Comment by johnfactotum** [comment] 2023-12-05 17:15
Duplicate of #1073

**Closed as not planned** 2023-12-05 17:15 UTC
Labels: bug, duplicate
