### ISSUE TITLE
Add the removable-media plug to allow saving downloaded files to /media.

### ISSUE THREAD

**Issue by parto254** [johnfactotum/foliate#332] opened 2020-05-05 09:53 UTC
Foliate installed via snap on Ubuntu 20.04 can't read epubs under /media

**Steps to reproduce**
- sudo snap install foliate
- browse an epub under /media
- foliate returns a "The file cannot be opened error"

More info on this AskUbuntu question:

https://askubuntu.com/questions/1235543/foliate-book-reader-snap-package-cant-open-ebooks-from-ntfs-partitions

**Comment by johnfactotum** [comment] 2020-05-05 14:00
Duplicate of #327.

**Closed by johnfactotum** 2020-05-05 14:00 UTC
