### ISSUE TITLE
Add RSS feed capability

### ISSUE THREAD

**Issue by digitalethics** [johnfactotum/foliate#217] opened 2019-12-09 11:58 UTC
Would you consider implementing a tab to view RSS feeds? The particular use case I have in mind is to be able to track RSS feeds of publishing houses and open access publishers for new and upcoming ebook publications.

**Comment by itprojects** [comment] 2019-12-09 12:11
Is there any RSS feed, that you can point to, for example?

**Comment by digitalethics** [comment] 2019-12-09 12:49
Some examples: 
https://blog.scholarled.org/rss/
https://doabooks.org/doab?func=rss
https://the-digital-reader.com/feed/rss/
https://re-press.org/feed/
https://www.augustverlag.de/en/catalog/feed/
http://global.oup.com/academic/news/?view=RSS
https://about.jstor.org/feed

**Comment by johnfactotum** [comment] 2019-12-09 14:02
Why not just use a dedicated RSS reader?

**Comment by digitalethics** [comment] 2019-12-10 11:26
The problem with dedicated RSS readers (or with RSS for that matter) is that they try to maintain the style of the original site with little to no capabilities to override the original font styles and to filter out pictures and other undesired elements that limit the actual reading experience.

**Comment by itprojects** [comment] 2019-12-10 17:57
@digitalethics maybe what @johnfactotum is trying to get across is that by design Foliate is just a Reader, and it's not meant to be an rss-reader/library. Adding those capabilities, even just for epub, will require very significant effort. In contrast Calibre and Gnome-Books are a library with a reader inside (evince+libgepub). There's even an effort to integrate Foliate with Gnome-Books [see here](https://gitlab.gnome.org/GNOME/gnome-books/issues/35).

**Comment by johnfactotum** [comment] 2019-12-12 03:19
I think this is _out of scope_. You may want to try [Feeds](https://gabmus.gitlab.io/gnome-feeds/), which has a reader mode, or [FeedReader](https://jangernert.github.io/FeedReader/), which I think has different themes that you can choose from. If those are not customizable enough for your needs, you should file a request with their developers.

**Closed by johnfactotum** 2019-12-12 03:19 UTC
