### ISSUE TITLE
Translate functionality  - Remember translation target language last time used

### ISSUE THREAD

**Issue by ralxxx** [johnfactotum/foliate#1395] opened 2024-09-11 21:47 UTC
**Is your feature request related to a problem? Please describe.**
The translation feature is really useful for reading foreign language texts. When opening up the pop-up the translation language suggested seems to be the system language. If he user prefers another language s/he needs to select each time the preferred language manually.    

**Describe the solution you'd like**
Instead, it could be very helpful, if Foliate simply applies again the target language used previously.. 

**Describe alternatives you've considered**
Does not apply 

**Additional context**

**Comment by johnfactotum** [comment] 2024-09-13 01:14
Duplicate of #1159

**Closed as not planned** 2024-09-13 01:15 UTC
Labels: duplicate, enhancement
