### ISSUE TITLE
Foliate crashes upon start

### ISSUE THREAD

**Issue by Svanto24** [johnfactotum/foliate#605] opened 2020-10-08 07:41 UTC
**Describe the bug**
Upon using nautilus to open an EPUB file in foliate, foliate does not start.
Same occurs when foliate is called in console, where the following report is produced:

```
[user@hostname ~]$ foliate

(com.github.johnfactotum.Foliate:1967): Gjs-CRITICAL **: 09:25:18.589: JS ERROR: TypeError: class heritage Handy.Column is not an object or null
@resource:///com/github/johnfactotum/Foliate/js/handy.js:68:7
@resource:///com/github/johnfactotum/Foliate/js/opds.js:25:23
@resource:///com/github/johnfactotum/Foliate/js/library.js:28:63
@resource:///com/github/johnfactotum/Foliate/js/main.js:44:27
@/usr/bin/foliate:9:1


(com.github.johnfactotum.Foliate:1967): Gjs-CRITICAL **: 09:25:18.589: Script /usr/bin/foliate threw an exception
```

**To Reproduce**
1. Go to terminal
2.  run foliate
3. see error

**Expected behavior**
I was hoping foliate would be launched.

**Version:**
 - Foliate version: 2.4.2-1
 - OS/Distribution and version: Arch, freshly updated system as of 7:32 UTC, 8th of October, 2020
 - Desktop environment: none, SwayWM is used as the window manager
 - Installation method: Pacman

**Additional context**
It looks to me like the issue has to do with libhandy, which as far as I know has not been merged into GTK yet, which is why I am confused.

I hope this report is up to the standards of the repository. Thank you very much for your work.

**Comment by johnfactotum** [comment] 2020-10-08 09:52
Looks like duplicate of #603

**Closed** 2020-10-08 09:53 UTC
Labels: bug, duplicate
