### ISSUE TITLE
Flatpak zoom gets reset to 100% every time the app starts 

### ISSUE THREAD

**Issue by alexgirto** [johnfactotum/foliate#1135] opened 2023-11-16 00:40 UTC
Every time the app is opened, zoom is 100%, no matter of previous changes

**To Reproduce**
1. Open Foliate and open a book
2. Change zoom to 170%
3. Close Foliate or go to Library
4. Open Foliate and open a book

**Expected behavior**
Zoom should stay at whatever set in step 2 (170%)

**Screenshots**

**Version:**
 - Foliate version: 3.0.0
 - OS/Distribution and version: SteamOS
 - Desktop environment: KDE
 - Installation method: Flatpak

**Additional context**
This is running on my Steamdeck, in Desktop Mode - so, esentially and Arch Linux environment

**Comment by johnfactotum** [comment] 2023-11-16 01:19
This is the expected behavior. See #993.

**Comment by alexgirto** [comment] 2023-11-16 01:51
But this default to 100% is annoying when going back to the same book. I guess you can't please everyone :)

**Comment by johnfactotum** [comment] 2023-11-16 02:04
It would possible to add support for per-book settings. Alternatively it can have a global default zoom setting.

Alternatively, there is a non-standard CSS property `zoom` that you can use in the [user stylesheet](https://github.com/johnfactotum/foliate/blob/gtk4/docs/faq.md#can-i-set-my-own-custom-css-styles):
```css
body {
    zoom: 150%;
}
```

**Comment by signdo** [comment] 2023-11-16 04:00
If you just want to make the text bigger because it's too small, maybe try adjusting the font size. The font size is set globally.

step1: Open a book
step2: Click the vertical [...] in the upper right corner
step3: Click `Font & Layout Settings`
step4: Change `Default Font Size`

I think this setting should be placed in the main interface of the software.

**Comment by alexgirto** [comment] 2023-11-16 06:06
Please have a look at the attached. The default_ images are just that, whilst the user_ images are after applying 

body { zoom: 170%; }
I'd expect default_170 = user_100, but that doesn't happen. 

Thank you,
Alex



    On Wednesday, November 15, 2023 at 06:04:17 p.m. PST, John Factotum ***@***.***> wrote:  
 
 


It would possible to add support for per-book settings. Alternatively it can have a global default zoom setting.

Alternatively, there is a non-standard CSS property zoom that you can use in the user stylesheet:
body {
    zoom: 150%;
}

**Comment by alexgirto** [comment] 2023-11-16 06:09
It appears e-mail attachments may not have gone through, so trying again, here:

The default_ images are just that, whilst the user_ images are after applying

body { zoom: 170%; }
I'd expect default_170 = user_100, but that doesn't happen.
![default_100](https://github.com/johnfactotum/foliate/assets/5903406/dc6bf569-0868-4ea1-86a3-28a72cade0c2)
![default_170](https://github.com/johnfactotum/foliate/assets/5903406/650e00a1-e785-4be3-aa64-77e6a9f6cf0c)
![user_100](https://github.com/johnfactotum/foliate/assets/5903406/cb2e8be9-5ec5-4515-8c36-0967b8db4216)
![user_170](https://github.com/johnfactotum/foliate/assets/5903406/3ad5dc9f-b3a8-43f2-b49f-385b3bdfe0f1)

**Comment by johnfactotum** [comment] 2023-11-17 00:32
Yes, that's expected. The CSS only affects the body of the page, not the layout.

**Comment by johnfactotum** [comment] 2023-11-28 03:35
Closing in favor of #1158

**Closed by johnfactotum** 2023-11-28 03:35 UTC
Labels: question
