### ISSUE TITLE
Add shortcut to open Library

### ISSUE THREAD

**Issue by lobaluna** [johnfactotum/foliate#810] opened 2021-11-20 19:49 UTC
A shortcut will avoid the use of the mouse. It's faster ;D

**Comment by johnfactotum** [comment] 2021-11-21 09:41
Duplicate of #631

**Closed by johnfactotum** 2021-11-21 09:41 UTC
Labels: enhancement

**Comment by lobaluna** [comment] 2021-11-21 20:14
Sorry, John, but it is not working:

 johnfactotum commented on Sep 15
Fixed with 42388fd

I am on Manjaro using Foliate and Ctrl-h does not open the Library.

**Comment by johnfactotum** [comment] 2021-11-22 08:55
The fix is not included in the latest release yet.
