### ISSUE TITLE
Improperly rendered table of contents

### ISSUE THREAD

**Issue by o1Suleyman** [johnfactotum/foliate#1419] opened 2024-10-29 14:24 UTC
**Describe the bug**
The table of contents isn't rendered properly in this book. You can download the book by clicking GET on libgen: http://library.lol/main/DC80DF2FC79D5C35A6C2767B1C16501C

**To Reproduce**
1. Download and open the book in Foliate
2. Scroll to the table of contents
3. See broken table of contents

**Expected behavior**
Table of contents renders/loads properly

**Screenshots**
![Screenshot from 2024-10-29 18-20-54](https://github.com/user-attachments/assets/8214bfb2-0bfd-480c-aca1-6ea5aba7bc65)

**Version:**
 - Foliate version: 3.1.1
 - OS/Distribution and version: Ubuntu 24.04
 - Desktop environment: GNOME 46
 - Installation method: Snap

**Comment by johnfactotum** [comment] 2024-10-30 08:55
Duplicate of #1255

**Closed as not planned by johnfactotum** 2024-10-30 08:55 UTC
Labels: bug, duplicate
