### ISSUE TITLE
.PDF

### ISSUE THREAD

**Issue by SaezSays** [johnfactotum/foliate#572] opened 2020-08-23 18:46 UTC
Do you think you can add that .PDF can be read? It is the best reader for Linux, the interface is minimalist but I have many books in .PDF that it does not recognize, only the .ePub

**Comment by apandada1** [comment] 2020-08-23 18:56
GNU/Linux distros have many very good PDF readers with lots of functionalities (e.g. Okular, Evince, Atril). Foliate works very well as a EPUB/MOBI reader, and usual document readers (e.g. Okular) cannot render them well. 

Let's not make Foliate over complicated.

**Comment by gregory-opera** [comment] 2020-08-25 20:09
I only just started using Foliate, but I was surprised to see that there was no support for the PDF... Sure, there are various PDF viewers out there that "just work" - but Foliate offers a better UI and various features that are better-suited to viewing comics, magazines and the occasional eBook in it, rather than an alternative like Evince.

The lack of support for the PDF is not a deal-breaker, because alternative PDF viewers are wildly available (not to mention the fact that most popular Linux-based operating systems include a PDF viewer by default)... But it does ruin the experience, considering many magazines and eBooks, plus the occasional comic, are distributed in the PDF.

Whilst I'm not a developer myself, I don't imagine that it would be all that difficult to add support for the PDF, either - the format has been an "open" format for quite some time now, and the specifics of the PDF are well-documented.

**Comment by johnfactotum** [comment] 2020-08-28 04:41
Duplicate of #139

**Closed by johnfactotum** 2020-08-28 04:41 UTC
