### ISSUE TITLE
Last page is inaccessable on epubs that lack a cover page

### ISSUE THREAD

**Issue by Mar2ck** [johnfactotum/foliate#285] opened 2020-04-08 20:21 UTC
I'm using Calibre's ebook-convert command to convert txt and html files to epub. By default it automatically generate a cover page but this can be disabled using --no-default-epub-cover. However with these no cover epubs, foliate will stop close to the end and wont let you go to the last page.

With cover version, second to last page (ebook-convert test.txt test-with-cover.epub)
Bottom right button works:
![with cover](https://user-images.githubusercontent.com/6759254/78828474-af5b8c80-79dc-11ea-9f93-e32ccbfa8d28.png)

Without cover version, second to last page (ebook-convert test.txt test-without-cover.epub --no-default-epub-cover)
Bottom right button is disabled and you can't use arrow keys or anything to get to the end of the book:
![without cover](https://user-images.githubusercontent.com/6759254/78828589-d4e89600-79dc-11ea-8d9b-516d13167bba.png)

Flatpak and snap versions dont make a difference, the problem goes away with spacing set to 1 (i have it on 1.5), here is a zip with the files im using: https://drive.google.com/open?id=16ee0qKRoGbhUhfQl_9jtb4CZwVzWBDaJ

**Comment by Mar2ck** [comment] 2020-04-08 20:34
It looks like resizing the window makes the bug go away but it comes back whenever the epub is opened again

**Comment by johnfactotum** [comment] 2020-04-09 02:39
Somehow I can't reproduce this consistently, but it does happen sometimes.

**Comment by johnfactotum** [comment] 2023-03-07 15:07
I can't seem to reproduce this anymore. Besides, it's a bit mysterious why the cover page would make any difference if they are different sections. It might be possible when using the continuous paginated layout in Epub.js, but Foliate doesn't use that.

Anyway, hopefully this is one of those layouting quirks that has been fixed by the new renderer. If not, feel free to comment or open a new issue.

**Closed by johnfactotum** 2023-03-07 15:07 UTC
Labels: bug, epub.js
