### ISSUE TITLE
Change name for the binary in deb package

### ISSUE THREAD

**Issue by Acvarium** [johnfactotum/foliate#467] opened 2020-06-18 13:00 UTC
I know, that some people use menu to run their applications and that is why we have .desktop files. And I know that I can create symlink. But some of us run applications with command line, and name of the application should not look like this:
![image](https://user-images.githubusercontent.com/463177/85022483-08356700-b17c-11ea-8d22-786821b5a416.png)

**Comment by johnfactotum** [comment] 2020-06-18 14:01
Duplicate of #22.

**Closed** 2020-06-18 14:02 UTC
Labels: duplicate
