### ISSUE TITLE
glib2 2.72.0 causes "Empty response"

### ISSUE THREAD

**Issue by tummychow** [johnfactotum/foliate#878] opened 2022-03-23 06:41 UTC
**Describe the bug**
Opening any epub causes foliate to show "Could not open file" with this output:

```
(com.github.johnfactotum.Foliate:16547): Gjs-WARNING **: 23:22:45.931: JS ERROR: Error: Empty Response
_init/<@resource:///com/github/johnfactotum/Foliate/js/epubView.js:623:57
_handleAction@resource:///com/github/johnfactotum/Foliate/js/epubView.js:886:22
_init/<@resource:///com/github/johnfactotum/Foliate/js/epubView.js:617:18
main@resource:///com/github/johnfactotum/Foliate/js/main.js:478:24
run@resource:///org/gnome/gjs/modules/script/package.js:206:19
@/usr/bin/foliate:9:17
```

**To Reproduce**
Open any epub with glib2 2.72.0

**Version:**
This is with Arch Linux's foliate 2.6.4-1 and glib2 2.72.0-1. Downgrading to Arch's glib2 2.70.4-2 fixes the issue. Honestly, I have no idea why. From past foliate issues, I assumed some other gtk package was involved (eg webkit2gtk 2.36.0-1 to 2.34.6-1, gjs 2:1.70.2-1 to 2:1.70.1-2, js78 78.15.0-4 to 78.15.0-3) but those downgrades don't fix it; only the glib2 downgrade has any effect.

**Comment by ksdrummer** [comment] 2022-03-23 21:33
I confirm that I have the exact same bug on arch : foliate 2.6.4 and 2.72.0-1.

`(com.github.johnfactotum.Foliate:362831): Gjs-WARNING **: 17:27:09.374: JS ERROR: Error: Empty Response
_init/<@resource:///com/github/johnfactotum/Foliate/js/epubView.js:623:57
_handleAction@resource:///com/github/johnfactotum/Foliate/js/epubView.js:886:22
_init/<@resource:///com/github/johnfactotum/Foliate/js/epubView.js:617:18
main@resource:///com/github/johnfactotum/Foliate/js/main.js:478:24
run@resource:///org/gnome/gjs/modules/script/package.js:206:19
@/usr/bin/foliate:9:17`

**Comment by johnfactotum** [comment] 2022-03-24 07:11
For some reason I can't seem to reproduce this. Have glib2 2.72.0-1. Built both 2.6.4 and master and all seems fine.

**Comment by tummychow** [comment] 2022-03-24 07:27
Interesting... I tried a few other downgrades thinking maybe glib2 was a red herring, but these also have no effect:
- glib-networking 1:2.72.0-1 to 1:2.70.1-1
- gobject-introspection-runtime 1.72.0-1 to 1.70.0-5

I'm not sure how something low in the stack (like glib2) could cause this error. Any additional debugging I can do to help?

**Comment by johnfactotum** [comment] 2022-03-24 10:15
I don't really have any idea. But here's a somewhat minimal script for reproducing the problem:

```js
#!/usr/bin/gjs
const fetchURI = 'file:///home/user/test'
const pageURI = 'file:///usr/share/com.github.johnfactotum.Foliate/assets/epub-viewer.html'

imports.gi.versions.Gtk = '3.0'
imports.gi.versions.WebKit2 = '4.0'
const { Gtk, WebKit2 } = imports.gi

const app = new Gtk.Application({ application_id: 'org.gtk.Example' })

const script = `fetch('${fetchURI}').then(res => res.text()).then(text => alert(text))`

app.connect('activate', () => {
    const win = new Gtk.ApplicationWindow({ application: app })
    const webView = new WebKit2.WebView({
        settings: new WebKit2.Settings({
            enable_write_console_messages_to_stdout: true,
            enable_developer_extras: true,
            allow_universal_access_from_file_urls: true,
        }),
    })
    webView.connect('load-changed', (_, event) =>
        event === WebKit2.LoadEvent.FINISHED
            ? webView.run_javascript(script, null, () => {}) : null)
    webView.load_uri(pageURI)
    win.add(webView)
    win.show_all()
})

app.run([])
```

To run this script you first need to make sure that `/home/user/test` exists by running, say, `echo "Hello" > /home/user/test`. The `pageURI` on the second line can be change to point to whatever local HTML page you have (in case Foliate isn't installed on the default location). If it alerts "Hello", then it works. Otherwise you would see the "Empty response" error either logged in the terminal or in WebKit's devtools console.

If one can reproduce with this GJS example, then it's probably a good idea to try to reproduce it in C as well and submit a bug to the WebKitGTK devs.

**Comment by tummychow** [comment] 2022-03-24 20:36
Hmm, running through those steps (with `echo "Hello" > /mnt/home/test`) gives me this output:

```
CONSOLE SECURITY ERROR Cross origin requests are only supported for HTTP.
CONSOLE JS ERROR Fetch API cannot load file:///mnt/home/test due to access control checks.
CONSOLE JS ERROR Unhandled Promise Rejection: TypeError: Load failed
```

which seems... like an error, but not quite the same as the "Empty response" error. Downgrading glib2 does fix it; the window shows a "Hello" alert with this output instead:

```
CONSOLE SECURITY ERROR The Content Security Policy directive 'sandbox' is ignored when delivered via an HTML meta element.
```

I'll see about filing that upstream bug.

**Comment by johnfactotum** [comment] 2022-03-25 08:14
Perhaps it's related to how your filesystem is set up, as I still cannot reproduce it.

In any case, in the future we really want to stop making requests to files, which is not only unreliable, but also insecure, and bad for performance as the whole file is loaded in memory. Instead it should either set up a local server, or somehow get a `File` object.

**Comment by ksdrummer** [comment] 2022-03-25 16:02
I don't know if it's really useful, but the script gave me the same output...

**Comment by tummychow** [comment] 2022-03-25 19:58
Yeah I'm also going to investigate miscellaneous filesystem and DNS related things. glib2 2.72.0 has other peculiar behaviors on my system (eg the GTK file picker no longer shows mountpoints in the "other locations" list) which seem to be in the same ballpark as this. There must be something that makes the file:// request "look" cross-origin that's specific to my setup.

**Comment by johackim** [comment] 2022-03-26 16:27
Temporary solution on Arch Linux with the [downgrade command](https://github.com/archlinux-downgrade/downgrade) :

```bash
sudo downgrade glib2
```

**Comment by truealex** [comment] 2022-04-05 09:39
I confirm there is a bug. if I roll back to the previous version of glibc, after rebooting, my desktop and taskbar do not appear. How to read books now?

**Comment by Kandelai** [comment] 2022-04-07 20:07
I rolled back using @johackim solution and Foliate worked for me as well, using Garuda Linux/Arch.

**Comment by lhirlimann** [comment] 2022-04-14 07:49
[strace.log.gz](https://github.com/johnfactotum/foliate/files/8487278/strace.log.gz)

Strace log of the issue on fedora 36 if it can help.

**Comment by Kandelai** [comment] 2022-04-17 14:54
Appears with the latest Arch updates, downgrading glib2 no longer works, thus no YacReader, also, still doesn't work with latest glib2 2.72.0-1. Running in terminal gets me;

'YACReader: error while loading shared libraries: libicuuc.so.70: cannot open shared object file: No such file or directory'

**Comment by FedericoCeratto** [comment] 2022-04-18 10:55
FWIW the bug seems to appear on [Debian as well](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1009669) but I cannot reproduce it on my hosts using glib 2.72.1

**Comment by thebiblelover7** [comment] 2022-04-21 10:29
I can reproduce this too

**Comment by tummychow** [comment] 2022-04-22 01:10
Some more investigation updates:

- 2.72.1 does not fix the issue on Arch
- I was able to bisect the issue to glib2 commit https://gitlab.gnome.org/GNOME/glib/-/commit/60173d0a387b45016684be8846c291dabd0aa5e8 which is rather horrifying because this is a merge of changes from an upstream library and I can't imagine how it's related. At least it gives me some hints on how some systems repro and others don't.

**Comment by apandada1** [comment] 2022-04-22 07:25
I cannot reproduce this issue with glib2 `2.72.1-1` in Arch Linux MATE, and EndeavourOS KDE. Is this issue specific to GNOME?

**Comment by moll** [comment] 2022-04-22 09:27
I can confirm @tummychow's comment that upgrading to glib2 v2.72.1-1 on Arch Linux **does not** seem to fix the issue.

**Comment by bgvaughan** [comment] 2022-04-22 20:38
I filed a bug for Debian. I'm using Debian Sid with XFCE, not with Gnome, and foliate still doesn't work after updating to glib2 v2.72.1-1.

**Comment by Kandelai** [comment] 2022-04-24 17:28
I am confused, why are users filing bug reports with their distro maintainers? Isn't this an issue for the Foliate maintainer to update Foliate to work with the latest Glib2?

**Comment by tummychow** [comment] 2022-04-24 20:32
@Kandelai pretty sure foliate is already doing the right thing here - [it's passing the option](https://github.com/johnfactotum/foliate/blob/811554d8db25b5069e10f0707b9f9e66c571a031/src/epubView.js#L582) that [disables cross origin restrictions for file urls](https://webkitgtk.org/reference/webkit2gtk/stable/WebKitSettings.html#WebKitSettings--allow-file-access-from-file-urls). So the fact that it's failing a file url request, with a cross origin error message, certainly looks like an upstream bug. (As I've already said, I don't know _how_ webkit2gtk and glib2 can interact in a way that causes this outcome. My guess is both are at fault in some way and glib2 happened to to be the one that revealed the issue.)

**Comment by FedericoCeratto** [comment] 2022-04-24 20:34
@Kandelai because sometimes bugs are due to interactions between library versions or other OS components and so on and can be fixed by the package maintainer.
[I'm the maintainer of the Debian package]

**Comment by eksperimental** [comment] 2022-04-24 22:29
If you are on Arch Linux and you use Cinnamon, DO NOT DOWNGRADE glib2.
Your graphical interface will become unusable.

**Comment by adamensler** [comment] 2022-04-27 05:19
Arch w/ Gnome shell 42 here. Encountered the same issue and found the downgrade trick above worked.

**Comment by rokezu** [comment] 2022-05-11 21:34
Just to confirm the same bug on Arch Linux as fellow users of that distribution and same versions, hopefully a solution will be found. I'd rather not mess with mime.cache or downgrades of core packages.

**Comment by eksperimental** [comment] 2022-05-11 21:40
> Just to confirm the same bug on Arch Linux as fellow users of that distribution and same versions, hopefully a solution will be found. I'd rather not mess with mime.cache or downgrades of core packages.

Do not downgrade! I messed up my environment.

You can install it from Snap store, it works just fine.

**Comment by Vednier** [comment] 2022-05-16 20:41
Oh well, having same problem on Ubuntu Mate 22.04 with same glib 2.72, so its global problem. Interestingly enough, Atril - Mate's standard viewer for PDF and epub have lost ability to show epub file at same time.

**Comment by kauesena** [comment] 2022-05-18 22:06
Since my last comment, I have reinstalled ArchLinux and I can now use Foliate 2.6.4 (the most recent) with glib2 2.72 via the package foliate from the Community repository.

**Comment by apandada1** [comment] 2022-05-19 02:06
Reinstalling Arch created a new version of mime.cache which might have
fixed the issue.

**Comment by kauesena** [comment] 2022-05-19 02:23
@winteriscariot I have just rechecked the versions (using `pacman -Qi`) of glib2 and Foliate and they are respectively 2.72.1-1 and 2.6.4-1.

**Comment by kauesena** [comment] 2022-05-19 02:34
If you (plural) need me to provide more information on my system or run any test, I'd be happy to oblige. I can think of no difference between the current installation from the previous one except that I've replaced the common kernel with the zen kernel and that I've started using LVM. However, I do not think such changes would interfere. The change must be of the sort @apandada1 mentioned.

**Comment by jeois** [comment] 2022-05-19 04:43
You don't need to delete `mime.cache` which will reset all file type associations.  It's not a big deal, but it can be a hassle to set them again.  I definitely wouldn't downgrade glib2 based on what people said about that creating other issues.

Instead, you can use your Desktop Environment's settings manager to **simply remove all apps associated with "html" and that'll fix it**.  In my case, I used KDE's System Settings (systemsettings5) to delete the list of apps under Applications>File Associations>text>html.  This way only` .html `files are affected.  For some reason, dolphin (KDE's file manager) still opens html files with Firefox, so this workaround didn't even diminish other functionality.  I'm sure other desktops also have mime settings editors, and you can use those to disable html file associations.  

For reference, Okular works regardless.  I'm on Arch/Manjaro using glib2 (2.71.1-1) and foliate (2.6.4-1).  BTW, the latest webkit2gtk (2.36.2-1) update didn't resolve this issue.

**Comment by rokezu** [comment] 2022-05-20 23:29
Well, I deleted `mime.cache` (mine was a file from 2011, not updated since then‽) and Foliate is working again, rebooted several times for a couple of days now, still working.  File associations and such for other apps didn't change.  I have no idea what is going on with these modern apps that resort to such convoluted ways to do an `fopen()` but well... So far this is working for me? In my case I just wanted to double check some ePubs from Humble Bundle that can't be opened correctly in my e-reader or with Calibre, and Foliate opened and formatted it successfully!  I'm reading a comic at the moment. 😄📖

**Comment by argosatcore** [comment] 2022-05-24 23:15
> Well, I deleted `mime.cache` (mine was a file from 2011, not updated since then‽) and Foliate is working again, rebooted several times for a couple of days now, still working. File associations and such for other apps didn't change. I have no idea what is going on with these modern apps that resort to such convoluted ways to do an `fopen()` but well... So far this is working for me? In my case I just wanted to double check some ePubs from Humble Bundle that can't be opened correctly in my e-reader or with Calibre, and Foliate opened and formatted it successfully! I'm reading a comic at the moment. smilebook

This worked for me too on Debian Sid. After deleting ~/.local/share/mime.cache foliate started working again without any apparent issues. However, if I restore the deleted mime.cache file or recreate it via `update-mime-database ~/.local/share/mime`, the issue resurfaces.

**Comment by chillycuz** [comment] 2022-05-31 05:44
I have the same exact experience as @argosatcore on fully updated Arch Linux 5.18, including failure after update-mime-database.

**Comment by feute** [comment] 2022-06-22 04:32
I started having this issue on Fedora 36 with everything up to date. Deleting `~/.local/share/mime/mime.cache` solved it.

**Comment by Arkoprovo1996** [comment] 2022-06-26 14:48
> I started having this issue on Fedora 36 with everything up to date. Deleting `~/.local/share/mime/mime.cache` solved it.

Wow, yes. I did too, on Manjaro and it fixed the issue. Thanks so much!! ♥

**Comment by truealex** [comment] 2022-06-28 11:43
on latest Arch advice to delete mime.cache file does not work

**Comment by argosatcore** [comment] 2022-07-05 23:28
This issue has been fixed on Debian Sid. [1] It looks like the culprit was `glib` and is now fixed on version 2.72.3. 

After running `update-mime-database ~/.local/share/mime`, I can now open EPUB files without a problem, and  `foliate` works as expected.

_______

[1]  See: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1009669

**Comment by wenzezlaus** [comment] 2022-07-06 05:12
As well, on Arch the issue is fixed with glib2 updated to v. 2.72.3

**Comment by kauesena** [comment] 2022-07-06 22:18
I second what @wenzezlaus reported. Somehow the issue reappeared to me some days ago but updating the system getting `glib2.72.3` made foliate work again.

**Comment by johnfactotum** [comment] 2022-09-23 19:05
Closing as it seems to have been fixed.

**Closed by johnfactotum** 2022-09-23 19:05 UTC
Labels: bug
