### ISSUE TITLE
Bad performance with one Gutenberg release of "Frankenstein"

### ISSUE THREAD

**Issue by ell1e** [johnfactotum/foliate#1052] opened 2023-06-27 20:47 UTC
**Describe the bug**
Foliate for me shows a hard to endure level of bad performance with one Gutenberg release of "Frankenstein". The affected book is the EPUB3 version of this: https://www.gutenberg.org/ebooks/42324 direct link to the EPUB3 file: https://www.gutenberg.org/ebooks/42324.epub3.images

**To Reproduce**
1. Download and open above file
2. Slowly turn pages just a few times, see how foliate reacts

**Expected behavior**
Page turn takes an acceptable amount of time. This is not the case, Foliate gets stuck for 10 seconds and longer trying to do a basic page turn and it's just kind of a disaster. At least that's what happens on my machine.

**Screenshots**
probably not relevant

**Version:**
 - Foliate version: 2.6.4
 - OS/Distribution and version: Fedora 37
 - Desktop environment: GNOME 3, some recent version
 - Installation method: flathub

**Additional context**

**Comment by johnfactotum** [comment] 2023-06-28 06:07
If you mean all page turns, including page turns within a section, are slow, I'm afraid can't reproduce it. It turns instantly for me.

If you mean that it takes a long time to load a long section (i.e. an HTML page in the spine), that is a limitation of CSS multicolumn based pagination (though for sections in this particular book, it takes about 2 seconds for me). This probably won't be fixed in the foreseeable future, though there's certainly room for improvement on the browser engine's side (multicolumn layout in WebKitGTK seems to be at least 3-5x slower compared to Firefox and Chromium).

**Closed** 2023-07-03 11:35 UTC
Labels: bug
